/**
 * PostgREST rejects unknown columns (PGRST204). Local rows may carry nested objects
 * (trip_rig.gear) or client-only extras; the wire payload is a column allowlist.
 */
import type { SyncEntity } from "@/core/sync/outbox";

const COLUMNS: Record<SyncEntity, ReadonlySet<string>> = {
  trip: new Set([
    "id",
    "angler_id",
    "spot_id",
    "water_class",
    "started_at",
    "started_tz",
    "ended_at",
    "ended_tz",
    "local_date",
    "platform",
    "angler_count",
    "target_species_ids",
    "zero_catch_confirmed_at",
    "catch_log_confidence",
    "conditions_verdict",
    "notes",
    "capture_mode",
    "client_created_at",
    "created_at",
    "client_updated_at",
    "deleted_at",
  ]),
  trip_rig: new Set([
    "id",
    "angler_id",
    "trip_id",
    "revision",
    "effective_from",
    "spot_id",
    "platform",
    "tackle_item_id",
    "bait_type_id",
    "depth_fished_m",
    "target_species_ids",
    "created_at",
    "slot",
    "name",
    "setup_type",
    "live_bait",
    "retired_at",
  ]),
  catch: new Set([
    "id",
    "angler_id",
    "trip_id",
    "caught_at",
    "caught_tz",
    "local_date",
    "lat",
    "lng",
    "gps_accuracy_m",
    "resolution_state",
    "dismissed_reason",
    "resolved_at",
    "resolved_by",
    "resolution_source",
    "species_id",
    "species_other",
    "outcome",
    "disposition",
    "quantity",
    "length_mm",
    "weight_g",
    "size_estimated",
    "spot_id",
    "platform",
    "tackle_item_id",
    "bait_type_id",
    "depth_fished_m",
    "rig_id",
    "rig_revision",
    "inherited_fields",
    "presentation",
    "bottom_depth_m",
    "structure_type_id",
    "cover_type_id",
    "notes",
    "capture_mode",
    "client_created_at",
    "created_at",
    "client_updated_at",
    "deleted_at",
    "rig_slot",
    "location_condition_id",
    "location_name",
    "current_term",
    "current_strength",
    "structure_type_ids",
    "water_color_id",
    "water_clarity_id",
    "regulation_snapshot",
    "tags",
    "favorite",
  ]),
  catch_gear: new Set([
    "id",
    "angler_id",
    "catch_id",
    "tackle_item_id",
    "role",
    "label",
    "detail",
    "created_at",
    "client_updated_at",
    "deleted_at",
  ]),
  condition_snapshot: new Set([
    "id",
    "angler_id",
    "trip_id",
    "catch_id",
    "kind",
    "observed_at",
    "water_class",
    "geo_cell_1km",
    "pressure_hpa",
    "pressure_trend_3h_hpa",
    "air_temp_c",
    "wind_speed_ms",
    "wind_dir_deg",
    "cloud_cover_pct",
    "moon_phase_angle_deg",
    "moon_illumination_fraction",
    "days_from_full",
    "days_from_new",
    "moonrise_utc",
    "moonset_utc",
    "sunrise_utc",
    "sunset_utc",
    "civil_twilight_begin_utc",
    "civil_twilight_end_utc",
    "minutes_from_sunrise",
    "minutes_from_sunset",
    "day_of_year",
    "water_temp_c",
    "surface_condition",
    "bait_present",
    "bird_activity",
    "tide_height_m",
    "tide_rate_m_per_hr",
    "tide_state",
    "tide_pct_through_cycle",
    "twelfths_hour",
    "tide_range_m",
    "tide_curve",
    "current_term",
    "current_bearing_deg",
    "current_axis_revision",
    "current_strength",
    "swell_height_m",
    "swell_period_s",
    "swell_dir_deg",
    "water_clarity_id",
    "water_color_id",
    "visibility_cm",
    "water_level_trend",
    "lake_elevation_m",
    "seasonal_pattern_id",
    "enrichment_status",
    "snapshot_basis",
    "provenance",
    "algo_version",
    "enrichment_attempts",
    "enrichment_last_error",
    "created_at",
    "deleted_at",
  ]),
  location_condition: new Set([
    "id",
    "angler_id",
    "trip_id",
    "spot_id",
    "name",
    "current_term",
    "current_strength",
    "structure_type_ids",
    "bottom_depth_m",
    "water_color_id",
    "water_clarity_id",
    "notes",
    "created_at",
    "client_updated_at",
    "deleted_at",
  ]),
  journal_entry: new Set([
    "id",
    "angler_id",
    "entry_date",
    "entry_tz",
    "body",
    "capture_mode",
    "client_created_at",
    "created_at",
    "client_updated_at",
    "deleted_at",
  ]),
  spot: new Set([
    "id",
    "angler_id",
    "name",
    "water_class",
    "water_body_type",
    "lat",
    "lng",
    "tide_station_id",
    "weather_station_id",
    "buoy_id",
    "alongshore_bearing_deg",
    "offshore_bearing_deg",
    "axis_source",
    "axis_revision",
    "created_at",
    "client_updated_at",
    "deleted_at",
  ]),
  tackle_item: new Set([
    "id",
    "angler_id",
    "label",
    "lure_class_id",
    "color",
    "size_label",
    "is_favorite",
    "created_at",
    "client_updated_at",
    "deleted_at",
  ]),
};

export function pickPostgrestPayload(
  entity: SyncEntity,
  payload: Readonly<Record<string, unknown>>,
): Record<string, unknown> {
  const allowed = COLUMNS[entity];
  const out: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(payload)) {
    if (allowed.has(key)) out[key] = value;
  }
  return out;
}
