#!/usr/bin/env node
/**
 * ADR 005 §2 — design tokens: JSON is the truth, CSS is output.
 *
 *   src/core/design/tokens.json  ->  src/app/tokens.generated.css
 *
 * The JSON is ux-ui's file: they own the values and the semantic naming. This script owns
 * only the transport. The same JSON is read by scripts/tokens-swift.mjs the day ios/
 * exists — which is the whole reason the source is language-neutral JSON.
 *
 *   npm run tokens         write the CSS
 *   npm run tokens:check   fail if the committed CSS is stale (CI drift check)
 */
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const SOURCE = join(root, "src/core/design/tokens.json");
const OUTPUT = join(root, "src/app/tokens.generated.css");

const tokens = JSON.parse(readFileSync(SOURCE, "utf8"));
const isMeta = (key) => key.startsWith("$");

/** Tailwind v4 generates utilities directly from `@theme` custom properties. */
function build() {
  const out = [
    "/*",
    " * GENERATED BY scripts/tokens.mjs — DO NOT EDIT.",
    " * Edit src/core/design/tokens.json and run `npm run tokens`.",
    " * A pull request that hand-edits this file is wrong even if it works (ADR 005 §2).",
    " */",
    "",
    "@theme {",
    "  /* Colour — semantic roles, see docs/design/02-semantic-colors.md */",
  ];

  for (const [name, value] of Object.entries(tokens.color)) {
    if (isMeta(name)) continue;
    out.push(`  --color-${name}: ${value.light};`);
  }

  out.push("", "  /* Type scale — 16px floor. Nothing in this app renders below it. */");
  for (const [name, def] of Object.entries(tokens.fontSize)) {
    if (isMeta(name)) continue;
    out.push(`  --${name}: ${def.value};`);
    out.push(`  --${name}--line-height: ${def.lineHeight};`);
    out.push(`  --${name}--font-weight: ${def.weight};`);
  }

  out.push("", "  /* Families — placeholders; see docs/design/README.md open question */");
  for (const [name, value] of Object.entries(tokens.fontFamily)) {
    if (isMeta(name)) continue;
    out.push(`  --font-${name}: ${value};`);
  }

  out.push("", "  /* Spacing — 4px base; p-3 is the 12px interactive floor */");
  for (const [name, value] of Object.entries(tokens.spacing)) {
    if (isMeta(name)) continue;
    // `space-4` becomes `--spacing-4`, so the utility reads `p-4`, not `p-space-4`.
    out.push(`  --spacing-${name.replace(/^space-/, "")}: ${value};`);
  }

  out.push("", "  /* Touch targets — 48px floor, 68px primary, 88px quick mark */");
  for (const [name, value] of Object.entries(tokens.touchTarget)) {
    if (isMeta(name)) continue;
    out.push(`  --spacing-touch-${name}: ${value};`);
  }

  out.push("", "  /* Opacity */");
  for (const [name, value] of Object.entries(tokens.opacity)) {
    if (isMeta(name)) continue;
    out.push(`  --opacity-${name}: ${value};`);
  }

  out.push("", "  /* Corner radius */");
  for (const [name, value] of Object.entries(tokens.radius)) {
    if (isMeta(name)) continue;
    // `radius-sm` becomes `--radius-sm`, so the utility reads `rounded-sm`.
    out.push(`  --${name}: ${value};`);
  }

  out.push("", "  /* Elevation — only the shadow is a utility; fill and border are  */");
  out.push("  /* compositions documented in docs/design/01-foundations.md §4.2.    */");
  for (const [name, def] of Object.entries(tokens.elevation)) {
    if (isMeta(name) || !def.shadow) continue;
    out.push(`  --shadow-${name}: ${def.shadow};`);
  }

  out.push("}", "");

  // A dark block is emitted only for tokens whose dark value actually differs. Today none
  // do: V1 is dark-only by design (tokens.json $darkOnlyByDesign), and the duplicated
  // `light` values are an honest placeholder, not a second theme.
  const differing = Object.entries(tokens.color).filter(
    ([name, v]) => !isMeta(name) && v.dark !== v.light,
  );
  if (differing.length > 0) {
    out.push("@media (prefers-color-scheme: dark) {", "  :root {");
    for (const [name, v] of differing) out.push(`    --color-${name}: ${v.dark};`);
    out.push("  }", "}", "");
  }

  return out.join("\n");
}

const css = build();

if (process.argv.includes("--check")) {
  let current = "";
  try {
    current = readFileSync(OUTPUT, "utf8");
  } catch {
    console.error("tokens: src/app/tokens.generated.css is missing. Run `npm run tokens`.");
    process.exit(1);
  }
  if (current !== css) {
    console.error(
      "tokens: src/app/tokens.generated.css is stale or hand-edited.\n" +
        "        Run `npm run tokens` and commit the result.",
    );
    process.exit(1);
  }
  console.log("tokens: generated CSS is up to date.");
} else {
  writeFileSync(OUTPUT, css);
  console.log(`tokens: wrote ${OUTPUT.replace(root + "/", "")}`);
}
