-- Hawaii v2 (2026-09-02): DLNR Regulated Fishing Areas layer (verbatim).
-- GENERATED from the bundle via gen-hi-rfa-v2.mts. Insert-only + pack upsert.

insert into public.reg_area (id, authority, kind, name, parent_id, boundary_geojson, source_url, verified_at, notes) values
  ('hi-west-hawaii-rfma', 'hawaii_dar', 'conservation_area', 'West Hawai''i Regional Fishery Management Area (Ka Lae, Ka''ū to ''Ūpolu Point, North Kohala)', null, '[[-156.08,18.92],[-155.68,19.75],[-156.05,20.26],[-155.95,19],[-155.99,18.94],[-156.08,18.92]]', 'https://dlnr.hawaii.gov/dar/fishing/fishing-regulations/regulated-areas/regulated-fishing-areas-on-hawaii/', '2026-09-02', 'HAR 13-60.4. Extends Ka Lae (South Point) to ''Ūpolu Point and seaward to the State''s management limit; includes the Kahalu''u Bay, Waiaua Bay, and Kikaua–Makalawena Fish Replenishment Areas (fresh fish replenishment subareas not yet mapped). Pāku''iku''ī take prohibited through 12/17/26.'),
  ('hi-milolii-cbsfa', 'hawaii_dar', 'conservation_area', 'Miloli''i Community-Based Subsistence Fishing Area', null, null, 'https://dlnr.hawaii.gov/dar/fishing/fishing-regulations/regulated-areas/regulated-fishing-areas-on-hawaii/', '2026-09-02', 'Polygons not yet mapped; the special regs row carries the verbatim walk-through. HAR chapter: Miloli''i CBSFA (DAR).'),
  ('hi-kealakekua-mlcd', 'hawaii_dar', 'conservation_area', 'Kealakekua Bay Marine Life Conservation District (Cook Point to Manini Beach Point)', null, null, 'https://dlnr.hawaii.gov/dar/fishing/fishing-regulations/regulated-areas/regulated-fishing-areas-on-hawaii/', '2026-09-02', 'HAR 13-29 / 13-60.4. Subzone B is the retractable ''allowed fishing'' strip.'),
  ('hi-lapakahi-mlcd', 'hawaii_dar', 'conservation_area', 'Lapakahi Marine Life Conservation District (Koai''e Cove & Subzone B)', null, null, 'https://dlnr.hawaii.gov/dar/fishing/fishing-regulations/regulated-areas/regulated-fishing-areas-on-hawaii/', '2026-09-02', 'HAR 13-33 / 13-60.4. Subzone B hooks-and-thrownet only.'),
  ('hi-oldkona-mlcd', 'hawaii_dar', 'conservation_area', 'Old Kona Airport Marine Life Conservation District', null, null, 'https://dlnr.hawaii.gov/dar/fishing/fishing-regulations/regulated-areas/regulated-fishing-areas-on-hawaii/', '2026-09-02', 'HAR 13-37 / 13-60.4. No Boating Zone inside; mooring 3-hour cap.'),
  ('hi-waialea-mlcd', 'hawaii_dar', 'conservation_area', 'Waialea Bay Marine Life Conservation District (Kānekanaka Point to north of ''Ōhai Point)', null, null, 'https://dlnr.hawaii.gov/dar/fishing/fishing-regulations/regulated-areas/regulated-fishing-areas-on-hawaii/', '2026-09-02', 'HAR 13-35 / 13-60.4. Hook-and-line finfish permitted from pole.')
on conflict (id) do nothing;

insert into public.reg_rule
  (species_id, reg_group_id, reg_area_id, water_class, kind, verbatim, source_url, source_title, source_updated_at, verified_at, pack_version,
   season_start, season_end, bag_daily, possession_limit, min_size_in, max_size_in, size_measure, platform_scope, depth_note, check_inseason, stale_after_days)
values
  (null, null, 'hi-west-hawaii-rfma', 'salt', 'note', 'The West Hawai''i Regional Fishery Management Area (FRA) extends along the west coast of the Island of Hawaii from Ka Lae, Ka''ū (South Point) to ''Ūpolu Point, North Kohala, and from the highwater mark on shore seaward to the limit of the State''s management authority. It includes the Fish Replenishment Areas, Netting Restricted Areas, and Marine Reserve depicted in the accompanying maps and described fully in the administrative rule (available at DAR). Pāku''iku''i: take prohibited in West Hawaii Regional Fishery Management Area through 12/17/26. (HAR 13-60.4)', 'https://dlnr.hawaii.gov/dar/fishing/fishing-regulations/regulated-areas/regulated-fishing-areas-on-hawaii/', 'DLNR Division of Aquatic Resources — Regulated Fishing Areas on Hawai''i Island (HAR 13-29/13-33/13-35/13-37/13-47/13-60.4)', null, '2026-09-02', 2,
   null, null, null, null, null, null, null, null, null, false, 180),
  (null, null, 'hi-milolii-cbsfa', 'salt', 'note', 'Miloli''i Community-Based Subsistence Fishing Area — From July through February the bag limit for kole is 20 per person per day, and minimum size is five inches. From June through February the minimum size for these species is 14 inches and maximum size is 20 inches, and the bag limit is one fish per person per day. [Uhu:] To take or possess more than three other uhu per person per day; only one may be a terminal-phase uhu. [''Ula:] To take or possess more than two ula per person per day. [''Opihi:] To take or possess more ''opihi makaiauli and ''opihi ''ālinalina (with shell) than can fit in a one-gallon size bag per person per day. Pāku''iku''i: take prohibited before July 1, 2027; beginning July 1, 2027 pāku''iku''i bag limit is five per person per day, and minimum size is five inches. [''Ū''ū:] To take or possess any ''ū''ū from April through June. (DLNR regulated areas, Miloli''i CBSFA row.)', 'https://dlnr.hawaii.gov/dar/fishing/fishing-regulations/regulated-areas/regulated-fishing-areas-on-hawaii/', 'DLNR Division of Aquatic Resources — Regulated Fishing Areas on Hawai''i Island (HAR 13-29/13-33/13-35/13-37/13-47/13-60.4)', null, '2026-09-02', 2,
   null, null, null, null, null, null, null, null, null, false, 90),
  (null, null, 'hi-kealakekua-mlcd', 'salt', 'note', 'Kealakekua Bay MLCD — The Kealakekua Bay Marine Life Conservation District is located offshore of the Kealakekua Bay Historical State Park on the western coast of the island of Hawai''i, from the highwater mark seaward to a line from Cook Point to Manini Beach Point. Permitted within Subzone B only: to fish for, take or possess any finfish with or by the use of hook-and-line and thrownet, provided that any legal fishing device or method except traps may be used for the taking of akule, ''ōpelu and crustaceans. Prohibited: to fish for, take or injure marine life (including eggs), except as indicated in ''Permitted'' activities above. (HAR 13-29, HAR 13-60.4)', 'https://dlnr.hawaii.gov/dar/fishing/fishing-regulations/regulated-areas/regulated-fishing-areas-on-hawaii/', 'DLNR Division of Aquatic Resources — Regulated Fishing Areas on Hawai''i Island (HAR 13-29/13-33/13-35/13-37/13-47/13-60.4)', null, '2026-09-02', 2,
   null, null, null, null, null, null, null, null, null, false, 180),
  (null, null, 'hi-lapakahi-mlcd', 'salt', 'note', 'Lapakahi MLCD — encompasses Subzone A (Koai''e Cove) and Subzone B, extending approximately 500 feet offshore of the Lapakahi State Historical Park. Permitted within Subzone B only: to fish for, take or possess any ''ōpelu by lift or ''ōpelu net, or any finfish or crustacean by hook-and-line or thrownet. Prohibited: to fish for, take or injure any marine life (including eggs), or possess in the water any device that may be used for the taking of marine life. (HAR 13-33, HAR 13-60.4)', 'https://dlnr.hawaii.gov/dar/fishing/fishing-regulations/regulated-areas/regulated-fishing-areas-on-hawaii/', 'DLNR Division of Aquatic Resources — Regulated Fishing Areas on Hawai''i Island (HAR 13-29/13-33/13-35/13-37/13-47/13-60.4)', null, '2026-09-02', 2,
   null, null, null, null, null, null, null, null, null, false, 180),
  (null, null, 'hi-oldkona-mlcd', 'salt', 'note', 'Old Kona Airport MLCD — Permitted: to fish for, take, possess or remove akule by handline at night, and ''ōpelu by lift or ''ōpelu net method; to fish for, take, possess or remove any finfish for home consumption by throw net or pole-and-line (without reel) with bait from shore. Prohibited except as permitted: to fish for, take, injure, kill, possess or remove any marine life, including live sea shell and ''opihi, live coral, algae or limu. No anchoring; a No Boating Zone applies. (HAR 13-37, HAR 13-60.4)', 'https://dlnr.hawaii.gov/dar/fishing/fishing-regulations/regulated-areas/regulated-fishing-areas-on-hawaii/', 'DLNR Division of Aquatic Resources — Regulated Fishing Areas on Hawai''i Island (HAR 13-29/13-33/13-35/13-37/13-47/13-60.4)', null, '2026-09-02', 2,
   null, null, null, null, null, null, null, null, null, false, 180),
  (null, null, 'hi-waialea-mlcd', 'salt', 'note', 'Waialea Bay MLCD — located offshore of Waialea Bay along the northwestern coast of the island of Hawai''i, from the highwater mark seaward to a line from Kānekanaka Point to the point immediately north of ''Ōhai Point. Permitted: to have or possess any fishing pole and hook-and-line, and to fish for, take or possess any finfish using such gear. Prohibited: to fish for, take or injure any marine life (including eggs), or possess in the water any device that may be used for the taking of marine life, except as indicated in permitted activities above. (HAR 13-35, HAR 13-60.4)', 'https://dlnr.hawaii.gov/dar/fishing/fishing-regulations/regulated-areas/regulated-fishing-areas-on-hawaii/', 'DLNR Division of Aquatic Resources — Regulated Fishing Areas on Hawai''i Island (HAR 13-29/13-33/13-35/13-37/13-47/13-60.4)', null, '2026-09-02', 2,
   null, null, null, null, null, null, null, null, null, false, 180);

insert into public.reg_pack (id, version, published_at, notes) values
  ('hawaii-2026-09-02', 2, '2026-09-02T18:00:00Z', 'Hawaii (DLNR DAR statewide table): moi 11 in @ 15 closed Jun–Aug; ''ama''ama 11 in closed Dec–Mar; ''o''io 14 in; ulua/papio 10 in @ 20 non-commercial; uhu 10 in @ 2 (large uhu 14 in, no take on Maui for two); weke ''oama 7 in / 50 ''oama; kala 14 in @ 4; kole 5 in; manini 6 in; Deep 7 combined bag 5 non-commercial; Maui rules under HAR 13-95.1; sharks and rays protected in state waters (HRS 188). No recreational saltwater license required.')
on conflict (id) do update set version = excluded.version, notes = excluded.notes;
