-- Virginia v2 (2026-09-03): VMRC recreational marine table digest + Bay striper
-- seasons. GENERATED via gen-va-digest-v2.mts. Insert-only + pack upsert to version 2.

insert into public.reg_area (id, authority, kind, name, parent_id, boundary_geojson, source_url, verified_at, notes) values
  ('va-coast', 'va-mrc', 'ocean_region', 'Virginia — coastal / territorial sea (seaside Accomack, Northampton, Virginia Beach)', null, '[[-76.4,38.05],[-75.4,36.55],[-75.3,36.55],[-75.9,38.05],[-76.4,38.05]]', 'https://webapps.mrc.virginia.gov/public/reports/swrecfishingrules.php', '2026-09-03', 'Coastal striper map: Territorial Sea plus seaside creeks; EEZ closed to stripers. Potomac is PRFC, not this pack.'),
  ('va-chesapeake', 'va-mrc', 'ocean_region', 'Virginia — Chesapeake Bay and Bay tributaries (not Potomac)', null, null, 'https://webapps.mrc.virginia.gov/public/reports/swrecfishingrules.php', '2026-09-03', 'Potomac mainstem and its VA tributaries follow PRFC, not VMRC Bay seasons.')
on conflict (id) do update set name = excluded.name, notes = excluded.notes, source_url = excluded.source_url;

insert into public.reg_rule
  (species_id, reg_group_id, reg_area_id, water_class, kind, verbatim, source_url, source_title, source_updated_at, verified_at, pack_version,
   season_start, season_end, bag_daily, possession_limit, min_size_in, max_size_in, size_measure, platform_scope, depth_note, check_inseason, stale_after_days)
values
  ('striped_bass', null, 'va-coast', 'salt', 'bag_limit', 'Virginia Coastal Seasons: January 1 through March 31. May 16 through December 31. Minimum Size Limit: 28 inches. Maximum Size Limit: 31 inches. Possession Limit: 1 per person.', 'https://webapps.mrc.virginia.gov/public/reports/swrecfishingrules.php', 'Virginia MRC — Recreational Fishing Regulations For Marine Waters', '2026-05-01', '2026-09-03', 2,
   '2026-05-16', '2026-12-31', 1, 1, 28, 31, 'total_length', null, 'Also open Jan 1–Mar 31.', true, 30),
  ('striped_bass', null, 'va-coast', 'salt', 'season', 'The open seasons for the coastal area striped bass recreational fishery shall be January 1 through March 31 and May 16 through December 31, inclusive.', 'https://www.mrc.virginia.gov/Notices/2024/2024-03-26-RC252-draft.pdf', 'Virginia MRC — 4VAC 20-252 coastal area striped bass recreational fishery', '2024-03-26', '2026-09-03', 2,
   '2026-01-01', '2026-03-31', 1, 1, 28, 31, 'total_length', null, null, true, 30),
  ('striped_bass', null, 'va-coast', 'salt', 'gear', 'As required by 4 VAC 20-252-50 (B), beginning August 1, 2020, any person fishing striped bass recreationally shall use non-offset, corrodible, non-stainless steel circle hooks when fishing with bait, live or chunk. Gaffing striped bass or attempting to gaff striped bass is illegal in Virginia marine waters. Atlantic Ocean waters beyond the 3 mile limit are closed to the taking and possession of striped bass all year.', 'https://webapps.mrc.virginia.gov/public/reports/swrecfishingrules.php', 'Virginia MRC — Recreational Fishing Regulations For Marine Waters', '2026-05-01', '2026-09-03', 2,
   null, null, null, null, null, null, null, null, null, true, 60),
  ('striped_bass', null, 'va-chesapeake', 'salt', 'bag_limit', 'Chesapeake Bay Spring Season. Season: May 16 through June 15. Minimum Size Limit: 19 inches. Maximum Size Limit: 24 inches. Possession Limit: 1 per person.', 'https://webapps.mrc.virginia.gov/public/reports/swrecfishingrules.php', 'Virginia MRC — Recreational Fishing Regulations For Marine Waters', '2026-05-01', '2026-09-03', 2,
   '2026-05-16', '2026-06-15', 1, 1, 19, 24, 'total_length', null, null, true, 14),
  ('striped_bass', null, 'va-chesapeake', 'salt', 'bag_limit', 'Chesapeake Bay Fall Season. Season: October 4 through December 31. Minimum Size Limit: 19 inches. Maximum Size Limit: 24 inches. Possession Limit: 1 per person.', 'https://webapps.mrc.virginia.gov/public/reports/swrecfishingrules.php', 'Virginia MRC — Recreational Fishing Regulations For Marine Waters', '2026-05-01', '2026-09-03', 2,
   '2026-10-04', '2026-12-31', 1, 1, 19, 24, 'total_length', null, null, true, 14),
  ('striped_bass', null, 'va-chesapeake', 'salt', 'season', 'Chesapeake Bay Spring Season: May 16 through June 15.', 'https://webapps.mrc.virginia.gov/public/reports/swrecfishingrules.php', 'Virginia MRC — Recreational Fishing Regulations For Marine Waters', '2026-05-01', '2026-09-03', 2,
   '2026-05-16', '2026-06-15', null, null, null, null, null, null, null, true, 14),
  ('striped_bass', null, 'va-chesapeake', 'salt', 'season', 'Chesapeake Bay Fall Season: October 4 through December 31.', 'https://webapps.mrc.virginia.gov/public/reports/swrecfishingrules.php', 'Virginia MRC — Recreational Fishing Regulations For Marine Waters', '2026-05-01', '2026-09-03', 2,
   '2026-10-04', '2026-12-31', null, null, null, null, null, null, null, true, 14),
  ('black_sea_bass', null, 'va-coast', 'salt', 'bag_limit', 'Black Sea Bass. Minimum Size Limit: 13. Possession Limit: 15. Season: May 11 through Dec 31. Regulations for black sea bass caught in federal waters are subject to change. Please refer to NMFS for regulations in federal waters.', 'https://webapps.mrc.virginia.gov/public/reports/swrecfishingrules.php', 'Virginia MRC — Recreational Fishing Regulations For Marine Waters', '2026-05-01', '2026-09-03', 2,
   '2026-05-11', '2026-12-31', 15, 15, 13, null, 'total_length', null, null, true, 30),
  ('black_sea_bass', null, 'va-coast', 'salt', 'season', 'A. It shall be unlawful for any person fishing with hook-and-line, rod and reel, spear, gig, or other recreational gear to possess more than 15 black sea bass. C. In 2026, the open recreational fishing season shall be from May 11 through December 31.', 'https://law.lis.virginia.gov/admincode/title4/agency20/chapter950/section45/', '4VAC20-950-45. Recreational possession limits and seasons (black sea bass)', '2026-01-01', '2026-09-03', 2,
   '2026-05-11', '2026-12-31', null, null, null, null, null, null, null, true, 30),
  ('tautog', null, 'va-coast', 'salt', 'bag_limit', 'Tautog. Minimum Size Limit: 16 IN. Possession Limit: 4 per person. Season: Closed Season: May 16 - June 30.', 'https://webapps.mrc.virginia.gov/public/reports/swrecfishingrules.php', 'Virginia MRC — Recreational Fishing Regulations For Marine Waters', '2026-05-01', '2026-09-03', 2,
   '2026-07-01', '2026-12-31', 4, 4, 16, null, 'total_length', null, null, true, 30),
  ('tautog', null, 'va-coast', 'salt', 'bag_limit', 'The recreational fishing season shall be closed from May 16 through June 30. The minimum size of tautog harvested for recreational purposes shall be 16 inches in total length. It shall be unlawful for any person fishing with hook and line, rod and reel, spear, gig or other recreational gear to possess more than four tautog.', 'https://mrc.virginia.gov/regulations/FR960.shtm', '4VAC20-960 — Pertaining to Tautog', '2024-02-01', '2026-09-03', 2,
   '2026-01-01', '2026-05-15', 4, 4, 16, null, 'total_length', null, null, true, 30),
  ('tautog', null, 'va-coast', 'salt', 'season', 'Tautog recreational season closed May 16 through June 30 (open otherwise).', 'https://webapps.mrc.virginia.gov/public/reports/swrecfishingrules.php', 'Virginia MRC — Recreational Fishing Regulations For Marine Waters', '2026-05-01', '2026-09-03', 2,
   '2026-07-01', '2026-12-31', null, null, null, null, null, null, null, true, 30),
  ('tautog', null, 'va-coast', 'salt', 'season', 'Tautog recreational open January 1 through May 15.', 'https://mrc.virginia.gov/regulations/FR960.shtm', '4VAC20-960 — Pertaining to Tautog', '2024-02-01', '2026-09-03', 2,
   '2026-01-01', '2026-05-15', null, null, null, null, null, null, null, true, 30),
  ('summer_flounder', null, 'va-coast', 'salt', 'bag_limit', 'Summer Flounder. Minimum Size Limit January 1-May 31: 16 Inches. Minimum Size Limit June 1-December 31: 17.5 Inches. Possession Limit: 4 per person. Season: Open year-round.', 'https://webapps.mrc.virginia.gov/public/reports/swrecfishingrules.php', 'Virginia MRC — Recreational Fishing Regulations For Marine Waters', '2026-05-01', '2026-09-03', 2,
   '2026-06-01', '2026-12-31', 4, 4, 17.5, null, 'total_length', null, 'Potomac tributaries follow PRFC.', true, 30),
  ('summer_flounder', null, 'va-coast', 'salt', 'bag_limit', 'Summer Flounder. Minimum Size Limit January 1-May 31: 16 Inches. Possession Limit: 4 per person. Season: Open year-round.', 'https://webapps.mrc.virginia.gov/public/reports/swrecfishingrules.php', 'Virginia MRC — Recreational Fishing Regulations For Marine Waters', '2026-05-01', '2026-09-03', 2,
   '2026-01-01', '2026-05-31', 4, 4, 16, null, 'total_length', null, null, true, 30),
  ('cobia', null, 'va-coast', 'salt', 'bag_limit', 'Recreational cobia regulations are as follows: 43-inch, total length, minimum size limit; 1-fish daily possession limit or 2-fish-daily vessel limit, whichever is more restrictive; an open season of June 15 through September 20; and gaffing is prohibited.', 'https://webapps.mrc.virginia.gov/public/reports/swrecfishingrules.php', 'Virginia MRC — Recreational Fishing Regulations For Marine Waters', '2026-05-01', '2026-09-03', 2,
   '2026-06-15', '2026-09-20', 1, 1, 43, null, 'total_length', null, '2 per vessel, whichever is more restrictive.', true, 30),
  ('cobia', null, 'va-coast', 'salt', 'season', 'Cobia. Minimum Size Limit: 43 inches total length. Possession Limit: 1 per person, 2 per vessel; whichever is more restrictive. Season: June 15 through Sept 20.', 'https://webapps.mrc.virginia.gov/public/reports/swrecfishingrules.php', 'Virginia MRC — Recreational Fishing Regulations For Marine Waters', '2026-05-01', '2026-09-03', 2,
   '2026-06-15', '2026-09-20', null, null, null, null, null, null, null, true, 30),
  ('red_drum', null, 'va-coast', 'salt', 'bag_limit', 'Red Drum (Channel Bass, Redfish). Minimum Size Limit: Min 18 IN. to Max 26 IN. Possession Limit: 3 per person.', 'https://webapps.mrc.virginia.gov/public/reports/swrecfishingrules.php', 'Virginia MRC — Recreational Fishing Regulations For Marine Waters', '2026-05-01', '2026-09-03', 2,
   null, null, 3, 3, 18, 26, 'total_length', null, null, true, 60),
  ('spotted_seatrout', null, 'va-coast', 'salt', 'bag_limit', 'Speckled Trout (Spotted Seatrout). Minimum Size Limit: 14 IN. Possession Limit: 5 per Person, only 1 greater than 24". Season: *Closed April 1 - June 30, 2026.', 'https://webapps.mrc.virginia.gov/public/reports/swrecfishingrules.php', 'Virginia MRC — Recreational Fishing Regulations For Marine Waters', '2026-05-01', '2026-09-03', 2,
   '2026-07-01', '2026-03-31', 5, 5, 14, null, 'total_length', null, 'One fish may exceed 24". Closed Apr 1–Jun 30 2026.', true, 14),
  ('spotted_seatrout', null, 'va-chesapeake', 'salt', 'season', 'Speckled trout recreational harvest closed April 1 through June 30, 2026 (VMRC table).', 'https://webapps.mrc.virginia.gov/public/reports/swrecfishingrules.php', 'Virginia MRC — Recreational Fishing Regulations For Marine Waters', '2026-05-01', '2026-09-03', 2,
   '2026-07-01', '2026-03-31', null, null, null, null, null, null, null, true, 14),
  ('spotted_seatrout', null, 'va-coast', 'salt', 'season', 'Speckled trout open outside April 1–June 30 2026 in Virginia marine waters.', 'https://webapps.mrc.virginia.gov/public/reports/swrecfishingrules.php', 'Virginia MRC — Recreational Fishing Regulations For Marine Waters', '2026-05-01', '2026-09-03', 2,
   '2026-07-01', '2026-03-31', null, null, null, null, null, null, null, true, 14),
  ('spotted_seatrout', null, 'va-chesapeake', 'salt', 'bag_limit', 'Speckled Trout (Spotted Seatrout) — Bay: Minimum Size Limit: 14 IN. Possession Limit: 5 per Person, only 1 greater than 24". Season: *Closed April 1 - June 30, 2026.', 'https://webapps.mrc.virginia.gov/public/reports/swrecfishingrules.php', 'Virginia MRC — Recreational Fishing Regulations For Marine Waters', '2026-05-01', '2026-09-03', 2,
   '2026-07-01', '2026-03-31', 5, 5, 14, null, 'total_length', null, 'One fish may exceed 24".', true, 14),
  ('black_drum', null, 'va-coast', 'salt', 'bag_limit', 'Black Drum (Drum, Drumfish). Minimum Size Limit: 16 IN. Possession Limit: 1 per person.', 'https://webapps.mrc.virginia.gov/public/reports/swrecfishingrules.php', 'Virginia MRC — Recreational Fishing Regulations For Marine Waters', '2026-05-01', '2026-09-03', 2,
   null, null, 1, 1, 16, null, 'total_length', null, null, true, 60),
  ('bluefish', null, 'va-coast', 'salt', 'bag_limit', 'Bluefish. Minimum Size Limit: None. Possession Limit: 5 per person from shore or a rented or private vessel; 5 per person on for-hire or charter vessels.', 'https://webapps.mrc.virginia.gov/public/reports/swrecfishingrules.php', 'Virginia MRC — Recreational Fishing Regulations For Marine Waters', '2026-05-01', '2026-09-03', 2,
   null, null, 5, 5, null, null, null, null, null, true, 60),
  ('weakfish', null, 'va-coast', 'salt', 'bag_limit', 'Grey Trout (Weakfish). Minimum Size Limit: 12 IN. Possession Limit: 1 per person.', 'https://webapps.mrc.virginia.gov/public/reports/swrecfishingrules.php', 'Virginia MRC — Recreational Fishing Regulations For Marine Waters', '2026-05-01', '2026-09-03', 2,
   null, null, 1, 1, 12, null, 'total_length', null, null, true, 60),
  ('sheepshead', null, 'va-coast', 'salt', 'bag_limit', 'Sheepshead. Minimum Size Limit: None. Possession Limit: 4 per person.', 'https://webapps.mrc.virginia.gov/public/reports/swrecfishingrules.php', 'Virginia MRC — Recreational Fishing Regulations For Marine Waters', '2026-05-01', '2026-09-03', 2,
   null, null, 4, 4, null, null, null, null, null, true, 60),
  ('spanish_mackerel', null, 'va-coast', 'salt', 'bag_limit', 'Spanish Mackerel. Minimum Size Limit: 14 IN. Possession Limit: 15 per person.', 'https://webapps.mrc.virginia.gov/public/reports/swrecfishingrules.php', 'Virginia MRC — Recreational Fishing Regulations For Marine Waters', '2026-05-01', '2026-09-03', 2,
   null, null, 15, 15, 14, null, 'total_length', null, null, true, 60),
  ('king_mackerel', null, 'va-coast', 'salt', 'bag_limit', 'King Mackerel. Minimum Size Limit: 27 IN. Possession Limit: 3 per person.', 'https://webapps.mrc.virginia.gov/public/reports/swrecfishingrules.php', 'Virginia MRC — Recreational Fishing Regulations For Marine Waters', '2026-05-01', '2026-09-03', 2,
   null, null, 3, 3, 27, null, 'total_length', null, null, true, 60),
  ('greater_amberjack', null, 'va-coast', 'salt', 'bag_limit', 'Amberjack. Minimum Size Limit: 32 IN. Possession Limit: 2 per person.', 'https://webapps.mrc.virginia.gov/public/reports/swrecfishingrules.php', 'Virginia MRC — Recreational Fishing Regulations For Marine Waters', '2026-05-01', '2026-09-03', 2,
   null, null, 2, 2, 32, null, 'total_length', null, null, true, 60),
  ('scup', null, 'va-coast', 'salt', 'bag_limit', 'Scup (Porgy). Minimum Size Limit: 9 IN. Possession Limit: 30 per person. Below regulations apply in state waters.', 'https://webapps.mrc.virginia.gov/public/reports/swrecfishingrules.php', 'Virginia MRC — Recreational Fishing Regulations For Marine Waters', '2026-05-01', '2026-09-03', 2,
   null, null, 30, 30, 9, null, 'total_length', null, 'Federal waters: check NMFS.', true, 60);

insert into public.reg_pack (id, version, published_at, notes) values
  ('virginia-2026-09-03', 2, '2026-09-03T23:30:00Z', 'Virginia MRC recreational table v2: coastal stripers 28–31" @1 (Jan 1–Mar 31 and May 16–Dec 31); Bay stripers 19–24" @1 May 16–Jun 15 and Oct 4–Dec 31; BSB 13" @15 May 11–Dec 31; tautog 16" @4 closed May 16–Jun 30; fluke 16" then 17.5" @4; cobia 43" @1 / 2 vessel Jun 15–Sep 20; red drum 18–26" @3; specks 14" @5 (1 over 24") closed Apr 1–Jun 30 2026.')
on conflict (id) do update set version = excluded.version, notes = excluded.notes, published_at = excluded.published_at;
