-- Washington v3 (2026-09-02): Puget Sound pamphlet tables — Marine Areas 9, 10, 13
-- (WDFW 2026-27 Sport Fishing Rules). GENERATED via gen-wa-sound-v3.mts.
-- Insert-only + pack upsert to version 3.

insert into public.reg_area (id, authority, kind, name, parent_id, boundary_geojson, source_url, verified_at, notes) values
  ('wa-ma-9', 'wdfw', 'ocean_region', 'Marine Area 9 — Admiralty Inlet', null, '[[-122.75,48.05],[-122.4,47.95],[-122.35,48],[-122.35,48.3],[-122.75,48.3],[-122.75,48.05]]', 'https://www.eregulations.com/washington/fishing/marine-area-9', '2026-09-02', 'Envelope. Legal: south of Partridge Point–Point Wilson line, south and west of Possession Point 110° true to shipwreck, north of Hood Canal Bridge and north of the Apple Cove Point–Edwards Point line.'),
  ('wa-ma-10', 'wdfw', 'ocean_region', 'Marine Area 10 — Seattle / Bremerton', null, '[[-122.5,47.55],[-122.3,47.55],[-122.3,47.95],[-122.5,47.95],[-122.5,47.55]]', 'https://www.eregulations.com/washington/fishing/marine-area-10', '2026-09-02', 'Envelope. Legal: Apple Cove Point–Edwards Point to a true east-west line through the north tip of Vashon Island. DOH fish-consumption advisories apply — check doh.wa.gov/fishmap.'),
  ('wa-ma-13', 'wdfw', 'ocean_region', 'Marine Area 13 — South Puget Sound', null, '[[-122.65,47.1],[-122.35,47.1],[-122.3,47.28],[-122.65,47.28]]', 'https://www.eregulations.com/washington/fishing/marine-area-13', '2026-09-02', 'Envelope. Legal: all waters south of the northernmost Tacoma Narrows Bridge. Halibut closed; Toliva Shoal + Budd Inlet sub-areas have their own salmon rows in the pamphlet (headline rows shipped as notes).')
on conflict (id) do nothing;

insert into public.reg_rule
  (species_id, reg_group_id, reg_area_id, water_class, kind, verbatim, source_url, source_title, source_updated_at, verified_at, pack_version,
   season_start, season_end, bag_daily, possession_limit, min_size_in, max_size_in, size_measure, platform_scope, depth_note, check_inseason, stale_after_days)
values
  (null, 'wa-bottomfish', 'wa-ma-9', 'salt', 'bag_limit', 'Bottomfish: Year-round season. Daily limit is a total of 15 bottomfish subject to individual limits and seasons shown below. Fishing for bottomfish prohibited in waters deeper than 120 feet. Descending device required onboard vessels.', 'https://www.eregulations.com/washington/fishing/ma-9', 'WDFW — 2026-2027 Washington Sport Fishing Rules (Marine Area ma-9)', '2026-06-18', '2026-09-02', 3,
   null, null, 15, null, null, null, null, null, 'No bottomfish deeper than 120 ft.', true, 30),
  ('lingcod', null, 'wa-ma-9', 'salt', 'bag_limit', 'Lingcod — May 1-June 15: Hook and line season. Min. size 26 in. Max. size 36 in. Daily limit 1. May 21-June 15: Spearfishing season. Max. size 36 in. Daily limit 1.', 'https://www.eregulations.com/washington/fishing/ma-9', 'WDFW — 2026-2027 Washington Sport Fishing Rules (Marine Area ma-9)', '2026-06-18', '2026-09-02', 3,
   '2026-05-01', '2026-06-15', 1, null, 26, 36, 'total_length', 'boat', 'Spear window opens May 21 (26-36 in slot; max 36).', true, 30),
  ('lingcod', null, 'wa-ma-9', 'salt', 'season', 'Lingcod — May 1-June 15: Hook and line season, May 21-June 15 spearfishing (outside those pamphlet windows lingcod retention is closed in this Marine Area).', 'https://www.eregulations.com/washington/fishing/ma-9', 'WDFW — 2026-2027 Washington Sport Fishing Rules (Marine Area ma-9)', '2026-06-18', '2026-09-02', 3,
   '2026-01-01', '2026-04-30', 0, null, null, null, null, null, null, true, 30),
  ('lingcod', null, 'wa-ma-9', 'salt', 'season', 'Lingcod — May 1-June 15: Hook and line season, May 21-June 15 spearfishing (outside these windows lingcod retention is closed in this Marine Area — see the pamphlet table).', 'https://www.eregulations.com/washington/fishing/ma-9', 'WDFW — 2026-2027 Washington Sport Fishing Rules (Marine Area ma-9)', '2026-06-18', '2026-09-02', 3,
   '2026-06-16', '2026-12-31', 0, null, null, null, null, null, null, true, 30),
  ('surfperch', null, 'wa-ma-9', 'salt', 'bag_limit', 'Surfperch: Year-round. No min. size. Daily limit 10. Except shiner perch daily limit 15: not included in bottomfish limit.', 'https://www.eregulations.com/washington/fishing/ma-9', 'WDFW — 2026-2027 Washington Sport Fishing Rules (Marine Area ma-9)', '2026-06-18', '2026-09-02', 3,
   null, null, 10, null, null, null, null, null, 'Shiner perch 15/day, not in the bottomfish count.', true, 60),
  ('rockfish', null, 'wa-ma-9', 'salt', 'prohibited', 'Rockfish: CLOSED — CLOSED to fishing for, retaining, or possessing.', 'https://www.eregulations.com/washington/fishing/ma-9', 'WDFW — 2026-2027 Washington Sport Fishing Rules (Marine Area ma-9)', '2026-06-18', '2026-09-02', 3,
   null, null, 0, 0, null, null, null, null, null, false, 120),
  ('pacific_cod', null, 'wa-ma-9', 'salt', 'prohibited', 'Pacific Cod, Pollock, Hake, and Wolf-Eel: Year-round — CLOSED to retention.', 'https://www.eregulations.com/washington/fishing/ma-9', 'WDFW — 2026-2027 Washington Sport Fishing Rules (Marine Area ma-9)', '2026-06-18', '2026-09-02', 3,
   null, null, 0, 0, null, null, null, null, 'Also covers pollock, hake, wolf-eel.', false, 120),
  ('sixgill_shark', null, 'wa-ma-9', 'salt', 'prohibited', 'Sixgill, Sevengill, and Thresher Sharks: CLOSED — CLOSED to fishing for, retaining, or possessing. Sixgill shark may not be removed from the water.', 'https://www.eregulations.com/washington/fishing/ma-9', 'WDFW — 2026-2027 Washington Sport Fishing Rules (Marine Area ma-9)', '2026-06-18', '2026-09-02', 3,
   null, null, 0, 0, null, null, null, null, null, true, 60),
  ('cabezon', null, 'wa-ma-9', 'salt', 'bag_limit', 'Cabezon: May 1-Nov. 30 — Min. size 18 in. Daily limit 1.', 'https://www.eregulations.com/washington/fishing/ma-9', 'WDFW — 2026-2027 Washington Sport Fishing Rules (Marine Area ma-9)', '2026-06-18', '2026-09-02', 3,
   '2026-05-01', '2026-11-30', 1, null, 18, null, 'total_length', null, null, true, 30),
  (null, 'wa-bottomfish', 'wa-ma-10', 'salt', 'bag_limit', 'Bottomfish: Year-round season. Daily limit is a total of 15 bottomfish subject to individual limits and seasons shown below. Fishing for bottomfish prohibited in waters deeper than 120 feet. Descending device required onboard vessels.', 'https://www.eregulations.com/washington/fishing/ma-10', 'WDFW — 2026-2027 Washington Sport Fishing Rules (Marine Area ma-10)', '2026-06-18', '2026-09-02', 3,
   null, null, 15, null, null, null, null, null, 'No bottomfish deeper than 120 ft.', true, 30),
  ('lingcod', null, 'wa-ma-10', 'salt', 'bag_limit', 'Lingcod — May 1-June 15: Hook and line season. Min. size 26 in. Max. size 36 in. Daily limit 1. May 21-June 15: Spearfishing season. Max. size 36 in. Daily limit 1.', 'https://www.eregulations.com/washington/fishing/ma-10', 'WDFW — 2026-2027 Washington Sport Fishing Rules (Marine Area ma-10)', '2026-06-18', '2026-09-02', 3,
   '2026-05-01', '2026-06-15', 1, null, 26, 36, 'total_length', 'boat', 'Spear window opens May 21 (26-36 in slot; max 36).', true, 30),
  ('lingcod', null, 'wa-ma-10', 'salt', 'season', 'Lingcod — May 1-June 15: Hook and line season, May 21-June 15 spearfishing (outside those pamphlet windows lingcod retention is closed in this Marine Area).', 'https://www.eregulations.com/washington/fishing/ma-10', 'WDFW — 2026-2027 Washington Sport Fishing Rules (Marine Area ma-10)', '2026-06-18', '2026-09-02', 3,
   '2026-01-01', '2026-04-30', 0, null, null, null, null, null, null, true, 30),
  ('lingcod', null, 'wa-ma-10', 'salt', 'season', 'Lingcod — May 1-June 15: Hook and line season, May 21-June 15 spearfishing (outside these windows lingcod retention is closed in this Marine Area — see the pamphlet table).', 'https://www.eregulations.com/washington/fishing/ma-10', 'WDFW — 2026-2027 Washington Sport Fishing Rules (Marine Area ma-10)', '2026-06-18', '2026-09-02', 3,
   '2026-06-16', '2026-12-31', 0, null, null, null, null, null, null, true, 30),
  ('surfperch', null, 'wa-ma-10', 'salt', 'bag_limit', 'Surfperch: Year-round. No min. size. Daily limit 10. Except shiner perch daily limit 15: not included in bottomfish limit.', 'https://www.eregulations.com/washington/fishing/ma-10', 'WDFW — 2026-2027 Washington Sport Fishing Rules (Marine Area ma-10)', '2026-06-18', '2026-09-02', 3,
   null, null, 10, null, null, null, null, null, 'Shiner perch 15/day, not in the bottomfish count.', true, 60),
  ('rockfish', null, 'wa-ma-10', 'salt', 'prohibited', 'Rockfish: CLOSED — CLOSED to fishing for, retaining, or possessing.', 'https://www.eregulations.com/washington/fishing/ma-10', 'WDFW — 2026-2027 Washington Sport Fishing Rules (Marine Area ma-10)', '2026-06-18', '2026-09-02', 3,
   null, null, 0, 0, null, null, null, null, null, false, 120),
  ('pacific_cod', null, 'wa-ma-10', 'salt', 'prohibited', 'Pacific Cod, Pollock, Hake, and Wolf-Eel: Year-round — CLOSED to retention.', 'https://www.eregulations.com/washington/fishing/ma-10', 'WDFW — 2026-2027 Washington Sport Fishing Rules (Marine Area ma-10)', '2026-06-18', '2026-09-02', 3,
   null, null, 0, 0, null, null, null, null, 'Also covers pollock, hake, wolf-eel.', false, 120),
  ('sixgill_shark', null, 'wa-ma-10', 'salt', 'prohibited', 'Sixgill, Sevengill, and Thresher Sharks: CLOSED — CLOSED to fishing for, retaining, or possessing. Sixgill shark may not be removed from the water.', 'https://www.eregulations.com/washington/fishing/ma-10', 'WDFW — 2026-2027 Washington Sport Fishing Rules (Marine Area ma-10)', '2026-06-18', '2026-09-02', 3,
   null, null, 0, 0, null, null, null, null, null, true, 60),
  ('cabezon', null, 'wa-ma-10', 'salt', 'bag_limit', 'Cabezon: May 1-Nov. 30 — Min. size 18 in. Daily limit 1.', 'https://www.eregulations.com/washington/fishing/ma-10', 'WDFW — 2026-2027 Washington Sport Fishing Rules (Marine Area ma-10)', '2026-06-18', '2026-09-02', 3,
   '2026-05-01', '2026-11-30', 1, null, 18, null, 'total_length', null, null, true, 30),
  (null, 'wa-bottomfish', 'wa-ma-13', 'salt', 'bag_limit', 'Bottomfish: Year-round season. Daily limit is a total of 15 bottomfish subject to individual limits and seasons shown below. Fishing for bottomfish prohibited in waters deeper than 120 feet. Descending device required onboard vessels.', 'https://www.eregulations.com/washington/fishing/ma-13', 'WDFW — 2026-2027 Washington Sport Fishing Rules (Marine Area ma-13)', '2026-06-18', '2026-09-02', 3,
   null, null, 15, null, null, null, null, null, 'No bottomfish deeper than 120 ft.', true, 30),
  ('lingcod', null, 'wa-ma-13', 'salt', 'bag_limit', 'Lingcod — May 1-June 15: Hook and line season. Min. size 26 in. Max. size 36 in. Daily limit 1. May 21-June 15: Spearfishing season. Max. size 36 in. Daily limit 1.', 'https://www.eregulations.com/washington/fishing/ma-13', 'WDFW — 2026-2027 Washington Sport Fishing Rules (Marine Area ma-13)', '2026-06-18', '2026-09-02', 3,
   '2026-05-01', '2026-06-15', 1, null, 26, 36, 'total_length', 'boat', 'Spear window opens May 21 (26-36 in slot; max 36).', true, 30),
  ('lingcod', null, 'wa-ma-13', 'salt', 'season', 'Lingcod — May 1-June 15: Hook and line season, May 21-June 15 spearfishing (outside those pamphlet windows lingcod retention is closed in this Marine Area).', 'https://www.eregulations.com/washington/fishing/ma-13', 'WDFW — 2026-2027 Washington Sport Fishing Rules (Marine Area ma-13)', '2026-06-18', '2026-09-02', 3,
   '2026-01-01', '2026-04-30', 0, null, null, null, null, null, null, true, 30),
  ('lingcod', null, 'wa-ma-13', 'salt', 'season', 'Lingcod — May 1-June 15: Hook and line season, May 21-June 15 spearfishing (outside these windows lingcod retention is closed in this Marine Area — see the pamphlet table).', 'https://www.eregulations.com/washington/fishing/ma-13', 'WDFW — 2026-2027 Washington Sport Fishing Rules (Marine Area ma-13)', '2026-06-18', '2026-09-02', 3,
   '2026-06-16', '2026-12-31', 0, null, null, null, null, null, null, true, 30),
  ('surfperch', null, 'wa-ma-13', 'salt', 'bag_limit', 'Surfperch: Year-round. No min. size. Daily limit 10. Except shiner perch daily limit 15: not included in bottomfish limit.', 'https://www.eregulations.com/washington/fishing/ma-13', 'WDFW — 2026-2027 Washington Sport Fishing Rules (Marine Area ma-13)', '2026-06-18', '2026-09-02', 3,
   null, null, 10, null, null, null, null, null, 'Shiner perch 15/day, not in the bottomfish count.', true, 60),
  ('rockfish', null, 'wa-ma-13', 'salt', 'prohibited', 'Rockfish: CLOSED — CLOSED to fishing for, retaining, or possessing.', 'https://www.eregulations.com/washington/fishing/ma-13', 'WDFW — 2026-2027 Washington Sport Fishing Rules (Marine Area ma-13)', '2026-06-18', '2026-09-02', 3,
   null, null, 0, 0, null, null, null, null, null, false, 120),
  ('pacific_cod', null, 'wa-ma-13', 'salt', 'prohibited', 'Pacific Cod, Pollock, Hake, and Wolf-Eel: Year-round — CLOSED to retention.', 'https://www.eregulations.com/washington/fishing/ma-13', 'WDFW — 2026-2027 Washington Sport Fishing Rules (Marine Area ma-13)', '2026-06-18', '2026-09-02', 3,
   null, null, 0, 0, null, null, null, null, 'Also covers pollock, hake, wolf-eel.', false, 120),
  ('sixgill_shark', null, 'wa-ma-13', 'salt', 'prohibited', 'Sixgill, Sevengill, and Thresher Sharks: CLOSED — CLOSED to fishing for, retaining, or possessing. Sixgill shark may not be removed from the water.', 'https://www.eregulations.com/washington/fishing/ma-13', 'WDFW — 2026-2027 Washington Sport Fishing Rules (Marine Area ma-13)', '2026-06-18', '2026-09-02', 3,
   null, null, 0, 0, null, null, null, null, null, true, 60),
  ('cabezon', null, 'wa-ma-13', 'salt', 'bag_limit', 'Cabezon: May 1-Nov. 30 — Min. size 18 in. Daily limit 1.', 'https://www.eregulations.com/washington/fishing/ma-13', 'WDFW — 2026-2027 Washington Sport Fishing Rules (Marine Area ma-13)', '2026-06-18', '2026-09-02', 3,
   '2026-05-01', '2026-11-30', 1, null, 18, null, 'total_length', null, null, true, 30),
  (null, null, 'wa-ma-9', 'salt', 'note', 'Salmon (Entire Area, MA9 Admiralty Inlet): July 16-July 18: Chinook - min. size 22 in. Other salmon species - no min. size. Daily limit 2 including no more than 1 Chinook. Release chum, wild coho, and wild Chinook. July 19-July 31: CLOSED. Aug. 1-Sept. 18: no min. size, daily limit 2, release Chinook, chum, and wild coho. Sept. 19-Sept. 30: no min. size, daily limit 2, release Chinook and chum. (Edmonds Pier and Northern Hood Canal run separate tables; Admiralty Head Marine Preserve and Keystone Conservation Area: year-round CLOSED.)', 'https://www.eregulations.com/washington/fishing/marine-area-9', 'WDFW — 2026-2027 Washington Sport Fishing Rules (Marine Area 9)', '2026-06-18', '2026-09-02', 3,
   null, null, null, null, null, null, null, null, null, true, 7),
  (null, null, 'wa-ma-10', 'salt', 'note', 'Salmon (Entire Area, MA10 Seattle/Bremerton): June 1-July 22: no min. size, daily limit 2, release Chinook and chum. July 23-July 25: Chinook min. 22 in, daily limit 2 incl. ≤1 Chinook, release chum and wild Chinook. July 26-Sept. 30: no min. size, daily limit 2, release Chinook and chum. Oct. 1-Nov. 15: no min. size, daily limit 2, release Chinook. Nov. 16-Mar. 30: CLOSED. Mar. 31-Apr. 30: open Wed.-Sat. only, Chinook min. 22 in, daily limit 2 incl. ≤1 Chinook, release chum and wild Chinook. (Shilshole/West Elliott Bay, East Elliott Bay, Harbor Island, Sinclair Inlet/Port Orchard, Agate Pass, and the four piers run separate tables.)', 'https://www.eregulations.com/washington/fishing/marine-area-10', 'WDFW — 2026-2027 Washington Sport Fishing Rules (Marine Area 10)', '2026-06-18', '2026-09-02', 3,
   null, null, null, null, null, null, null, null, null, true, 7),
  (null, null, 'wa-ma-13', 'salt', 'note', 'Salmon (Entire Area, MA13 South Puget Sound): July 1-Sept. 30: Chinook - min. size 20 in. Other salmon species - no min. size. Daily limit 2. Release chum, wild coho, and wild Chinook. Oct. 1-June 30: Chinook - min. size 22 in. Other salmon species - no min. size. Daily limit 2. Release chum, wild coho, and wild Chinook. Anglers may fish with two poles with Two-Pole Endorsement. (Toliva Shoal, Northern/Southern Budd Inlet, and Fox Island Pier run separate tables.)', 'https://www.eregulations.com/washington/fishing/marine-area-13', 'WDFW — 2026-2027 Washington Sport Fishing Rules (Marine Area 13)', '2026-06-18', '2026-09-02', 3,
   null, null, null, null, null, null, null, null, null, true, 7),
  ('pacific_halibut', null, 'wa-ma-13', 'salt', 'prohibited', 'Pacific Halibut (Marine Area 13): CLOSED — CLOSED to fishing for, retaining, or possessing.', 'https://www.eregulations.com/washington/fishing/marine-area-13', 'WDFW — 2026-2027 Washington Sport Fishing Rules (Marine Area 13)', '2026-06-18', '2026-09-02', 3,
   null, null, 0, 0, null, null, null, null, null, false, 120);

insert into public.reg_pack (id, version, published_at, notes) values
  ('washington-2026-09-02', 3, '2026-09-02T12:00:00Z', 'Washington ocean Marine Areas 1-4 (WDFW news release March 5, 2026) — v2 deepens with the inside-waters doctrine (no rockfish 6-13, barbless hooks 5-13), Puget Sound halibut windows (1/day, 6/yr, catch record card), the North Coast 20-fathom retention list, the C-shaped yelloweye conservation area, wolf-eel closure, and the five-additional-flatfish rule. v3 lands the Puget Sound pamphlet tables for Marine Areas 9, 10 and 13 verbatim (2026-27 book, updated June 18 2026): 15 bottomfish daily, >120ft fishing prohibited, descending device required, lingcod May 1-Jun 15 slot 26-36 in (spear May 21-Jun 15, hook-and-line from May 1), cabezon May 1-Nov 30 @18 in @1, rockfish closed, cod/pollock/hake/wolf-eel closed, salmon headline windows as notes. Crab/shrimp tables still pending.')
on conflict (id) do update set version = excluded.version, notes = excluded.notes;
