-- California GMA layer v2 (Fish Legal: "break up California further" — seasons,
-- depth restrictions, GMAs). GENERATED from the bundles via gen-ca-gma-layer.mts.
-- kind 'groundfish_management_area' is an existing CHECK-allowed value; no schema work.

insert into public.reg_area (id, authority, kind, name, parent_id, boundary_geojson, source_url, verified_at, notes) values
  ('ca-gma-northern', 'cdfw', 'groundfish_management_area', 'Northern GMA — California-Oregon border to Cape Mendocino (40°10′ N)', null, null, 'https://wildlife.ca.gov/Fishing/Ocean/Regulations/Groundfish-Summary', '2026-09-01', 'CCR T14 §27.25(a). Same ring as the pack envelope; GMA rules carry the 2026 season table.'),
  ('ca-gma-mendocino', 'cdfw', 'groundfish_management_area', 'Mendocino GMA — Cape Mendocino (40°10′ N) to Point Arena (38°57.5′ N)', null, null, 'https://wildlife.ca.gov/Fishing/Ocean/Regulations/Groundfish-Summary', '2026-09-01', 'CCR T14 §27.30(a). 2026 table identical to Northern.'),
  ('ca-gma-san-francisco', 'cdfw', 'groundfish_management_area', 'San Francisco GMA — Point Arena (38°57.5′ N) to Pigeon Point (37°11′ N)', null, null, 'https://wildlife.ca.gov/Fishing/Ocean/Regulations/Groundfish-Summary', '2026-09-01', 'CCR T14 §27.35(a). Cordell Bank: ALL groundfish fishing prohibited inside (NMFS compliance guide, June 2026).'),
  ('ca-gma-central', 'cdfw', 'groundfish_management_area', 'Central GMA — Pigeon Point (37°11′ N) to Point Conception (34°27′ N)', null, null, 'https://wildlife.ca.gov/Fishing/Ocean/Regulations/Groundfish-Summary', '2026-09-01', 'CCR T14 §27.40(a). South of here the SoCal pack''s Southern GMA season table rules.')
on conflict (id) do nothing;

insert into public.reg_rule
  (species_id, reg_group_id, reg_area_id, water_class, kind, verbatim, source_url, source_title, source_updated_at, verified_at, pack_version,
   season_start, season_end, bag_daily, possession_limit, min_size_in, max_size_in, size_measure, platform_scope, depth_note, check_inseason, stale_after_days)
values
  (null, 'rcg-complex-norcal', 'ca-gma-northern', 'salt', 'season', 'Nearshore Rockfish, Cabezon, and Greenlings (CCR T14 §1.91(a)(1): black, black and yellow, blue, brown, calico, China, copper, gopher, grass, kelp, and olive rockfishes; treefish; Cabezon and Greenlings per §28.28/§28.29): Jan 1 - Mar 31 — Closed, unlawful to possess in all waters. April 1 - December 31: Open all depths.', 'https://wildlife.ca.gov/Fishing/Ocean/Regulations/Groundfish-Summary', 'CDFW — Summary of Recreational Groundfish Fishing Regulations (updated June 23, 2026)', '2026-06-23', '2026-09-01', 2,
   '2026-01-01', '2026-03-31', null, null, null, null, null, 'boat', null, false, 60),
  (null, 'rcg-complex-norcal', 'ca-gma-northern', 'salt', 'season', 'Nearshore Rockfish, Cabezon, and Greenlings: April 1 - December 31 — Open all depths.', 'https://wildlife.ca.gov/Fishing/Ocean/Regulations/Groundfish-Summary', 'CDFW — Summary of Recreational Groundfish Fishing Regulations (updated June 23, 2026)', '2026-06-23', '2026-09-01', 2,
   '2026-04-01', '2026-12-31', null, null, null, null, null, 'boat', null, false, 60),
  (null, null, 'ca-gma-northern', 'salt', 'season', 'Shelf and Slope Rockfish and Lingcod (shelf per §1.91(a)(3); slope per §1.91(a)(4); lingcod per §28.27): Jan 1 - Mar 31 — Closed, unlawful to possess in all waters. April 1 - December 31: Open all depths.', 'https://wildlife.ca.gov/Fishing/Ocean/Regulations/Groundfish-Summary', 'CDFW — Summary of Recreational Groundfish Fishing Regulations (updated June 23, 2026)', '2026-06-23', '2026-09-01', 2,
   '2026-01-01', '2026-03-31', null, null, null, null, null, 'boat', null, false, 60),
  (null, null, 'ca-gma-northern', 'salt', 'season', 'Shelf and Slope Rockfish and Lingcod: April 1 - December 31 — Open all depths.', 'https://wildlife.ca.gov/Fishing/Ocean/Regulations/Groundfish-Summary', 'CDFW — Summary of Recreational Groundfish Fishing Regulations (updated June 23, 2026)', '2026-06-23', '2026-09-01', 2,
   '2026-04-01', '2026-12-31', null, null, null, null, null, 'boat', null, false, 60),
  (null, 'rcg-complex-norcal', 'ca-gma-northern', 'salt', 'note', 'Statewide daily bag limits: RCG Complex — 10 fish in combination per person, except copper rockfish 1 per person, vermilion/sunset rockfish 2 per person combined (outside the Northern Management Area; 4 per person inside it), canary rockfish 2 per person. Lingcod: 2 per person, 22-inch minimum total length. No retention of bronzespotted rockfish, cowcod, quillback rockfish, or yelloweye rockfish at any time (§28.55).', 'https://wildlife.ca.gov/Fishing/Ocean/Regulations/Groundfish-Summary', 'CDFW — Summary of Recreational Groundfish Fishing Regulations (updated June 23, 2026)', '2026-06-23', '2026-09-01', 2,
   null, null, 10, 10, null, null, null, null, null, false, 60),
  (null, 'rcg-complex-norcal', 'ca-gma-mendocino', 'salt', 'season', 'Nearshore Rockfish, Cabezon, and Greenlings (CCR T14 §1.91(a)(1): black, black and yellow, blue, brown, calico, China, copper, gopher, grass, kelp, and olive rockfishes; treefish; Cabezon and Greenlings per §28.28/§28.29): Jan 1 - Mar 31 — Closed, unlawful to possess in all waters. April 1 - December 31: Open all depths.', 'https://wildlife.ca.gov/Fishing/Ocean/Regulations/Groundfish-Summary', 'CDFW — Summary of Recreational Groundfish Fishing Regulations (updated June 23, 2026)', '2026-06-23', '2026-09-01', 2,
   '2026-01-01', '2026-03-31', null, null, null, null, null, 'boat', null, false, 60),
  (null, 'rcg-complex-norcal', 'ca-gma-mendocino', 'salt', 'season', 'Nearshore Rockfish, Cabezon, and Greenlings: April 1 - December 31 — Open all depths.', 'https://wildlife.ca.gov/Fishing/Ocean/Regulations/Groundfish-Summary', 'CDFW — Summary of Recreational Groundfish Fishing Regulations (updated June 23, 2026)', '2026-06-23', '2026-09-01', 2,
   '2026-04-01', '2026-12-31', null, null, null, null, null, 'boat', null, false, 60),
  (null, null, 'ca-gma-mendocino', 'salt', 'season', 'Shelf and Slope Rockfish and Lingcod (shelf per §1.91(a)(3); slope per §1.91(a)(4); lingcod per §28.27): Jan 1 - Mar 31 — Closed, unlawful to possess in all waters. April 1 - December 31: Open all depths.', 'https://wildlife.ca.gov/Fishing/Ocean/Regulations/Groundfish-Summary', 'CDFW — Summary of Recreational Groundfish Fishing Regulations (updated June 23, 2026)', '2026-06-23', '2026-09-01', 2,
   '2026-01-01', '2026-03-31', null, null, null, null, null, 'boat', null, false, 60),
  (null, null, 'ca-gma-mendocino', 'salt', 'season', 'Shelf and Slope Rockfish and Lingcod: April 1 - December 31 — Open all depths.', 'https://wildlife.ca.gov/Fishing/Ocean/Regulations/Groundfish-Summary', 'CDFW — Summary of Recreational Groundfish Fishing Regulations (updated June 23, 2026)', '2026-06-23', '2026-09-01', 2,
   '2026-04-01', '2026-12-31', null, null, null, null, null, 'boat', null, false, 60),
  (null, 'rcg-complex-norcal', 'ca-gma-mendocino', 'salt', 'note', 'Statewide daily bag limits: RCG Complex — 10 fish in combination per person, except copper rockfish 1 per person, vermilion/sunset rockfish 2 per person combined (outside the Northern Management Area; 4 per person inside it), canary rockfish 2 per person. Lingcod: 2 per person, 22-inch minimum total length. No retention of bronzespotted rockfish, cowcod, quillback rockfish, or yelloweye rockfish at any time (§28.55).', 'https://wildlife.ca.gov/Fishing/Ocean/Regulations/Groundfish-Summary', 'CDFW — Summary of Recreational Groundfish Fishing Regulations (updated June 23, 2026)', '2026-06-23', '2026-09-01', 2,
   null, null, 10, 10, null, null, null, null, null, false, 60),
  (null, 'rcg-complex-norcal', 'ca-gma-san-francisco', 'salt', 'season', 'Nearshore Rockfish, Cabezon, and Greenlings (CCR T14 §1.91(a)(1): black, black and yellow, blue, brown, calico, China, copper, gopher, grass, kelp, and olive rockfishes; treefish; Cabezon and Greenlings per §28.28/§28.29): Jan 1 - Mar 31 — Closed, unlawful to possess in all waters. April 1 - December 31: Open all depths.', 'https://wildlife.ca.gov/Fishing/Ocean/Regulations/Groundfish-Summary', 'CDFW — Summary of Recreational Groundfish Fishing Regulations (updated June 23, 2026)', '2026-06-23', '2026-09-01', 2,
   '2026-01-01', '2026-03-31', null, null, null, null, null, 'boat', null, false, 60),
  (null, 'rcg-complex-norcal', 'ca-gma-san-francisco', 'salt', 'season', 'Nearshore Rockfish, Cabezon, and Greenlings: April 1 - December 31 — Open all depths. with the Cordell Bank all-groundfish prohibition applying inside its footprint', 'https://wildlife.ca.gov/Fishing/Ocean/Regulations/Groundfish-Summary', 'CDFW — Summary of Recreational Groundfish Fishing Regulations (updated June 23, 2026)', '2026-06-23', '2026-09-01', 2,
   '2026-04-01', '2026-12-31', null, null, null, null, null, 'boat', null, false, 60),
  (null, null, 'ca-gma-san-francisco', 'salt', 'season', 'Shelf and Slope Rockfish and Lingcod (shelf per §1.91(a)(3); slope per §1.91(a)(4); lingcod per §28.27): Jan 1 - Mar 31 — Closed, unlawful to possess in all waters. April 1 - December 31: Open all depths.', 'https://wildlife.ca.gov/Fishing/Ocean/Regulations/Groundfish-Summary', 'CDFW — Summary of Recreational Groundfish Fishing Regulations (updated June 23, 2026)', '2026-06-23', '2026-09-01', 2,
   '2026-01-01', '2026-03-31', null, null, null, null, null, 'boat', null, false, 60),
  (null, null, 'ca-gma-san-francisco', 'salt', 'season', 'Shelf and Slope Rockfish and Lingcod: April 1 - December 31 — Open all depths. with the Cordell Bank all-groundfish prohibition applying inside its footprint', 'https://wildlife.ca.gov/Fishing/Ocean/Regulations/Groundfish-Summary', 'CDFW — Summary of Recreational Groundfish Fishing Regulations (updated June 23, 2026)', '2026-06-23', '2026-09-01', 2,
   '2026-04-01', '2026-12-31', null, null, null, null, null, 'boat', null, false, 60),
  (null, 'rcg-complex-norcal', 'ca-gma-san-francisco', 'salt', 'note', 'Statewide daily bag limits: RCG Complex — 10 fish in combination per person, except copper rockfish 1 per person, vermilion/sunset rockfish 2 per person combined (outside the Northern Management Area; 4 per person inside it), canary rockfish 2 per person. Lingcod: 2 per person, 22-inch minimum total length. No retention of bronzespotted rockfish, cowcod, quillback rockfish, or yelloweye rockfish at any time (§28.55).', 'https://wildlife.ca.gov/Fishing/Ocean/Regulations/Groundfish-Summary', 'CDFW — Summary of Recreational Groundfish Fishing Regulations (updated June 23, 2026)', '2026-06-23', '2026-09-01', 2,
   null, null, 10, 10, null, null, null, null, null, false, 60),
  (null, 'rcg-complex-norcal', 'ca-gma-central', 'salt', 'season', 'Nearshore Rockfish, Cabezon, and Greenlings (CCR T14 §1.91(a)(1): black, black and yellow, blue, brown, calico, China, copper, gopher, grass, kelp, and olive rockfishes; treefish; Cabezon and Greenlings per §28.28/§28.29): Jan 1 - Mar 31 — Closed, unlawful to possess in all waters. April 1 - December 31: Open all depths.', 'https://wildlife.ca.gov/Fishing/Ocean/Regulations/Groundfish-Summary', 'CDFW — Summary of Recreational Groundfish Fishing Regulations (updated June 23, 2026)', '2026-06-23', '2026-09-01', 2,
   '2026-01-01', '2026-03-31', null, null, null, null, null, 'boat', null, false, 60),
  (null, 'rcg-complex-norcal', 'ca-gma-central', 'salt', 'season', 'Nearshore Rockfish, Cabezon, and Greenlings: April 1 - December 31 — Open all depths.', 'https://wildlife.ca.gov/Fishing/Ocean/Regulations/Groundfish-Summary', 'CDFW — Summary of Recreational Groundfish Fishing Regulations (updated June 23, 2026)', '2026-06-23', '2026-09-01', 2,
   '2026-04-01', '2026-12-31', null, null, null, null, null, 'boat', null, false, 60),
  (null, null, 'ca-gma-central', 'salt', 'season', 'Shelf and Slope Rockfish and Lingcod (shelf per §1.91(a)(3); slope per §1.91(a)(4); lingcod per §28.27): Jan 1 - Mar 31 — Closed, unlawful to possess in all waters. April 1 - December 31: Open all depths.', 'https://wildlife.ca.gov/Fishing/Ocean/Regulations/Groundfish-Summary', 'CDFW — Summary of Recreational Groundfish Fishing Regulations (updated June 23, 2026)', '2026-06-23', '2026-09-01', 2,
   '2026-01-01', '2026-03-31', null, null, null, null, null, 'boat', null, false, 60),
  (null, null, 'ca-gma-central', 'salt', 'season', 'Shelf and Slope Rockfish and Lingcod: April 1 - December 31 — Open all depths.', 'https://wildlife.ca.gov/Fishing/Ocean/Regulations/Groundfish-Summary', 'CDFW — Summary of Recreational Groundfish Fishing Regulations (updated June 23, 2026)', '2026-06-23', '2026-09-01', 2,
   '2026-04-01', '2026-12-31', null, null, null, null, null, 'boat', null, false, 60),
  (null, 'rcg-complex-norcal', 'ca-gma-central', 'salt', 'note', 'Statewide daily bag limits: RCG Complex — 10 fish in combination per person, except copper rockfish 1 per person, vermilion/sunset rockfish 2 per person combined (outside the Northern Management Area; 4 per person inside it), canary rockfish 2 per person. Lingcod: 2 per person, 22-inch minimum total length. No retention of bronzespotted rockfish, cowcod, quillback rockfish, or yelloweye rockfish at any time (§28.55).', 'https://wildlife.ca.gov/Fishing/Ocean/Regulations/Groundfish-Summary', 'CDFW — Summary of Recreational Groundfish Fishing Regulations (updated June 23, 2026)', '2026-06-23', '2026-09-01', 2,
   null, null, 10, 10, null, null, null, null, null, false, 60),
  (null, null, 'ca-gma-san-francisco', 'salt', 'prohibited', 'Cordell Bank: all groundfish fishing is prohibited to protect sensitive habitat (see the NMFS compliance guide, June 2026).', 'https://wildlife.ca.gov/Fishing/Ocean/Regulations/Groundfish-Summary', 'CDFW — Summary of Recreational Groundfish Fishing Regulations (updated June 23, 2026)', '2026-06-23', '2026-09-01', 2,
   null, null, null, null, null, null, null, null, null, false, 60),
  (null, null, 'ca-gma-central', 'salt', 'note', 'It is unlawful to possess a groundfish species or species group within a Groundfish Management Area where the take and possession of those species are prohibited in all waters of that Groundfish Management Area or in excess of the bag limit of that Groundfish Management Area, regardless of if the groundfish species or species group were taken in a different Groundfish Management Area where the take or possession is authorized (CCR T14 §27.20(b)(1)(A)(1)).', 'https://wildlife.ca.gov/Fishing/Ocean/Regulations/Groundfish-Summary', 'CDFW — Summary of Recreational Groundfish Fishing Regulations (updated June 23, 2026)', '2026-06-23', '2026-09-01', 2,
   null, null, null, null, null, null, null, null, null, false, 60),
  (null, null, 'ca-gma-central', 'salt', 'note', 'Shore-based anglers and spear divers are exempt from seasons and depths. Divers and shore-based anglers are exempt from season and depth restrictions affecting the RCG Complex and other federally managed groundfish (CCR T14, §27.20(b)(1)(C) and (b)(1)(D)). No vessel or watercraft may be used to assist in take under the shore exemption.', 'https://wildlife.ca.gov/Fishing/Ocean/Regulations/Groundfish-Summary', 'CDFW — Summary of Recreational Groundfish Fishing Regulations (updated June 23, 2026)', '2026-06-23', '2026-09-01', 2,
   null, null, null, null, null, null, null, 'shore', null, false, 60);

insert into public.reg_rule
  (species_id, reg_group_id, reg_area_id, water_class, kind, verbatim, source_url, source_title, source_updated_at, verified_at, pack_version,
   season_start, season_end, bag_daily, possession_limit, min_size_in, max_size_in, size_measure, platform_scope, depth_note, check_inseason, stale_after_days)
values
  (null, null, 'ca-gma-southern', 'salt', 'note', 'It is unlawful to possess a groundfish species or species group within a Groundfish Management Area where the take and possession of those species are prohibited in all waters of that Groundfish Management Area or in excess of the bag limit of that Groundfish Management Area, regardless of if the groundfish species or species group were taken in a different Groundfish Management Area where the take or possession is authorized (CCR T14 §27.20(b)(1)(A)(1)).', 'https://wildlife.ca.gov/Fishing/Ocean/Regulations/Groundfish-Summary', 'CDFW — Summary of Recreational Groundfish Fishing Regulations (updated June 23, 2026)', '2026-06-23', '2026-09-01', 2,
   null, null, null, null, null, null, null, null, null, false, 60),
  (null, null, 'ca-gma-southern', 'salt', 'note', 'Transit Provision: in waters where groundfish species or species groups are closed to take or possession but authorized elsewhere, those species may be possessed aboard a vessel that is anchored, drifting, or transiting in or through the closed area. While transiting a closed area, no gear may be deployed other than crustacean hoop nets (§29.80(b)), Dungeness crab traps (§29.80(c)), and dip nets (§28.80) (CCR T14 §27.20(b)(1)(A)).', 'https://wildlife.ca.gov/Fishing/Ocean/Regulations/Groundfish-Summary', 'CDFW — Summary of Recreational Groundfish Fishing Regulations (updated June 23, 2026)', '2026-06-23', '2026-09-01', 2,
   null, null, null, null, null, null, null, null, null, false, 60),
  (null, null, 'ca-gma-southern', 'salt', 'note', 'Groundfish Exclusion Areas: eight Groundfish Exclusion Areas in the Southern Management Area restrict certain fishing activities (CCR T14 §27.50). Cowcod protections — take of groundfish is prohibited inside the GEAs; coordinates on the CDFW Cowcod page and Ocean Sport Fishing interactive map.', 'https://wildlife.ca.gov/Conservation/Marine/Cowcod', 'CDFW — Cowcod conservation / Groundfish Exclusion Areas', null, '2026-09-01', 2,
   null, null, null, null, null, null, null, null, null, false, 60);

insert into public.reg_pack (id, version, published_at, notes) values
  ('norcal-2026-09-01', 2, '2026-09-01T12:00:00Z', 'Northern California (CDFW, Groundfish Summary updated June 23 2026): v2 adds the GMA layer — Northern, Mendocino, San Francisco and Central Groundfish Management Areas are now first-class areas with their own season windows (identical 2026 tables, verbatim), Cordell Bank prohibition, and the GMA-crossing possession rule. Saltwater only; river/salmon checks stay check-in-season.'),
  ('socal-2026-09-01', 2, '2026-09-01T00:00:00.000Z', 'Hand-verified starter set + v2 Groundfish Management Area doctrine rows (GMA-crossing possession, transit provision, GEA note) from the Groundfish Summary updated June 23, 2026.')
on conflict (id) do update set version = excluded.version, notes = excluded.notes;
