-- Washington v6 (2026-09-03): structured chinook season rows for Marine Areas
-- 9/10/13 — verbatim windows from the 2026-27 pamphlet tables; the v3 headline note
-- rows stay as the full verbatim of record (incl. sub-area pointer lists).
-- GENERATED via gen-wa-salmon-structure-v6.mts. Insert-only + pack upsert to 6.

insert into public.reg_rule
  (species_id, reg_group_id, reg_area_id, water_class, kind, verbatim, source_url, source_title, source_updated_at, verified_at, pack_version,
   season_start, season_end, bag_daily, possession_limit, min_size_in, max_size_in, size_measure, platform_scope, depth_note, check_inseason, stale_after_days)
values
  ('chinook_salmon', null, 'wa-ma-9', 'salt', 'season', 'Salmon (Entire Area, MA9): July 16-July 18: Chinook - min. size 22 in. Other salmon species - no min. size. Daily limit 2 including no more than 1 Chinook. Release chum, wild coho, and wild Chinook.', 'https://www.eregulations.com/washington/fishing/marine-area-9', 'WDFW — 2026-2027 Washington Sport Fishing Rules (Marine Area 9)', '2026-06-18', '2026-09-02', 6,
   '2026-07-16', '2026-07-18', 1, null, 22, null, 'total_length', null, 'Hatchery chinook only (release wild); salmon aggregate 2; release chum + wild coho.', true, 7),
  ('chinook_salmon', null, 'wa-ma-9', 'salt', 'prohibited', 'Salmon (Entire Area, MA9): July 19-July 31: CLOSED. Aug. 1-Sept. 18: no min. size, daily limit 2, release Chinook, chum, and wild coho. Sept. 19-Sept. 30: no min. size, daily limit 2, release Chinook and chum.', 'https://www.eregulations.com/washington/fishing/marine-area-9', 'WDFW — 2026-2027 Washington Sport Fishing Rules (Marine Area 9)', '2026-06-18', '2026-09-02', 6,
   '2026-07-19', '2026-09-30', 0, 0, null, null, null, null, 'Chinook release Jul 19-Sep 30 (Jul 19-31 all-salmon CLOSED outright).', true, 7),
  ('chinook_salmon', null, 'wa-ma-10', 'salt', 'prohibited', 'Salmon (Entire Area, MA10): June 1-July 22: no min. size, daily limit 2, release Chinook and chum.', 'https://www.eregulations.com/washington/fishing/marine-area-10', 'WDFW — 2026-2027 Washington Sport Fishing Rules (Marine Area 10)', '2026-06-18', '2026-09-02', 6,
   '2026-06-01', '2026-07-22', 0, 0, null, null, null, null, 'Chinook release; other salmon 2/day.', true, 7),
  ('chinook_salmon', null, 'wa-ma-10', 'salt', 'season', 'Salmon (Entire Area, MA10): July 23-July 25: Chinook min. 22 in, daily limit 2 including no more than 1 Chinook, release chum and wild Chinook.', 'https://www.eregulations.com/washington/fishing/marine-area-10', 'WDFW — 2026-2027 Washington Sport Fishing Rules (Marine Area 10)', '2026-06-18', '2026-09-02', 6,
   '2026-07-23', '2026-07-25', 1, null, 22, null, 'total_length', null, 'Hatchery chinook only (release wild); salmon aggregate 2; release chum.', true, 7),
  ('chinook_salmon', null, 'wa-ma-10', 'salt', 'prohibited', 'Salmon (Entire Area, MA10): July 26-Sept. 30: no min. size, daily limit 2, release Chinook and chum. Oct. 1-Nov. 15: no min. size, daily limit 2, release Chinook.', 'https://www.eregulations.com/washington/fishing/marine-area-10', 'WDFW — 2026-2027 Washington Sport Fishing Rules (Marine Area 10)', '2026-06-18', '2026-09-02', 6,
   '2026-07-26', '2026-11-15', 0, 0, null, null, null, null, 'Chinook release; other salmon 2/day (release chum through Sep 30).', true, 7),
  (null, null, 'wa-ma-10', 'salt', 'season', 'Salmon (Entire Area, MA10): Nov. 16-Mar. 30: CLOSED.', 'https://www.eregulations.com/washington/fishing/marine-area-10', 'WDFW — 2026-2027 Washington Sport Fishing Rules (Marine Area 10)', '2026-06-18', '2026-09-02', 6,
   '2026-11-16', '2026-03-30', 0, 0, null, null, null, null, 'All-salmon closed (window wraps New Year''s).', true, 7),
  ('chinook_salmon', null, 'wa-ma-10', 'salt', 'season', 'Salmon (Entire Area, MA10): Mar. 31-Apr. 30: open Wed.-Sat. only, Chinook min. 22 in, daily limit 2 including no more than 1 Chinook, release chum and wild Chinook.', 'https://www.eregulations.com/washington/fishing/marine-area-10', 'WDFW — 2026-2027 Washington Sport Fishing Rules (Marine Area 10)', '2026-06-18', '2026-09-02', 6,
   '2026-03-31', '2026-04-30', 1, null, 22, null, 'total_length', null, 'Wed-Sat only (weekday gate is not modeled); hatchery chinook only; aggregate 2.', true, 7),
  ('chinook_salmon', null, 'wa-ma-13', 'salt', 'season', 'Salmon (Entire Area, MA13): July 1-Sept. 30: Chinook - min. size 20 in. Other salmon species - no min. size. Daily limit 2. Release chum, wild coho, and wild Chinook.', 'https://www.eregulations.com/washington/fishing/marine-area-13', 'WDFW — 2026-2027 Washington Sport Fishing Rules (Marine Area 13)', '2026-06-18', '2026-09-02', 6,
   '2026-07-01', '2026-09-30', 2, null, 20, null, 'total_length', null, 'Hatchery chinook only (release wild); salmon aggregate 2; release chum + wild coho.', true, 7),
  ('chinook_salmon', null, 'wa-ma-13', 'salt', 'season', 'Salmon (Entire Area, MA13): Oct. 1-June 30: Chinook - min. size 22 in. Other salmon species - no min. size. Daily limit 2. Release chum, wild coho, and wild Chinook. Anglers may fish with two poles with Two-Pole Endorsement.', 'https://www.eregulations.com/washington/fishing/marine-area-13', 'WDFW — 2026-2027 Washington Sport Fishing Rules (Marine Area 13)', '2026-06-18', '2026-09-02', 6,
   '2026-10-01', '2026-06-30', 2, null, 22, null, 'total_length', null, 'Wraps New Year''s; hatchery chinook only; two-pole endorsement allowed.', true, 7);

insert into public.reg_pack (id, version, published_at, notes) values
  ('washington-2026-09-02', 6, '2026-09-02T12:00:00Z', 'Washington ocean Marine Areas 1-4 (WDFW news release March 5, 2026) — v2 deepens with the inside-waters doctrine (no rockfish 6-13, barbless hooks 5-13), Puget Sound halibut windows (1/day, 6/yr, catch record card), the North Coast 20-fathom retention list, the C-shaped yelloweye conservation area, wolf-eel closure, and the five-additional-flatfish rule. v3 lands the Puget Sound pamphlet tables for Marine Areas 9, 10 and 13 verbatim (2026-27 book, updated June 18 2026): 15 bottomfish daily, >120ft fishing prohibited, descending device required, lingcod May 1-Jun 15 slot 26-36 in (spear May 21-Jun 15, hook-and-line from May 1), cabezon May 1-Nov 30 @18 in @1, rockfish closed, cod/pollock/hake/wolf-eel closed, salmon headline windows as notes. v4 lands the Crab Rules page verbatim: Puget Sound (Dungeness 5 @ 6.25 in males hardshell / Red Rock 6 @ 5 in / Tanner 6 @ 4.5 in; CRC + endorsement; MA12 south of Ayock Point + MA13 closed to crab in 2026), Pacific Ocean (Dungeness 6 @ 6 in + Red Rock 6 @ 5 in; pot window Dec 1-Sep 15, year-round other gear; Willapa Bay pots Nov 15-Sep 15), Columbia River estuary (Dungeness 12 @ 5.75 in, year-round all gear), European green crab report-and-release. Shrimp tables land in v5 (separate PR). v6 promotes the MA9/10/13 salmon headline notes to structured chinook season rows: per-window size/bag with wild-release clauses, wrap-capable seasons, and sub-area pointers in the notes.')
on conflict (id) do update set version = excluded.version, notes = excluded.notes;
