-- Pacific Northwest wave v1 (24-state expansion, 2026-09-02): Oregon (ODFW) and
-- Washington (WDFW) ocean packs. GENERATED from the bundles via gen-pnw-wave.mts.
-- Insert-only; older migrations are history and stay frozen.

insert into public.species (id, common_name, scientific_name, is_group, rolls_up_to, water_class, take_status, sort_order, needs_review) values
  ('canary_rockfish', 'Canary rockfish', 'Sebastes pinniger', false, 'rockfish', 'salt', 'regulated', 456, false),
  ('blue_rockfish', 'Blue rockfish', 'Sebastes mystinus', false, 'rockfish', 'salt', 'regulated', 457, false),
  ('black_rockfish', 'Black rockfish', 'Sebastes melanops', false, 'rockfish', 'salt', 'regulated', 458, false),
  ('yellowtail_rockfish', 'Yellowtail rockfish', 'Sebastes flavidus', false, 'rockfish', 'salt', 'regulated', 459, false),
  ('widow_rockfish', 'Widow rockfish', 'Sebastes entomelas', false, 'rockfish', 'salt', 'regulated', 460, false),
  ('bocaccio', 'Bocaccio', 'Sebastes paucispinis', false, 'rockfish', 'salt', 'regulated', 461, false),
  ('copper_rockfish', 'Copper rockfish', 'Sebastes caurinus', false, 'rockfish', 'salt', 'regulated', 462, false),
  ('quillback_rockfish', 'Quillback rockfish', 'Sebastes maliger', false, 'rockfish', 'salt', 'regulated', 463, false),
  ('vermilion_rockfish', 'Vermilion rockfish', 'Sebastes miniatus', false, 'rockfish', 'salt', 'regulated', 464, false),
  ('yelloweye_rockfish', 'Yelloweye rockfish', 'Sebastes ruberrimus', false, 'rockfish', 'salt', 'protected', 465, false),
  ('sablefish', 'Sablefish (black cod)', 'Anoplopoma fimbria', false, null, 'salt', 'regulated', 466, false),
  ('pacific_cod', 'Pacific cod', 'Gadus macrocephalus', false, null, 'salt', 'regulated', 467, false),
  ('shiner_perch', 'Shiner perch', 'Cymatogaster aggregata', false, 'surfperch', 'salt', 'open', 468, false),
  ('sixgill_shark', 'Sixgill shark', 'Hexanchus griseus', false, null, 'salt', 'protected', 469, false),
  ('flatfish', 'Flatfish (sole, sanddab, flounder)', 'Pleuronectidae', true, null, 'salt', 'open', 470, false)
on conflict (id) do nothing;

insert into public.reg_area (id, authority, kind, name, parent_id, boundary_geojson, source_url, verified_at, notes) values
  ('or-marine', 'odfw', 'ocean_region', 'Oregon marine zone (ocean waters)', null, '[[-124.6,42],[-124.2,43.4],[-124.1,44.6],[-124.05,45.5],[-124,46.25],[-123.9,46.25],[-124.6,46.25],[-124.6,42]]', 'https://myodfw.com/sport-bottomfish-seasons', '2026-09-02', 'Envelope. ODFW Marine Zone = ocean plus bay stumps; estuary/river rules are NOT in this pack yet. Inseason changes are common — see the inseason note row.'),
  ('or-halibut-central', 'noaa', 'ocean_region', 'Central Oregon Coast halibut subarea (Cape Falcon to Humbug Mountain)', null, '[[-124.4,42.67],[-124.3,44],[-124.1,45.77],[-124,45.77],[-124,42.67],[-124.3,42.67],[-124.4,42.67]]', 'https://www.fisheries.noaa.gov/action/2026-pacific-halibut-recreational-fishery', '2026-09-02', 'IPHC Area 2A wording: “Central Coast”. Nearshore = inside 40 fm.'),
  ('or-halibut-southern', 'noaa', 'ocean_region', 'Southern Oregon halibut subarea (Humbug Mountain to the California border)', null, '[[-124.4,42],[-124.4,42.67],[-124,42.67],[-124,42],[-124.4,42]]', 'https://www.fisheries.noaa.gov/action/2026-pacific-halibut-recreational-fishery', '2026-09-02', 'IPHC Area 2A Oregon Southern Coast allocation (8,000 lb for 2026).')
on conflict (id) do nothing;

insert into public.reg_group (id, name, member_species_ids, source_url, verified_at) values
  ('or-general-marine', 'General marine species (rockfish, cabezon, greenling, skates, etc.)', '{rockfish,black_rockfish,blue_rockfish,canary_rockfish,copper_rockfish,quillback_rockfish,vermilion_rockfish,yelloweye_rockfish,bocaccio,widow_rockfish,yellowtail_rockfish,cabezon,kelp_greenling}', 'https://myodfw.com/sport-bottomfish-seasons', '2026-09-02'),
  ('or-longleader', 'Offshore long-leader bag (10 named rockfish species)', '{yellowtail_rockfish,widow_rockfish,canary_rockfish,blue_rockfish,bocaccio}', 'https://myodfw.com/sport-bottomfish-seasons', '2026-09-02')
on conflict (id) do nothing;

insert into public.reg_rule
  (species_id, reg_group_id, reg_area_id, water_class, kind, verbatim, source_url, source_title, source_updated_at, verified_at, pack_version,
   season_start, season_end, bag_daily, possession_limit, min_size_in, max_size_in, size_measure, platform_scope, depth_note, check_inseason, stale_after_days)
values
  ('rockfish', 'or-general-marine', 'or-marine', 'salt', 'season', 'Rockfish / Cabezon / Lingcod / Etc.: Open at all-depths year-round, no seasonal depth restriction.', 'https://myodfw.com/sport-bottomfish-seasons', 'ODFW — Sport Bottomfish Seasons (2026 recreational bottomfish seasons/regulations)', '2025-12-31', '2026-09-02', 1,
   '2026-01-01', '2026-12-31', null, null, null, null, null, 'boat', null, false, 60),
  (null, 'or-general-marine', 'or-marine', 'salt', 'bag_limit', 'General marine species (rockfish, cabezon, greenling, skates, etc.): 4-fish daily bag limit per angler beginning January 1, 2026.', 'https://myodfw.com/sport-bottomfish-seasons', 'ODFW — Sport Bottomfish Seasons (2026 recreational bottomfish seasons/regulations)', '2025-12-31', '2026-09-02', 1,
   null, null, 4, null, null, null, null, null, null, true, 30),
  ('canary_rockfish', null, 'or-marine', 'salt', 'bag_limit', 'Canary rockfish: 2-fish daily sub-bag limit per angler as part of the general marine bag limit, beginning January 1, 2026.', 'https://myodfw.com/sport-bottomfish-seasons', 'ODFW — Sport Bottomfish Seasons (2026 recreational bottomfish seasons/regulations)', '2025-12-31', '2026-09-02', 1,
   null, null, 2, null, null, null, null, null, null, true, 30),
  ('cabezon', null, 'or-marine', 'salt', 'season', 'Cabezon: 1-fish daily sub-bag limit per angler as part of the general marine bag limit beginning July 1, 2026. Minimum length of 16 inches. No retention January 1 through June 30.', 'https://myodfw.com/sport-bottomfish-seasons', 'ODFW — Sport Bottomfish Seasons (2026 recreational bottomfish seasons/regulations)', '2025-12-31', '2026-09-02', 1,
   '2026-01-01', '2026-06-30', 0, null, null, null, null, null, null, true, 30),
  ('cabezon', null, 'or-marine', 'salt', 'bag_limit', 'Cabezon: 1-fish daily sub-bag limit per angler as part of the general marine bag limit beginning July 1, 2026. Minimum length of 16 inches. No retention January 1 through June 30.', 'https://myodfw.com/sport-bottomfish-seasons', 'ODFW — Sport Bottomfish Seasons (2026 recreational bottomfish seasons/regulations)', '2025-12-31', '2026-09-02', 1,
   '2026-07-01', '2026-12-31', 1, null, 16, null, 'total_length', null, null, true, 30),
  ('lingcod', null, 'or-marine', 'salt', 'bag_limit', 'Lingcod: 3-fish daily bag limit per angler beginning January 1, 2026 with a minimum length limit of 22 inches. Lingcod are not part of the general marine species bag limit.', 'https://myodfw.com/sport-bottomfish-seasons', 'ODFW — Sport Bottomfish Seasons (2026 recreational bottomfish seasons/regulations)', '2025-12-31', '2026-09-02', 1,
   null, null, 3, null, 22, null, 'total_length', null, null, true, 30),
  ('sablefish', null, 'or-marine', 'salt', 'bag_limit', 'Sablefish: 10-fish daily bag limit per angler. Sablefish are not part of the general marine species bag limit.', 'https://myodfw.com/sport-bottomfish-seasons', 'ODFW — Sport Bottomfish Seasons (2026 recreational bottomfish seasons/regulations)', '2025-12-31', '2026-09-02', 1,
   null, null, 10, null, null, null, null, null, null, true, 30),
  ('flatfish', null, 'or-marine', 'salt', 'bag_limit', 'Flatfish daily bag limit is 25 fish for species of sanddab, sole, flounder, etc. Does not include Pacific halibut. Open at all depths year round.', 'https://myodfw.com/sport-bottomfish-seasons', 'ODFW — Sport Bottomfish Seasons (2026 recreational bottomfish seasons/regulations)', '2025-12-31', '2026-09-02', 1,
   null, null, 25, null, null, null, null, null, null, true, 30),
  (null, 'or-longleader', 'or-marine', 'salt', 'note', 'Offshore long-leader gear fishery: The daily bag limit is 10 fish per angler. For canary rockfish, there is a daily sub-bag limit of two fish per angler beginning January 1, 2026. The only species allowed in the daily long-leader gear bag limit are: yellowtail, widow, canary, redstripe, greenstriped, silvergray, chilipepper, blue, deacon, and bocaccio rockfishes. Lingcod cannot be retained. Offshore long-leader gear fishery trips cannot be combined with traditional bottomfish trips.', 'https://myodfw.com/sport-bottomfish-seasons', 'ODFW — Sport Bottomfish Seasons (2026 recreational bottomfish seasons/regulations)', '2025-12-31', '2026-09-02', 1,
   null, null, 10, null, null, null, null, 'boat', 'Offshore long-leader fishery only.', true, 30),
  ('yelloweye_rockfish', null, 'or-marine', 'salt', 'prohibited', 'Retention of quillback rockfish and yelloweye rockfish remains prohibited. Yelloweye rockfish is a protected species.', 'https://myodfw.com/recreation-report/fishing-report/marine-zone', 'ODFW — Marine Zone Recreation Report', '2026-08-27', '2026-09-02', 1,
   null, null, 0, 0, null, null, null, null, null, true, 30),
  ('quillback_rockfish', null, 'or-marine', 'salt', 'prohibited', 'Retention of quillback rockfish and yelloweye rockfish remains prohibited.', 'https://myodfw.com/recreation-report/fishing-report/marine-zone', 'ODFW — Marine Zone Recreation Report', '2026-08-27', '2026-09-02', 1,
   null, null, 0, 0, null, null, null, null, null, true, 30),
  (null, null, 'or-marine', 'salt', 'note', 'Any vessel fishing for or possessing bottomfish, Pacific halibut, or flatfish in the ocean must have a functional descending device onboard; and are required to use it on any rockfish released outside of 30 fathoms.', 'https://myodfw.com/sites/default/files/2018-06/2018-groundfish%20fishery%20what%20can%20i%20keep-07012018%20update.pdf', 'ODFW — Groundfish: what can I keep, and how many? (descending device rule)', '2018-07-01', '2026-09-02', 1,
   null, null, null, null, null, null, null, 'boat', null, false, 120),
  (null, null, 'or-marine', 'salt', 'note', 'Regulations can change inseason, check https://myodfw.com/fishing/marine-zone before you go fishing. The Commission set the 2026 groundfish regulations December 12, 2025; the marine bag and lingcod limits were trimmed inseason in 2025 when harvest guidelines approached.', 'https://myodfw.com/news/commission-sets-2026-groundfish-seasons', 'ODFW — Commission sets 2026 groundfish seasons (press release)', '2025-12-12', '2026-09-02', 1,
   null, null, null, null, null, null, null, null, null, true, 14),
  ('pacific_halibut', null, 'or-halibut-central', 'salt', 'bag_limit', 'Oregon: The daily bag limit is two Pacific halibut of any size per person unless otherwise specified through inseason action.', 'https://www.fisheries.noaa.gov/action/2026-pacific-halibut-recreational-fishery', 'NOAA Fisheries — 2026 Pacific Halibut Recreational Fishery (final rule, Area 2A)', '2026-05-01', '2026-09-02', 1,
   null, null, 2, null, null, null, null, null, null, true, 14),
  ('pacific_halibut', null, 'or-halibut-central', 'salt', 'season', 'Central Coast nearshore — Cape Falcon south to Humbug Mountain, shoreward of a boundary line approximating the 40-fm depth contour: May 1 through October 31, 7 days a week. The area will be closed when there is not sufficient subarea allocation for another full day of fishing.', 'https://www.fisheries.noaa.gov/action/2026-pacific-halibut-recreational-fishery', 'NOAA Fisheries — 2026 Pacific Halibut Recreational Fishery (final rule, Area 2A)', '2026-05-01', '2026-09-02', 1,
   '2026-05-01', '2026-10-31', null, null, null, null, null, 'boat', 'Nearshore: inside 40 fathoms.', true, 14),
  ('pacific_halibut', null, 'or-halibut-central', 'salt', 'season', 'Central Coast all-depth — Spring: May 1 through July 31, 7 days a week. Summer: August 1 through October 31, 7 days a week. The area will be closed when there is not sufficient subarea allocation for another full day of fishing.', 'https://www.fisheries.noaa.gov/action/2026-pacific-halibut-recreational-fishery', 'NOAA Fisheries — 2026 Pacific Halibut Recreational Fishery (final rule, Area 2A)', '2026-05-01', '2026-09-02', 1,
   '2026-05-01', '2026-07-31', null, null, null, null, null, 'boat', 'All-depth window (spring).', true, 14),
  ('pacific_halibut', null, 'or-halibut-central', 'salt', 'season', 'Central Coast all-depth — Spring: May 1 through July 31, 7 days a week. Summer: August 1 through October 31, 7 days a week. The area will be closed when the remaining combined spring and summer allocations are not sufficient for another full day of fishing.', 'https://www.fisheries.noaa.gov/action/2026-pacific-halibut-recreational-fishery', 'NOAA Fisheries — 2026 Pacific Halibut Recreational Fishery (final rule, Area 2A)', '2026-05-01', '2026-09-02', 1,
   '2026-08-01', '2026-10-31', null, null, null, null, null, 'boat', 'All-depth window (summer).', true, 14),
  ('pacific_halibut', null, 'or-halibut-southern', 'salt', 'season', 'Southern Oregon — Humbug Mountain to the Oregon/California border: May 1 through October 31, 7 days a week. The daily bag limit is two Pacific halibut of any size per person. The area will be closed when there is not sufficient subarea allocation for another full day of fishing.', 'https://www.fisheries.noaa.gov/action/2026-pacific-halibut-recreational-fishery', 'NOAA Fisheries — 2026 Pacific Halibut Recreational Fishery (final rule, Area 2A)', '2026-05-01', '2026-09-02', 1,
   '2026-05-01', '2026-10-31', 2, null, null, null, null, 'boat', null, true, 14);

insert into public.reg_pack (id, version, published_at, notes) values
  ('oregon-2026-09-02', 1, '2026-09-02T12:00:00Z', 'Oregon ocean (ODFW): 2026 marine bottomfish table verbatim — general marine 4/day all depths year-round, canary 2 sub-bag, cabezon 1 (Jul–Dec, 16-inch), lingcod 3 (22-inch), sablefish 10, flatfish 25, offshore long-leader 10, halibut per the federal Area 2A catch-sharing plan. Yelloweye and quillback rockfish retention prohibited; descending device mandatory on boats. Salmon/shellfish not yet shipped.')
on conflict (id) do update set version = excluded.version, notes = excluded.notes;

insert into public.reg_area (id, authority, kind, name, parent_id, boundary_geojson, source_url, verified_at, notes) values
  ('wa-ma-1-4-coastal', 'wdfw', 'ocean_region', 'Coastal Marine Areas 1–4 (Ilwaco / Westport / La Push / Neah Bay west of Bonilla–Tatoosh)', null, '[[-124.8,46.25],[-124.7,46.9],[-124.3,47.3],[-124.7,47.95],[-124.8,48.2],[-124.75,48.5],[-124,46.25],[-124.8,46.25]]', 'https://wdfw.wa.gov/newsroom/news-release/coastal-recreational-bottomfish-fishery-season-opens-march-14-1', '2026-09-02', 'Envelope of WDFW Marine Areas 1–4 west of the Bonilla–Tatoosh line. Puget Sound areas 5–13 follow the Washington Sport Fishing Rules pamphlet — not shipped yet.'),
  ('wa-ma4-east', 'wdfw', 'ocean_region', 'Marine Area 4 east of the Bonilla–Tatoosh boundary (Neah Bay east)', null, '[[-124.75,48.35],[-124.6,48.28],[-124.45,48.2],[-124.4,48.35],[-124.6,48.42],[-124.75,48.42],[-124.75,48.35]]', 'https://wdfw.wa.gov/newsroom/news-release/coastal-recreational-bottomfish-fishery-season-opens-march-14-1', '2026-09-02', 'Year-round bottomfish here; rockfish retention limited to the four named species.')
on conflict (id) do nothing;

insert into public.reg_group (id, name, member_species_ids, source_url, verified_at) values
  ('wa-bottomfish', 'Bottomfish daily aggregate (9 across the family''s species)', '{rockfish,black_rockfish,blue_rockfish,canary_rockfish,copper_rockfish,quillback_rockfish,vermilion_rockfish,yelloweye_rockfish,bocaccio,widow_rockfish,yellowtail_rockfish,cabezon,kelp_greenling,lingcod,sablefish,pacific_cod}', 'https://wdfw.wa.gov/newsroom/news-release/coastal-recreational-bottomfish-fishery-season-opens-march-14-1', '2026-09-02'),
  ('wa-rockfish', 'Rockfish sub-limit (7) within the bottomfish aggregate', '{rockfish,black_rockfish,blue_rockfish,canary_rockfish,copper_rockfish,quillback_rockfish,vermilion_rockfish,yelloweye_rockfish,bocaccio,widow_rockfish,yellowtail_rockfish}', 'https://wdfw.wa.gov/newsroom/news-release/coastal-recreational-bottomfish-fishery-season-opens-march-14-1', '2026-09-02'),
  ('wa-ma4-east-rockfish', 'Retainable rockfish in Marine Area 4 east (black, blue/deacon, yellowtail, widow)', '{black_rockfish,blue_rockfish,yellowtail_rockfish,widow_rockfish}', 'https://wdfw.wa.gov/newsroom/news-release/coastal-recreational-bottomfish-fishery-season-opens-march-14-1', '2026-09-02')
on conflict (id) do nothing;

insert into public.reg_rule
  (species_id, reg_group_id, reg_area_id, water_class, kind, verbatim, source_url, source_title, source_updated_at, verified_at, pack_version,
   season_start, season_end, bag_daily, possession_limit, min_size_in, max_size_in, size_measure, platform_scope, depth_note, check_inseason, stale_after_days)
values
  (null, 'wa-bottomfish', 'wa-ma-1-4-coastal', 'salt', 'season', 'Marine Area 1 (Ilwaco), Marine Area 2 (Westport-Ocean Shores), Marine Area 3 (La Push) and Marine Area 4 (Neah Bay west of Bonilla-Tatoosh boundary line) is open from March 14 through Oct. 17.', 'https://wdfw.wa.gov/newsroom/news-release/coastal-recreational-bottomfish-fishery-season-opens-march-14-1', 'WDFW — Coastal recreational bottomfish fishery season opens March 14 (news release)', '2026-03-05', '2026-09-02', 1,
   '2026-03-14', '2026-10-17', null, null, null, null, null, 'boat', null, true, 30),
  (null, 'wa-bottomfish', 'wa-ma-1-4-coastal', 'salt', 'bag_limit', 'Daily aggregate limit is nine bottomfish and includes a sub-limit of seven rockfish (sub-limit of five canary rockfish), two lingcod, and one cabezon per angler with no minimum size restriction. A daily aggregate limit is a combination of nine bottomfish species.', 'https://wdfw.wa.gov/newsroom/news-release/coastal-recreational-bottomfish-fishery-season-opens-march-14-1', 'WDFW — Coastal recreational bottomfish fishery season opens March 14 (news release)', '2026-03-05', '2026-09-02', 1,
   '2026-03-14', '2026-10-17', 9, null, null, null, null, null, null, true, 30),
  (null, 'wa-rockfish', 'wa-ma-1-4-coastal', 'salt', 'bag_limit', 'Daily aggregate limit is nine bottomfish and includes a sub-limit of seven rockfish (sub-limit of five canary rockfish), two lingcod, and one cabezon per angler with no minimum size restriction.', 'https://wdfw.wa.gov/newsroom/news-release/coastal-recreational-bottomfish-fishery-season-opens-march-14-1', 'WDFW — Coastal recreational bottomfish fishery season opens March 14 (news release)', '2026-03-05', '2026-09-02', 1,
   '2026-03-14', '2026-10-17', 7, null, null, null, null, null, null, true, 30),
  ('canary_rockfish', null, 'wa-ma-1-4-coastal', 'salt', 'bag_limit', 'The daily possession sub-bag limit of five canary rockfish remains the same for the 2026 coastal recreational bottomfish fisheries in Marine Area 1 (Ilwaco), Marine Area 2 (Westport-Ocean Shores), Marine Area 3 (La Push), and Marine Area 4 (Neah Bay west of the Bonilla-Tatoosh boundary line).', 'https://wdfw.wa.gov/newsroom/news-release/coastal-recreational-bottomfish-fishery-season-opens-march-14-1', 'WDFW — Coastal recreational bottomfish fishery season opens March 14 (news release)', '2026-03-05', '2026-09-02', 1,
   '2026-03-14', '2026-10-17', 5, null, null, null, null, null, null, true, 30),
  ('lingcod', null, 'wa-ma-1-4-coastal', 'salt', 'bag_limit', 'Daily aggregate limit is nine bottomfish and includes a sub-limit of seven rockfish (sub-limit of five canary rockfish), two lingcod, and one cabezon per angler with no minimum size restriction.', 'https://wdfw.wa.gov/newsroom/news-release/coastal-recreational-bottomfish-fishery-season-opens-march-14-1', 'WDFW — Coastal recreational bottomfish fishery season opens March 14 (news release)', '2026-03-05', '2026-09-02', 1,
   '2026-03-14', '2026-10-17', 2, null, null, null, null, null, null, true, 30),
  ('cabezon', null, 'wa-ma-1-4-coastal', 'salt', 'bag_limit', 'Daily aggregate limit is nine bottomfish and includes a sub-limit of seven rockfish (sub-limit of five canary rockfish), two lingcod, and one cabezon per angler with no minimum size restriction.', 'https://wdfw.wa.gov/newsroom/news-release/coastal-recreational-bottomfish-fishery-season-opens-march-14-1', 'WDFW — Coastal recreational bottomfish fishery season opens March 14 (news release)', '2026-03-05', '2026-09-02', 1,
   '2026-03-14', '2026-10-17', 1, null, null, null, null, null, null, true, 30),
  ('copper_rockfish', null, 'wa-ma-1-4-coastal', 'salt', 'season', 'Anglers are reminded that possession of copper rockfish, quillback rockfish, and vermilion rockfish is prohibited in May, June, and July, when peak effort for bottomfish occurs. Anglers cannot possess copper rockfish, quillback rockfish, and vermilion rockfish in May, June, and July.', 'https://wdfw.wa.gov/newsroom/news-release/coastal-recreational-bottomfish-fishery-season-opens-march-14-1', 'WDFW — Coastal recreational bottomfish fishery season opens March 14 (news release)', '2026-03-05', '2026-09-02', 1,
   '2026-05-01', '2026-07-31', 0, null, null, null, null, null, null, true, 30),
  ('quillback_rockfish', null, 'wa-ma-1-4-coastal', 'salt', 'season', 'Possession of quillback rockfish is prohibited in May, June, and July. Anglers cannot possess copper rockfish, quillback rockfish, and vermilion rockfish in May, June, and July.', 'https://wdfw.wa.gov/newsroom/news-release/coastal-recreational-bottomfish-fishery-season-opens-march-14-1', 'WDFW — Coastal recreational bottomfish fishery season opens March 14 (news release)', '2026-03-05', '2026-09-02', 1,
   '2026-05-01', '2026-07-31', 0, null, null, null, null, null, null, true, 30),
  ('vermilion_rockfish', null, 'wa-ma-1-4-coastal', 'salt', 'season', 'Possession of vermilion rockfish is prohibited in May, June, and July. Anglers cannot possess copper rockfish, quillback rockfish, and vermilion rockfish in May, June, and July.', 'https://wdfw.wa.gov/newsroom/news-release/coastal-recreational-bottomfish-fishery-season-opens-march-14-1', 'WDFW — Coastal recreational bottomfish fishery season opens March 14 (news release)', '2026-03-05', '2026-09-02', 1,
   '2026-05-01', '2026-07-31', 0, null, null, null, null, null, null, true, 30),
  ('yelloweye_rockfish', null, 'wa-ma-1-4-coastal', 'salt', 'prohibited', 'Yelloweye rockfish retention is prohibited in all areas of Washington and must be released.', 'https://wdfw.wa.gov/newsroom/news-release/coastal-recreational-bottomfish-fishery-season-opens-march-14-1', 'WDFW — Coastal recreational bottomfish fishery season opens March 14 (news release)', '2026-03-05', '2026-09-02', 1,
   null, null, 0, 0, null, null, null, null, null, true, 30),
  (null, null, 'wa-ma-1-4-coastal', 'salt', 'note', 'Anglers are reminded that a descending device must be on board vessels and rigged for immediate use when fishing for or possessing bottomfish and halibut.', 'https://wdfw.wa.gov/newsroom/news-release/coastal-recreational-bottomfish-fishery-season-opens-march-14-1', 'WDFW — Coastal recreational bottomfish fishery season opens March 14 (news release)', '2026-03-05', '2026-09-02', 1,
   null, null, null, null, null, null, null, 'boat', null, false, 120),
  (null, 'wa-bottomfish', 'wa-ma4-east', 'salt', 'season', 'Marine Area 4 (Neah Bay east of Bonilla-Tatoosh boundary line) is open year-round. Lingcod fishing is open from March 14 through Oct. 17.', 'https://wdfw.wa.gov/newsroom/news-release/coastal-recreational-bottomfish-fishery-season-opens-march-14-1', 'WDFW — Coastal recreational bottomfish fishery season opens March 14 (news release)', '2026-03-05', '2026-09-02', 1,
   '2026-01-01', '2026-12-31', null, null, null, null, null, 'boat', null, true, 30),
  (null, 'wa-bottomfish', 'wa-ma4-east', 'salt', 'bag_limit', 'Daily aggregate limit is nine bottomfish and includes a sub-limit of seven black, blue/deacon, yellowtail, and widow rockfishes (retention of other rockfish species is prohibited), two lingcod, and one cabezon per angler with no minimum size restriction.', 'https://wdfw.wa.gov/newsroom/news-release/coastal-recreational-bottomfish-fishery-season-opens-march-14-1', 'WDFW — Coastal recreational bottomfish fishery season opens March 14 (news release)', '2026-03-05', '2026-09-02', 1,
   '2026-01-01', '2026-12-31', 9, null, null, null, null, null, null, true, 30),
  (null, 'wa-ma4-east-rockfish', 'wa-ma4-east', 'salt', 'bag_limit', 'Daily aggregate limit is nine bottomfish and includes a sub-limit of seven black, blue/deacon, yellowtail, and widow rockfishes (retention of other rockfish species is prohibited), two lingcod, and one cabezon per angler with no minimum size restriction.', 'https://wdfw.wa.gov/newsroom/news-release/coastal-recreational-bottomfish-fishery-season-opens-march-14-1', 'WDFW — Coastal recreational bottomfish fishery season opens March 14 (news release)', '2026-03-05', '2026-09-02', 1,
   '2026-01-01', '2026-12-31', 7, null, null, null, null, null, null, true, 30),
  ('lingcod', null, 'wa-ma4-east', 'salt', 'season', 'Marine Area 4 (Neah Bay east of Bonilla-Tatoosh boundary line) is open year-round. Lingcod fishing is open from March 14 through Oct. 17.', 'https://wdfw.wa.gov/newsroom/news-release/coastal-recreational-bottomfish-fishery-season-opens-march-14-1', 'WDFW — Coastal recreational bottomfish fishery season opens March 14 (news release)', '2026-03-05', '2026-09-02', 1,
   '2026-03-14', '2026-10-17', null, null, null, null, null, null, null, true, 30),
  ('lingcod', null, 'wa-ma4-east', 'salt', 'bag_limit', 'Daily aggregate limit is nine bottomfish and includes a sub-limit of seven black, blue/deacon, yellowtail, and widow rockfishes (retention of other rockfish species is prohibited), two lingcod, and one cabezon per angler with no minimum size restriction.', 'https://wdfw.wa.gov/newsroom/news-release/coastal-recreational-bottomfish-fishery-season-opens-march-14-1', 'WDFW — Coastal recreational bottomfish fishery season opens March 14 (news release)', '2026-03-05', '2026-09-02', 1,
   null, null, 2, null, null, null, null, null, null, true, 30),
  ('pacific_halibut', null, 'wa-ma-1-4-coastal', 'salt', 'bag_limit', 'The bottomfish daily limit doesn’t include halibut. The daily limit for halibut is one fish with no minimum size restriction.', 'https://wdfw.wa.gov/newsroom/news-release/coastal-recreational-bottomfish-fishery-season-opens-march-14-1', 'WDFW — Coastal recreational bottomfish fishery season opens March 14 (news release)', '2026-03-05', '2026-09-02', 1,
   null, null, 1, null, null, null, null, null, null, true, 14),
  ('pacific_halibut', null, 'wa-ma-1-4-coastal', 'salt', 'note', '2026 Washington halibut (Area 2A): Puget Sound and Strait of Juan de Fuca — April 2 through June 30 and August 16 through September 30, 7 days a week. North Coast (Marine Areas 3 and 4) — Thursdays through Sundays May through June 28 per the published date table, plus August 16 through September 30, 7 days a week. South Coast (Marine Area 2) — Thursdays, Fridays, Sundays, and Tuesdays April 30 through June 30, plus August 8 through September 30, 7 days a week. Inseason closures when subarea allocations are used.', 'https://www.fisheries.noaa.gov/action/2026-pacific-halibut-recreational-fishery', 'NOAA Fisheries — 2026 Pacific Halibut Recreational Fishery (final rule, Area 2A)', '2026-05-01', '2026-09-02', 1,
   null, null, null, null, null, null, null, null, null, true, 7),
  ('surfperch', null, 'wa-ma-1-4-coastal', 'salt', 'bag_limit', 'Surfperch and shiner perch are not part of the bottomfish limit. Surfperch has a daily limit of 12 and shiner perch has a daily limit of 15 with no minimum size restriction for either species. Fishing is open on the second Saturday in March through the third Saturday in October – March 14 through Oct. 17, 2026 – except fishing for surfperch is open year-round from the beach.', 'https://wdfw.wa.gov/newsroom/news-release/coastal-recreational-bottomfish-fishery-season-opens-march-14-1', 'WDFW — Coastal recreational bottomfish fishery season opens March 14 (news release)', '2026-03-05', '2026-09-02', 1,
   null, null, 12, null, null, null, null, 'shore', null, true, 30),
  ('shiner_perch', null, 'wa-ma-1-4-coastal', 'salt', 'bag_limit', 'Surfperch has a daily limit of 12 and shiner perch has a daily limit of 15 with no minimum size restriction for either species.', 'https://wdfw.wa.gov/newsroom/news-release/coastal-recreational-bottomfish-fishery-season-opens-march-14-1', 'WDFW — Coastal recreational bottomfish fishery season opens March 14 (news release)', '2026-03-05', '2026-09-02', 1,
   null, null, 15, null, null, null, null, null, null, true, 30),
  ('sixgill_shark', null, 'wa-ma-1-4-coastal', 'salt', 'prohibited', 'Fishing for, retaining, or possessing sixgill, sevengill, and thresher sharks is closed in all marine areas. A sixgill shark may not be removed from the water.', 'https://wdfw.wa.gov/newsroom/news-release/coastal-recreational-bottomfish-fishery-season-opens-march-14-1', 'WDFW — Coastal recreational bottomfish fishery season opens March 14 (news release)', '2026-03-05', '2026-09-02', 1,
   null, null, 0, 0, null, null, null, null, null, true, 60),
  ('thresher_shark', null, 'wa-ma-1-4-coastal', 'salt', 'prohibited', 'Fishing for, retaining, or possessing sixgill, sevengill, and thresher sharks is closed in all marine areas.', 'https://wdfw.wa.gov/newsroom/news-release/coastal-recreational-bottomfish-fishery-season-opens-march-14-1', 'WDFW — Coastal recreational bottomfish fishery season opens March 14 (news release)', '2026-03-05', '2026-09-02', 1,
   null, null, 0, 0, null, null, null, null, null, true, 60);

insert into public.reg_pack (id, version, published_at, notes) values
  ('washington-2026-09-02', 1, '2026-09-02T12:00:00Z', 'Washington ocean Marine Areas 1–4 (WDFW news release March 5, 2026): 2026 coastal bottomfish aggregate 9/day (≤7 rockfish, ≤5 canary; 2 lingcod; 1 cabezon; no min sizes), copper/quillback/vermilion possession prohibited May–July, yelloweye prohibited year-round, descending device mandatory on boats, surfperch 12 / shiner 15, halibut 1/day per the federal Area 2A plan. Marine Areas 5–13 (Puget Sound) and salmon/shellfish not yet shipped.')
on conflict (id) do update set version = excluded.version, notes = excluded.notes;
