-- Alaska broaden v2 (2026-09-02): North Gulf Coast (2026 Southcentral book) and
-- Kodiak Island / Alaska Peninsula / Aleutian Islands salt water (2026 Southwest book).
-- GENERATED from the bundle via gen-ak-broaden-v2.mts. Insert-only + pack upsert.

insert into public.reg_area (id, authority, kind, name, parent_id, boundary_geojson, source_url, verified_at, notes) values
  ('ak-ngc', 'adfg', 'ocean_region', 'North Gulf Coast — within 200 miles of shore, Cape Fairfield to Gore Point (incl. Seward / North Gulf Coast fleet)', null, '[[-152.5,58.7],[-149.2,59.9],[-148.3,60.35],[-147.4,60],[-147.5,59.2],[-149.4,58.8],[-152.5,58.7]]', 'https://www.adfg.alaska.gov/static/regulations/fishregulations/PDFs/southcentral/2026sc_sfregs_north_gulf_coast.pdf', '2026-09-02', 'Envelope between the longitudes of Gore Point (~152° W) and Cape Fairfield (~147.5° W). ADF&G wording: within 200 miles of shore between those longitudes.'),
  ('ak-res-bay', 'adfg', 'ocean_region', 'Resurrection Bay saltwaters (north of the Cape Resurrection–Aialik Cape line)', null, '[[-149.55,59.85],[-149.35,60.05],[-149.15,60.15],[-149.05,59.95],[-149.3,59.75],[-149.55,59.85]]', 'https://www.adfg.alaska.gov/static/regulations/fishregulations/PDFs/southcentral/2026sc_sfregs_north_gulf_coast.pdf', '2026-09-02', 'Lingcod closed year-round in the bay; king salmon seasons split on Aug 31.'),
  ('ak-kodiak', 'adfg', 'ocean_region', 'Kodiak Island, Alaska Peninsula & Aleutian Islands salt waters (Southwest general)', null, '[[-154.9,57],[-151.9,57.6],[-151.85,58.1],[-153,58.6],[-154.6,58.4],[-155.4,57.4],[-154.9,57]]', 'https://www.adfg.alaska.gov/static/regulations/fishregulations/PDFs/Southwest/2026sw_sfregs_kodiak_akpen_aleutian_salt.pdf', '2026-09-02', 'Envelope of waters circumjacent to Kodiak Island; API (Alaska Peninsula/Aleutian Islands) coastal remainder follows the same 2026 general table except where noted. 2026s are emergency-order series (kings 1/day Apr 1-Sep 15 island-wide, eelgrass belt rockfish grid).'),
  ('ak-kodiak-north-belt', 'adfg', 'ocean_region', 'Kodiak north belt (west of Afognak n. of Cape Ikolik; east n. of Dangerous Cape; stats areas 525701/525702)', null, '[[-153.4,57.29],[-152.8,58],[-152.3,57.9],[-152.7,57.35],[-153.4,57.29]]', 'https://www.adfg.alaska.gov/static/regulations/fishregulations/PDFs/Southwest/2026sw_sfregs_kodiak_akpen_aleutian_salt.pdf', '2026-09-02', '2026 EO belt. Rockfish: 5/day 10 poss; ≤2 of a single species; ≤1 yelloweye; ≤1 black.'),
  ('ak-kodiak-afognak-north', 'adfg', 'ocean_region', 'Afognak & Shuyak Islands north of Tonki Cape (58°21.181''N) and Black Cape (58°24.583''N)', null, '[[-153.1,58.35],[-152.5,58.6],[-152.2,58.4],[-152.8,58.21],[-153.1,58.35]]', 'https://www.adfg.alaska.gov/static/regulations/fishregulations/PDFs/Southwest/2026sw_sfregs_kodiak_akpen_aleutian_salt.pdf', '2026-09-02', '2026 EO: rockfish 3/day ≤1 of a single species; lingcod 1/day ≥35 in (season Jul 1–Dec 31).')
on conflict (id) do nothing;

insert into public.reg_rule
  (species_id, reg_group_id, reg_area_id, water_class, kind, verbatim, source_url, source_title, source_updated_at, verified_at, pack_version,
   season_start, season_end, bag_daily, possession_limit, min_size_in, max_size_in, size_measure, platform_scope, depth_note, check_inseason, stale_after_days)
values
  (null, null, 'ak-ngc', 'salt', 'note', 'North Gulf Coast saltwaters: within 200 miles of shore from the longitude of Gore Point to the longitude of Cape Fairfield. Fishing is open year-round for all species unless otherwise noted. Snagging is legal year-round in all North Gulf Coast saltwaters. Gaffs may not be used to puncture any fish intended or required to be released. Stay legal — before you cast, check emergency orders at www.adfg.alaska.gov/sf/EONR. ATTENTION SALT WATER ANGLERS: Anglers must carry a deepwater release device onboard their vessel when sport fishing in salt water and will be required to use the device to release rockfish that are not harvested at depth of capture or 100 feet.', 'https://www.adfg.alaska.gov/static/regulations/fishregulations/PDFs/southcentral/2026sc_sfregs_north_gulf_coast.pdf', 'ADF&G — 2026 Southcentral Alaska Sport Fishing Regulations Summary Book (North Gulf Coast, Salt Water general & special regulations)', null, '2026-09-02', 2,
   null, null, null, null, null, null, null, null, null, true, 30),
  ('pacific_halibut', null, 'ak-ngc', 'salt', 'season', 'Pacific halibut: Feb. 1-Dec. 31. Unguided anglers: 2 per day, 4 in possession. Consult federal regulations for bag, possession and size limits and other regulations for guided (charter) anglers.', 'https://www.adfg.alaska.gov/static/regulations/fishregulations/PDFs/southcentral/2026sc_sfregs_north_gulf_coast.pdf', 'ADF&G — 2026 Southcentral Alaska Sport Fishing Regulations Summary Book (North Gulf Coast, Salt Water general & special regulations)', null, '2026-09-02', 2,
   '2026-02-01', '2026-12-31', 2, 4, null, null, null, null, null, true, 14),
  ('pacific_halibut', null, 'ak-ngc', 'salt', 'season', 'Pacific halibut: Feb. 1-Dec. 31 (January 1-31 closed; season opens February 1).', 'https://www.adfg.alaska.gov/static/regulations/fishregulations/PDFs/southcentral/2026sc_sfregs_north_gulf_coast.pdf', 'ADF&G — 2026 Southcentral Alaska Sport Fishing Regulations Summary Book (North Gulf Coast, Salt Water general & special regulations)', null, '2026-09-02', 2,
   '2026-01-01', '2026-01-31', 0, null, null, null, null, null, null, true, 14),
  ('chinook_salmon', null, 'ak-res-bay', 'salt', 'bag_limit', 'King salmon — Saltwaters: Resurrection Bay (North of line between Cape Resurrection to Aialik Cape): Sept. 1-Apr. 30: 1 per day, 1 in possession, no size limit. (Split into two rows because the window wraps the year.)', 'https://www.adfg.alaska.gov/static/regulations/fishregulations/PDFs/southcentral/2026sc_sfregs_north_gulf_coast.pdf', 'ADF&G — 2026 Southcentral Alaska Sport Fishing Regulations Summary Book (North Gulf Coast, Salt Water general & special regulations)', null, '2026-09-02', 2,
   '2026-09-01', '2026-12-31', 1, 1, null, null, null, null, null, true, 14),
  ('chinook_salmon', null, 'ak-res-bay', 'salt', 'bag_limit', 'King salmon — Saltwaters: Resurrection Bay (North of line between Cape Resurrection to Aialik Cape): Sept. 1-Apr. 30: 1 per day, 1 in possession, no size limit. (Split into two rows because the window wraps the year.)', 'https://www.adfg.alaska.gov/static/regulations/fishregulations/PDFs/southcentral/2026sc_sfregs_north_gulf_coast.pdf', 'ADF&G — 2026 Southcentral Alaska Sport Fishing Regulations Summary Book (North Gulf Coast, Salt Water general & special regulations)', null, '2026-09-02', 2,
   '2026-01-01', '2026-04-30', 1, 1, null, null, null, null, null, true, 14),
  ('chinook_salmon', null, 'ak-res-bay', 'salt', 'bag_limit', 'King salmon — Saltwaters: Resurrection Bay (North of line between Cape Resurrection to Aialik Cape): May 1-Aug. 31: 2 per day, 2 in possession, no size limit.', 'https://www.adfg.alaska.gov/static/regulations/fishregulations/PDFs/southcentral/2026sc_sfregs_north_gulf_coast.pdf', 'ADF&G — 2026 Southcentral Alaska Sport Fishing Regulations Summary Book (North Gulf Coast, Salt Water general & special regulations)', null, '2026-09-02', 2,
   '2026-05-01', '2026-08-31', 2, 2, null, null, null, null, null, true, 14),
  ('chinook_salmon', null, 'ak-ngc', 'salt', 'bag_limit', 'King salmon — Saltwaters: Outside of Resurrection Bay: Open year-round: 1 per day, 1 in possession, no size limit.', 'https://www.adfg.alaska.gov/static/regulations/fishregulations/PDFs/southcentral/2026sc_sfregs_north_gulf_coast.pdf', 'ADF&G — 2026 Southcentral Alaska Sport Fishing Regulations Summary Book (North Gulf Coast, Salt Water general & special regulations)', null, '2026-09-02', 2,
   null, null, 1, 1, null, null, null, null, null, true, 14),
  (null, 'akse-4salmon', 'ak-res-bay', 'salt', 'bag_limit', 'Chum, coho, pink, & sockeye salmon (combo) — Saltwaters: Resurrection Bay: Open year-round: 6 per day, 6 in possession, no size limit. All 6 may be coho salmon. Pink salmon taken in the sport fishery may be used as bait, but are part of your bag limit. Pink salmon used as bait must not be alive.', 'https://www.adfg.alaska.gov/static/regulations/fishregulations/PDFs/southcentral/2026sc_sfregs_north_gulf_coast.pdf', 'ADF&G — 2026 Southcentral Alaska Sport Fishing Regulations Summary Book (North Gulf Coast, Salt Water general & special regulations)', null, '2026-09-02', 2,
   null, null, 6, 6, null, null, null, null, null, true, 14),
  (null, 'akse-4salmon', 'ak-ngc', 'salt', 'bag_limit', 'Chum, coho, pink, & sockeye salmon (combo) — Saltwaters: Outside of Resurrection Bay: Open year-round: 6 per day, 6 in possession, no size limit. Only 3 per day, 3 in possession may be coho salmon. It is illegal to fish for species in these waters with more than 3 coho salmon in your possession.', 'https://www.adfg.alaska.gov/static/regulations/fishregulations/PDFs/southcentral/2026sc_sfregs_north_gulf_coast.pdf', 'ADF&G — 2026 Southcentral Alaska Sport Fishing Regulations Summary Book (North Gulf Coast, Salt Water general & special regulations)', null, '2026-09-02', 2,
   null, null, 6, 6, null, null, null, null, 'Only 3 of the 6 may be coho.', true, 14),
  ('steelhead', null, 'ak-ngc', 'salt', 'prohibited', 'Rainbow/steelhead trout (combo): Saltwaters: Closed year-round to all rainbow/steelhead trout fishing. All rainbow/steelhead trout caught may not be removed from the water and must be released immediately.', 'https://www.adfg.alaska.gov/static/regulations/fishregulations/PDFs/southcentral/2026sc_sfregs_north_gulf_coast.pdf', 'ADF&G — 2026 Southcentral Alaska Sport Fishing Regulations Summary Book (North Gulf Coast, Salt Water general & special regulations)', null, '2026-09-02', 2,
   null, null, 0, 0, null, null, null, null, null, true, 60),
  ('dolly_varden', null, 'ak-ngc', 'salt', 'bag_limit', 'Arctic char/Dolly Varden (combo): Saltwaters: Entire North Gulf Coast: Open year-round: 5 per day, 5 in possession, no size limit.', 'https://www.adfg.alaska.gov/static/regulations/fishregulations/PDFs/southcentral/2026sc_sfregs_north_gulf_coast.pdf', 'ADF&G — 2026 Southcentral Alaska Sport Fishing Regulations Summary Book (North Gulf Coast, Salt Water general & special regulations)', null, '2026-09-02', 2,
   null, null, 5, 5, null, null, null, null, null, true, 30),
  ('lingcod', null, 'ak-res-bay', 'salt', 'prohibited', 'Lingcod — Saltwaters: Resurrection Bay (North of line between Cape Resurrection to Aialik Cape): Closed year-round to all lingcod fishing. Lingcod caught incidentally must be released immediately. You cannot legally fish for any species of fish inside Resurrection Bay if you possess a lingcod taken elsewhere.', 'https://www.adfg.alaska.gov/static/regulations/fishregulations/PDFs/southcentral/2026sc_sfregs_north_gulf_coast.pdf', 'ADF&G — 2026 Southcentral Alaska Sport Fishing Regulations Summary Book (North Gulf Coast, Salt Water general & special regulations)', null, '2026-09-02', 2,
   null, null, 0, 0, null, null, null, null, null, true, 30),
  ('lingcod', null, 'ak-ngc', 'salt', 'bag_limit', 'Lingcod — Saltwaters: Outside of Resurrection Bay: July 1-Dec. 31: 1 per day, 2 in possession, must be at least 35 inches long with head attached or 28 inches from tip of tail to front of dorsal fin with head removed.', 'https://www.adfg.alaska.gov/static/regulations/fishregulations/PDFs/southcentral/2026sc_sfregs_north_gulf_coast.pdf', 'ADF&G — 2026 Southcentral Alaska Sport Fishing Regulations Summary Book (North Gulf Coast, Salt Water general & special regulations)', null, '2026-09-02', 2,
   '2026-07-01', '2026-12-31', 1, 2, 35, null, 'total_length', null, null, true, 14),
  ('lingcod', null, 'ak-ngc', 'salt', 'season', 'Lingcod — Saltwaters: Outside of Resurrection Bay: July 1-Dec. 31 (the remaining January 1-June 30 period is closed to lingcod retention).', 'https://www.adfg.alaska.gov/static/regulations/fishregulations/PDFs/southcentral/2026sc_sfregs_north_gulf_coast.pdf', 'ADF&G — 2026 Southcentral Alaska Sport Fishing Regulations Summary Book (North Gulf Coast, Salt Water general & special regulations)', null, '2026-09-02', 2,
   '2026-01-01', '2026-06-30', 0, null, null, null, null, null, null, true, 14),
  ('rockfish', null, 'ak-ngc', 'salt', 'bag_limit', 'Rockfish: Open year-round. In 2026, by emergency order the following apply: Pelagic: 2 per day, 4 in possession. Nonpelagic: 1 per day, 2 in possession. April 1-June 30: No retention of yelloweye rockfish.', 'https://www.adfg.alaska.gov/static/regulations/fishregulations/PDFs/southcentral/2026sc_sfregs_north_gulf_coast.pdf', 'ADF&G — 2026 Southcentral Alaska Sport Fishing Regulations Summary Book (North Gulf Coast, Salt Water general & special regulations)', null, '2026-09-02', 2,
   null, null, 2, 4, null, null, null, null, '2026 EO grid: pelagic 2/day; nonpelagic 1/day; yelloweye closed Apr 1-Jun 30.', true, 14),
  ('yelloweye_rockfish', null, 'ak-ngc', 'salt', 'season', 'Rockfish 2026 emergency order: April 1-June 30: No retention of yelloweye rockfish.', 'https://www.adfg.alaska.gov/static/regulations/fishregulations/PDFs/southcentral/2026sc_sfregs_north_gulf_coast.pdf', 'ADF&G — 2026 Southcentral Alaska Sport Fishing Regulations Summary Book (North Gulf Coast, Salt Water general & special regulations)', null, '2026-09-02', 2,
   '2026-04-01', '2026-06-30', 0, null, null, null, null, null, null, true, 14),
  (null, null, 'ak-ngc', 'salt', 'note', 'Sharks except spiny dogfish: Open year-round: 1 per day, 1 in possession, no size limit. There is an annual limit of 2 sharks. Harvest record required. Spiny dogfish: 5 per day, 5 in possession, no size limit. Other finfish: no limit.', 'https://www.adfg.alaska.gov/static/regulations/fishregulations/PDFs/southcentral/2026sc_sfregs_north_gulf_coast.pdf', 'ADF&G — 2026 Southcentral Alaska Sport Fishing Regulations Summary Book (North Gulf Coast, Salt Water general & special regulations)', null, '2026-09-02', 2,
   null, null, null, null, null, null, null, null, null, true, 60),
  (null, null, 'ak-kodiak', 'salt', 'note', 'Inclusive waters: All salt waters circumjacent to Kodiak Island, the Aleutian Islands, and the Alaska Peninsula (coastline west of the longitude of Cape Douglas and Bering Sea coastline south of the latitude of Cape Menshikof). Fishing is open year-round for all species unless otherwise noted. Stay legal — before you cast, check emergency orders at www.adfg.alaska.gov/sf/EONR. Questions? Please contact the Kodiak area office at (907) 486-1880.', 'https://www.adfg.alaska.gov/static/regulations/fishregulations/PDFs/Southwest/2026sw_sfregs_kodiak_akpen_aleutian_salt.pdf', 'ADF&G — 2026 Southwest Alaska Sport Fishing Regulations Summary Book (Kodiak Island, Alaska Peninsula & Aleutian Islands salt water)', null, '2026-09-02', 2,
   null, null, null, null, null, null, null, null, null, true, 30),
  ('chinook_salmon', null, 'ak-kodiak', 'salt', 'season', 'King salmon — In 2026, in the salt waters of the southern Alaska Peninsula west to Scotch Cap on Unimak Island and waters circumjacent to Kodiak Island by emergency order: April 1-September 15: 1 per day, 1 in possession, any size. In 2026, in the westside salt waters of Kodiak Island by emergency order: May 1-June 30: Closed to king salmon fishing. (Otherwise) 2 per day, 2 in possession, no size or annual limit.', 'https://www.adfg.alaska.gov/static/regulations/fishregulations/PDFs/Southwest/2026sw_sfregs_kodiak_akpen_aleutian_salt.pdf', 'ADF&G — 2026 Southwest Alaska Sport Fishing Regulations Summary Book (Kodiak Island, Alaska Peninsula & Aleutian Islands salt water)', null, '2026-09-02', 2,
   '2026-04-01', '2026-09-15', 1, 1, null, null, null, null, 'Westside Kodiak: closed May 1-Jun 30. Outside Apr 1-Sep 15: 2/day.', true, 7),
  ('chinook_salmon', null, 'ak-kodiak-north-belt', 'salt', 'season', 'In 2026, in the westside salt waters of Kodiak Island by emergency order: May 1-June 30: Closed to king salmon fishing.', 'https://www.adfg.alaska.gov/static/regulations/fishregulations/PDFs/Southwest/2026sw_sfregs_kodiak_akpen_aleutian_salt.pdf', 'ADF&G — 2026 Southwest Alaska Sport Fishing Regulations Summary Book (Kodiak Island, Alaska Peninsula & Aleutian Islands salt water)', null, '2026-09-02', 2,
   '2026-05-01', '2026-06-30', 0, null, null, null, null, null, null, true, 7),
  (null, 'akse-4salmon', 'ak-kodiak', 'salt', 'bag_limit', 'Chum, coho, pink, & sockeye salmon (combo): Kodiak and Alaska Peninsula/Aleutian Islands Remote Zones: 5 per day, 10 in possession. Kodiak Road Zone: 5 per day, 5 in possession, only 2 of which may be sockeye salmon. January 1-September 15: Only 2 of which may be coho salmon. September 16-December 31: Only 1 of which may be a coho salmon. Unalaska Bay: 5 per day, 5 in possession, only 2 of which may be coho salmon and 2 of which may be sockeye salmon.', 'https://www.adfg.alaska.gov/static/regulations/fishregulations/PDFs/Southwest/2026sw_sfregs_kodiak_akpen_aleutian_salt.pdf', 'ADF&G — 2026 Southwest Alaska Sport Fishing Regulations Summary Book (Kodiak Island, Alaska Peninsula & Aleutian Islands salt water)', null, '2026-09-02', 2,
   null, null, 5, 10, null, null, null, null, 'Road Zone: 5/day 5 poss, ≤2 sockeye; coho ≤2 Jan 1–Sep 15, ≤1 Sep 16–Dec 31.', true, 14),
  ('steelhead', null, 'ak-kodiak', 'salt', 'bag_limit', 'Rainbow/steelhead trout: 2 per day, 2 in possession, only 1 of which may be 20 inches or longer (except Kodiak Road Zone, see page 23). There is an annual limit of 2 fish 20 inches or longer. Harvest record required.', 'https://www.adfg.alaska.gov/static/regulations/fishregulations/PDFs/Southwest/2026sw_sfregs_kodiak_akpen_aleutian_salt.pdf', 'ADF&G — 2026 Southwest Alaska Sport Fishing Regulations Summary Book (Kodiak Island, Alaska Peninsula & Aleutian Islands salt water)', null, '2026-09-02', 2,
   null, null, 2, 2, null, null, null, null, 'Annual limit 2 fish ≥20 in; harvest record required.', true, 30),
  ('dolly_varden', null, 'ak-kodiak', 'salt', 'bag_limit', 'Dolly Varden: 10 per day, 10 in possession, no size limit.', 'https://www.adfg.alaska.gov/static/regulations/fishregulations/PDFs/Southwest/2026sw_sfregs_kodiak_akpen_aleutian_salt.pdf', 'ADF&G — 2026 Southwest Alaska Sport Fishing Regulations Summary Book (Kodiak Island, Alaska Peninsula & Aleutian Islands salt water)', null, '2026-09-02', 2,
   null, null, 10, 10, null, null, null, null, null, true, 30),
  ('lingcod', null, 'ak-kodiak', 'salt', 'season', 'Lingcod: July 1-December 31: Open to lingcod fishing. Afognak and Shuyak Islands - north of the latitude of Tonki Cape (north of 58°21.181''N. lat.) and north of the latitude of Black Cape (north of 58°24.583''N. lat.), inclusive of all waters between these points by emergency order: 1 per day, 1 in possession, 35 inches or longer. Remainder of Alaska Peninsula, Aleutian Islands, and Kodiak Island: 2 per day, 4 in possession, no size limit.', 'https://www.adfg.alaska.gov/static/regulations/fishregulations/PDFs/Southwest/2026sw_sfregs_kodiak_akpen_aleutian_salt.pdf', 'ADF&G — 2026 Southwest Alaska Sport Fishing Regulations Summary Book (Kodiak Island, Alaska Peninsula & Aleutian Islands salt water)', null, '2026-09-02', 2,
   '2026-07-01', '2026-12-31', 2, 4, null, null, null, null, 'Afognak/Shuyak north of the capes: 1/day ≥35 in.', true, 14),
  ('lingcod', null, 'ak-kodiak', 'salt', 'season', 'Lingcod: July 1-December 31: Open to lingcod fishing. (January 1-June 30 closed.)', 'https://www.adfg.alaska.gov/static/regulations/fishregulations/PDFs/Southwest/2026sw_sfregs_kodiak_akpen_aleutian_salt.pdf', 'ADF&G — 2026 Southwest Alaska Sport Fishing Regulations Summary Book (Kodiak Island, Alaska Peninsula & Aleutian Islands salt water)', null, '2026-09-02', 2,
   '2026-01-01', '2026-06-30', 0, null, null, null, null, null, null, true, 14),
  ('lingcod', null, 'ak-kodiak-afognak-north', 'salt', 'bag_limit', 'Lingcod (Afognak and Shuyak Islands north of Tonki Cape 58°21.181''N and north of Black Cape 58°24.583''N, inclusive of all waters between, by emergency order): July 1-December 31: 1 per day, 1 in possession, 35 inches or longer.', 'https://www.adfg.alaska.gov/static/regulations/fishregulations/PDFs/Southwest/2026sw_sfregs_kodiak_akpen_aleutian_salt.pdf', 'ADF&G — 2026 Southwest Alaska Sport Fishing Regulations Summary Book (Kodiak Island, Alaska Peninsula & Aleutian Islands salt water)', null, '2026-09-02', 2,
   '2026-07-01', '2026-12-31', 1, 1, 35, null, 'total_length', null, null, true, 7),
  ('pacific_halibut', null, 'ak-kodiak', 'salt', 'season', 'Halibut: Pacific halibut fisheries are managed by the federal government under international treaty. February 1-December 31: Open to halibut fishing. Unguided anglers: 2 per day, 4 in possession. Consult federal regulations for bag, possession and size limits, and other regulations for guided (charter) anglers. No person shall possess on board a vessel Pacific halibut that have been filleted, mutilated, or otherwise disfigured in any manner, except that each Pacific halibut may be cut into no more than 2 ventral pieces, 2 dorsal pieces, and 2 cheek pieces, with a patch of skin on each piece, naturally attached.', 'https://www.adfg.alaska.gov/static/regulations/fishregulations/PDFs/Southwest/2026sw_sfregs_kodiak_akpen_aleutian_salt.pdf', 'ADF&G — 2026 Southwest Alaska Sport Fishing Regulations Summary Book (Kodiak Island, Alaska Peninsula & Aleutian Islands salt water)', null, '2026-09-02', 2,
   '2026-02-01', '2026-12-31', 2, 4, null, null, null, null, null, true, 14),
  ('rockfish', null, 'ak-kodiak-north-belt', 'salt', 'bag_limit', 'Rockfish — In 2026, in the salt waters of the westside of Kodiak and Afognak islands north of the latitude of Cape Ikolik and on the eastside of Kodiak and Afognak islands north of the latitude of Dangerous Cape by emergency order: 5 per day, 10 in possession, only 2 per day, 4 in possession may be a single rockfish species, only 1 per day, 2 in possession may be a yelloweye rockfish, and only 1 per day, 2 in possession may be a black rockfish.', 'https://www.adfg.alaska.gov/static/regulations/fishregulations/PDFs/Southwest/2026sw_sfregs_kodiak_akpen_aleutian_salt.pdf', 'ADF&G — 2026 Southwest Alaska Sport Fishing Regulations Summary Book (Kodiak Island, Alaska Peninsula & Aleutian Islands salt water)', null, '2026-09-02', 2,
   null, null, 5, 10, null, null, null, null, '≤2 of a single species; ≤1 yelloweye; ≤1 black.', true, 7),
  ('rockfish', null, 'ak-kodiak-afognak-north', 'salt', 'bag_limit', 'Rockfish — In 2026, in the salt waters of Afognak and Shuyak islands, north of the latitude of Tonki Cape (north of 58°21.181''N. lat.) and north of the latitude of Black Cape (north of 58°24.583''N. lat.), inclusive of all waters between these points, by emergency order: 3 per day, 3 in possession, and only 1 may be a single rockfish species.', 'https://www.adfg.alaska.gov/static/regulations/fishregulations/PDFs/Southwest/2026sw_sfregs_kodiak_akpen_aleutian_salt.pdf', 'ADF&G — 2026 Southwest Alaska Sport Fishing Regulations Summary Book (Kodiak Island, Alaska Peninsula & Aleutian Islands salt water)', null, '2026-09-02', 2,
   null, null, 3, 3, null, null, null, null, '≤1 of a single species.', true, 7),
  ('rockfish', null, 'ak-kodiak', 'salt', 'bag_limit', 'Rockfish — Remainder of Kodiak Island: 5 per day, 10 in possession, only 2 per day, 4 in possession may be nonpelagic (see page 34), only 1 per day, 2 in possession may be a yelloweye rockfish. Alaska Peninsula & Aleutian Islands: 10 per day, 20 in possession.', 'https://www.adfg.alaska.gov/static/regulations/fishregulations/PDFs/Southwest/2026sw_sfregs_kodiak_akpen_aleutian_salt.pdf', 'ADF&G — 2026 Southwest Alaska Sport Fishing Regulations Summary Book (Kodiak Island, Alaska Peninsula & Aleutian Islands salt water)', null, '2026-09-02', 2,
   null, null, 5, 10, null, null, null, null, '≤2 nonpelagic; ≤1 yelloweye. AkPen/Aleutians: 10/day, 20 poss.', true, 14),
  (null, null, 'ak-kodiak', 'salt', 'note', 'Sharks (except spiny dogfish): 1 per day, 1 in possession, no size limit. Annual limit of 2 sharks. Harvest record required. Spiny dogfish: 5 per day, 5 in possession, no size limit. Other finfish: no limit.', 'https://www.adfg.alaska.gov/static/regulations/fishregulations/PDFs/Southwest/2026sw_sfregs_kodiak_akpen_aleutian_salt.pdf', 'ADF&G — 2026 Southwest Alaska Sport Fishing Regulations Summary Book (Kodiak Island, Alaska Peninsula & Aleutian Islands salt water)', null, '2026-09-02', 2,
   null, null, null, null, null, null, null, null, null, true, 60),
  ('dungeness_crab', null, 'ak-kodiak', 'salt', 'note', 'King crab — Alaska Peninsula and Aleutian Islands (golden king crab): Males only: 6 per day, 6 in possession, 6½ inches or more (straight line distance across carapace, not including spines). Red or blue king crab may not be retained or possessed. Kodiak Area: Closed to all king crab species. Tanner crab: Males only: 6 per day, 6 in possession, 5½ inches or more (straight line distance across carapace, including spines). In a commercial Tanner crab section of the Kodiak District that will be open to a commercial Tanner crab fishery, the taking of Tanner crab is prohibited in waters 25 fathoms or more in depth during the 14 days immediately before the scheduled opening of a commercial Tanner crab fishing season in that section. Dungeness crab: Males only: 12 per day, 12 in possession, 6½ inches or more.', 'https://www.adfg.alaska.gov/static/regulations/fishregulations/PDFs/Southwest/2026sw_sfregs_kodiak_akpen_aleutian_salt.pdf', 'ADF&G — 2026 Southwest Alaska Sport Fishing Regulations Summary Book (Kodiak Island, Alaska Peninsula & Aleutian Islands salt water)', null, '2026-09-02', 2,
   null, null, 12, 12, 6.5, null, null, null, 'Males only. Golden king (AkPen/Aleutians): 6@6½in; Tanner: 6@5½in w/ 14-day pre-opener ≥25fm rule; Kodiak closed to king crab.', true, 60);

insert into public.reg_pack (id, version, published_at, notes) values
  ('alaska-2026-09-02', 2, '2026-09-02T18:00:00Z', 'Alaska — Southeast (ADF&G 2026 Region 1 summary book): saltwater year-round except halibut/lingcod/DSR/crab/shrimp. Lingcod May 16–Nov 30 w/ nonresident 30–35 in-or-55 in+ slot and 2/yr; DSR nonresidents Jul 1–Aug 25 only, annual 1; halibut closed January, unguided 2/day; pelagic 3 / slope 1 / DSR 1 rockfish regimes; deepwater release device mandatory; EEZ switches everyone to nonresident limits. Emergency orders control king salmon annually. v2 adds North Gulf Coast (Resurrection Bay closures, NGC king/salmon/lingcod/EO rockfish table) and Kodiak/Southwest (2026 EO king salmon + rockfish grid, lingcod, crab tables, halibut Feb-Dec) verbatim.')
on conflict (id) do update set version = excluded.version, notes = excluded.notes;
