-- Washington v5 (2026-09-02): Shrimp Rules page verbatim (WDFW 2026-27 book,
-- page updated 2026-06-18); no new areas — reuses wa-ma-5-13-inside, wa-ma-9/10/13,
-- and wa-ma-1-4-coastal. GENERATED via gen-wa-shrimp-v5.mts.
-- Insert-only + pack upsert to 5. Species appendix mirrors ontology additions.

insert into public.species (id, common_name, scientific_name, is_group, rolls_up_to, water_class, take_status, sort_order, needs_review) values
  ('spot_shrimp', 'Spot shrimp', 'Pandalus platyceros', false, null, 'salt', 'regulated', 492, false),
  ('coonstripe_shrimp', 'Coonstripe shrimp (dock/humpback)', 'Pandalus danae / P. hypsinotus', false, null, 'salt', 'regulated', 493, false),
  ('pink_shrimp', 'Pink shrimp', 'Pandalus eous / P. jordani', false, null, 'salt', 'regulated', 494, false)
on conflict (id) do nothing;

insert into public.reg_rule
  (species_id, reg_group_id, reg_area_id, water_class, kind, verbatim, source_url, source_title, source_updated_at, verified_at, pack_version,
   season_start, season_end, bag_daily, possession_limit, min_size_in, max_size_in, size_measure, platform_scope, depth_note, check_inseason, stale_after_days)
values
  ('spot_shrimp', null, 'wa-ma-5-13-inside', 'salt', 'bag_limit', 'Puget Sound (Marine Areas 5-13 and Marine Area 4 east of the Bonilla-Tatoosh line): Daily limit of 80 spot shrimp. Daily limit of 10 pounds, heads and tails, of all shrimp species combined (maximum of 80 spot shrimp — if open for spot shrimp). First opening date will occur in May.', 'https://www.eregulations.com/washington/fishing/shrimp-rules', 'WDFW — 2026-2027 Washington Sport Fishing Rules (Shrimp Rules)', '2026-06-18', '2026-09-02', 5,
   null, null, 80, null, null, null, null, null, 'Capped inside a 10-lb all-species combined daily limit; first opening occurs in May (dates announced late March/early April).', true, 7),
  (null, null, 'wa-ma-5-13-inside', 'salt', 'gear', 'Shrimp (Puget Sound): minimum mesh size for shrimp pots is 1" mesh. June 1 through October 15: minimum mesh is 1", unless the area is closed for spot shrimp but open for coonstripe and pink shrimp, then minimum mesh is ½"; in those areas all spot shrimp caught must be returned to the water immediately. If retaining non-spot shrimp, all shrimp heads (spot and non-spot) must be retained in the field until ashore and finished fishing for the day. All Areas: each harvester must have a separate container for their catch; no minimum carapace size; maximum of two shrimp pots per person, no more than four shrimp pots per boat.', 'https://www.eregulations.com/washington/fishing/shrimp-rules', 'WDFW — 2026-2027 Washington Sport Fishing Rules (Shrimp Rules)', '2026-06-18', '2026-09-02', 5,
   null, null, null, null, null, null, null, null, null, true, 30),
  (null, null, 'wa-ma-5-13-inside', 'salt', 'season', 'Marine Areas 4 (east of Bonilla-Tatoosh line), 5, 6, 7 East, 7 South, 7 West, 8-1, 8-2, 9, 10, 11, 12, Discovery Bay Shrimp Area: For shrimp season open dates and times go to wdfw.wa.gov/fishing/shellfishing-regulations/shrimp/areas. The dates for the upcoming 2027 season will be announced and available in late March or early April to accommodate co-management obligations, account for extreme tides, and complete pre-season test fishing and quota setting. Discovery Bay Shrimp Area: waters south of a line from McCurdy Point on the Quimper Peninsula to the northern tip of Protection Island then to Rocky Point on the Miller Peninsula and all waters of Discovery Bay.', 'https://www.eregulations.com/washington/fishing/shrimp-rules', 'WDFW — 2026-2027 Washington Sport Fishing Rules (Shrimp Rules)', '2026-06-18', '2026-09-02', 5,
   null, null, null, null, null, null, null, null, null, true, 7),
  ('spot_shrimp', null, 'wa-ma-5-13-inside', 'salt', 'prohibited', 'During 2026 Marine Areas 8-1, 8-2, 9, 10, 11, and 13 have been CLOSED to spot shrimp harvest.', 'https://www.eregulations.com/washington/fishing/shrimp-rules', 'WDFW — 2026-2027 Washington Sport Fishing Rules (Shrimp Rules)', '2026-06-18', '2026-09-02', 5,
   null, null, 0, 0, null, null, null, null, 'Spot closed (2026 book year) in 8-1/8-2/9/10/11/13; coonstripe + pink stay open there — ½" mesh + immediate spot release rules apply.', true, 7),
  ('spot_shrimp', null, 'wa-ma-9', 'salt', 'prohibited', 'During 2026 Marine Areas 8-1, 8-2, 9, 10, 11, and 13 have been CLOSED to spot shrimp harvest.', 'https://www.eregulations.com/washington/fishing/shrimp-rules', 'WDFW — 2026-2027 Washington Sport Fishing Rules (Shrimp Rules)', '2026-06-18', '2026-09-02', 5,
   null, null, 0, 0, null, null, null, null, null, true, 7),
  ('spot_shrimp', null, 'wa-ma-10', 'salt', 'prohibited', 'During 2026 Marine Areas 8-1, 8-2, 9, 10, 11, and 13 have been CLOSED to spot shrimp harvest.', 'https://www.eregulations.com/washington/fishing/shrimp-rules', 'WDFW — 2026-2027 Washington Sport Fishing Rules (Shrimp Rules)', '2026-06-18', '2026-09-02', 5,
   null, null, 0, 0, null, null, null, null, null, true, 7),
  ('spot_shrimp', null, 'wa-ma-13', 'salt', 'prohibited', 'During 2026 Marine Areas 8-1, 8-2, 9, 10, 11, and 13 have been CLOSED to spot shrimp harvest.', 'https://www.eregulations.com/washington/fishing/shrimp-rules', 'WDFW — 2026-2027 Washington Sport Fishing Rules (Shrimp Rules)', '2026-06-18', '2026-09-02', 5,
   null, null, 0, 0, null, null, null, null, null, true, 7),
  (null, null, 'wa-ma-1-4-coastal', 'salt', 'bag_limit', 'Pacific Ocean (Marine Areas 1-3 and Marine Area 4 west of the Bonilla-Tatoosh line): Daily limit of 25 pounds, heads and tails, of all shrimp species combined (maximum of 200 spot shrimp). Shrimp heads may be removed, but must be retained while in the field, until ashore and finished fishing for the day. The minimum mesh size for shrimp pots is 1" mesh.', 'https://www.eregulations.com/washington/fishing/shrimp-rules', 'WDFW — 2026-2027 Washington Sport Fishing Rules (Shrimp Rules)', '2026-06-18', '2026-09-02', 5,
   null, null, null, null, null, null, null, null, '25 lb combined (heads+tails); spot component capped at 200 individuals.', true, 30),
  ('spot_shrimp', null, 'wa-ma-1-4-coastal', 'salt', 'season', 'Pacific Ocean Marine Areas 1-3 and 4 (west of Bonilla-Tatoosh line) — All Species: Year-round. Open daily. Note: Pacific Ocean shrimp grounds are located a considerable distance from shore (30 miles or more) and as a result are generally inaccessible by the casual sport fisher.', 'https://www.eregulations.com/washington/fishing/shrimp-rules', 'WDFW — 2026-2027 Washington Sport Fishing Rules (Shrimp Rules)', '2026-06-18', '2026-09-02', 5,
   null, null, null, null, null, null, null, 'boat', 'Grounds 30+ mi offshore.', false, 60),
  ('spot_shrimp', null, 'wa-ma-1-4-coastal', 'salt', 'bag_limit', 'Pacific Ocean (Marine Areas 1-3 and Marine Area 4 west of the Bonilla-Tatoosh line): Daily limit of 25 pounds, heads and tails, of all shrimp species combined — maximum of 200 spot shrimp.', 'https://www.eregulations.com/washington/fishing/shrimp-rules', 'WDFW — 2026-2027 Washington Sport Fishing Rules (Shrimp Rules)', '2026-06-18', '2026-09-02', 5,
   null, null, 200, null, null, null, null, null, 'Spot component cap inside the 25-lb combined limit.', true, 30);

insert into public.reg_pack (id, version, published_at, notes) values
  ('washington-2026-09-02', 5, '2026-09-02T12:00:00Z', 'Washington ocean Marine Areas 1-4 (WDFW news release March 5, 2026) — v2 deepens with the inside-waters doctrine (no rockfish 6-13, barbless hooks 5-13), Puget Sound halibut windows (1/day, 6/yr, catch record card), the North Coast 20-fathom retention list, the C-shaped yelloweye conservation area, wolf-eel closure, and the five-additional-flatfish rule. v3 lands the Puget Sound pamphlet tables for Marine Areas 9, 10 and 13 verbatim (2026-27 book, updated June 18 2026): 15 bottomfish daily, >120ft fishing prohibited, descending device required, lingcod May 1-Jun 15 slot 26-36 in (spear May 21-Jun 15, hook-and-line from May 1), cabezon May 1-Nov 30 @18 in @1, rockfish closed, cod/pollock/hake/wolf-eel closed, salmon headline windows as notes. v4 lands the Crab Rules page verbatim: Puget Sound (Dungeness 5 @ 6.25 in males hardshell / Red Rock 6 @ 5 in / Tanner 6 @ 4.5 in; CRC + endorsement; MA12 south of Ayock Point + MA13 closed to crab in 2026), Pacific Ocean (Dungeness 6 @ 6 in + Red Rock 6 @ 5 in; pot window Dec 1-Sep 15, year-round other gear; Willapa Bay pots Nov 15-Sep 15), Columbia River estuary (Dungeness 12 @ 5.75 in, year-round all gear), European green crab report-and-release. v5 lands the Shrimp Rules page verbatim: Puget Sound 80 spot shrimp/day cap inside a 10-lb all-species combined limit with 2026 spot closures (MA 8-1/8-2/9/10/11/13) as prohibited rows; Pacific Ocean 25-lb combined (max 200 spot, year-round); mesh/head-retention/pot-count gear doctrine.')
on conflict (id) do update set version = excluded.version, notes = excluded.notes;
