-- Wave 4 v1 (24-state expansion, 2026-09-02): Alaska Southeast (ADF&G) and Hawaii
-- (DLNR DAR) packs. GENERATED from the bundles via gen-wave4-ak-hi.mts.
-- Insert-only; older migrations are history and stay frozen.

insert into public.species (id, common_name, scientific_name, is_group, rolls_up_to, water_class, take_status, sort_order, needs_review) values
  ('pink_salmon', 'Pink salmon (humpy)', 'Oncorhynchus gorbuscha', false, null, 'salt', 'regulated', 471, false),
  ('chum_salmon', 'Chum salmon', 'Oncorhynchus keta', false, null, 'salt', 'regulated', 472, false),
  ('sockeye_salmon', 'Sockeye salmon', 'Oncorhynchus nerka', false, null, 'salt', 'regulated', 473, false),
  ('dolly_varden', 'Dolly Varden', 'Salvelinus malma', false, null, 'salt', 'open', 474, false),
  ('moi', 'Moi (Pacific threadfin)', 'Polydactylus sexfilis', false, null, 'salt', 'regulated', 475, false),
  ('oio_bonefish', '''O''io (Hawaiian bonefish)', 'Albula virgata', false, null, 'salt', 'regulated', 476, false),
  ('awa', 'Awa (milkfish)', 'Chanos chanos', false, null, 'salt', 'regulated', 477, false),
  ('aholehole', 'Aholehole (Hawaiian flagtail)', 'Kuhlia sandvicensis', false, null, 'salt', 'regulated', 478, false),
  ('uhu', 'Uhu (parrotfish)', 'Scaridae', true, null, 'salt', 'regulated', 479, false),
  ('weke', 'Weke (yellowstripe goatfish)', 'Mulloidichthys flavolineatus', false, null, 'salt', 'regulated', 480, false),
  ('kole', 'Kole (goldring surgeonfish)', 'Ctenochaetus strigosus', false, null, 'salt', 'regulated', 481, false),
  ('manini', 'Manini (convict tang)', 'Acanthurus triostegus', false, null, 'salt', 'regulated', 482, false),
  ('kala', 'Kala (bluespine unicornfish)', 'Naso unicornis', false, null, 'salt', 'regulated', 483, false),
  ('onaga', 'Onaga (''ula''ula koa''e)', 'Etelis coruscans', false, null, 'salt', 'regulated', 484, false),
  ('opakapaka', '''Opakapaka', 'Etelis carbunculus', false, null, 'salt', 'regulated', 485, false),
  ('ehu', 'Ehu (''ula''ula)', 'Etelis marshalli', false, null, 'salt', 'regulated', 486, false),
  ('hapuu', 'Hapu''u (Hawaiian grouper)', 'Epinephelus quernus', false, null, 'salt', 'regulated', 487, false)
on conflict (id) do nothing;

insert into public.reg_area (id, authority, kind, name, parent_id, boundary_geojson, source_url, verified_at, notes) values
  ('ak-se-state', 'adfg', 'ocean_region', 'Southeast Alaska — state waters (Cape Fairweather to Dixon Entrance, shoreline to 3 nm)', null, '[[-139.3,57.4],[-136.8,56.4],[-135.9,58],[-136.5,59.4],[-139,59.9],[-139.4,59.6],[-139.3,57.4]]', 'https://www.adfg.alaska.gov/static/regulations/fishregulations/PDFs/southeast/2026se_sfregs_general_freshwater_saltwater.pdf', '2026-09-02', 'Envelope of the Southeast saltwater general area. State waters run shoreline to 3 nautical miles; beyond that is the EEZ — see the EEZ doctrine row. Management-area exceptions (Juneau/Glacier Bay, Sitka, Petersburg/Wrangell, Ketchikan) live in the booklet''s special section — not shipped yet.'),
  ('ak-se-eez', 'adfg', 'ocean_region', 'Southeast Alaska — EEZ (3–200 nautical miles offshore)', null, null, 'https://www.adfg.alaska.gov/static/regulations/fishregulations/PDFs/southeast/2026se_sfregs_general_freshwater_saltwater.pdf', '2026-09-02', 'Marker area: ADF&G''s booklet applies NONRESIDENT bag/possession/annual limits and nonresident lingcod size limits to all anglers in the EEZ.')
on conflict (id) do nothing;

insert into public.reg_group (id, name, member_species_ids, source_url, verified_at) values
  ('akse-4salmon', 'Chum, coho, pink & sockeye salmon (16 inches or longer)', '["chum_salmon","coho_salmon","pink_salmon","sockeye_salmon"]', 'https://www.adfg.alaska.gov/static/regulations/fishregulations/PDFs/southeast/2026se_sfregs_general_freshwater_saltwater.pdf', '2026-09-02'),
  ('akse-pelagic-rockfish', 'Pelagic rockfish (black, dark, deacon, dusky, widow, yellowtail)', '["black_rockfish","widow_rockfish","yellowtail_rockfish"]', 'https://www.adfg.alaska.gov/static/regulations/fishregulations/PDFs/southeast/2026se_sfregs_general_freshwater_saltwater.pdf', '2026-09-02'),
  ('akse-slope-rockfish', 'Slope rockfish (nonpelagic; incl. blue, bocaccio, vermilion, …)', '["blue_rockfish","bocaccio","vermilion_rockfish"]', 'https://www.adfg.alaska.gov/static/regulations/fishregulations/PDFs/southeast/2026se_sfregs_general_freshwater_saltwater.pdf', '2026-09-02'),
  ('akse-dsr', 'Demersal shelf rockfish (canary, China, copper, quillback, rosethorn, tiger, yelloweye)', '["canary_rockfish","copper_rockfish","quillback_rockfish","yelloweye_rockfish"]', 'https://www.adfg.alaska.gov/static/regulations/fishregulations/PDFs/southeast/2026se_sfregs_general_freshwater_saltwater.pdf', '2026-09-02')
on conflict (id) do nothing;

insert into public.reg_rule
  (species_id, reg_group_id, reg_area_id, water_class, kind, verbatim, source_url, source_title, source_updated_at, verified_at, pack_version,
   season_start, season_end, bag_daily, possession_limit, min_size_in, max_size_in, size_measure, platform_scope, depth_note, check_inseason, stale_after_days)
values
  (null, null, 'ak-se-state', 'salt', 'note', 'The salt water sport fishing season is open year-round for all species, except for halibut, lingcod, demersal shelf rockfish, Tanner crab, shrimp, and resident king crab fisheries, and unless otherwise noted below or in special regulations. Stay legal — before you cast, check emergency orders at www.adfg.alaska.gov/sf/EONR.', 'https://www.adfg.alaska.gov/static/regulations/fishregulations/PDFs/southeast/2026se_sfregs_general_freshwater_saltwater.pdf', 'ADF&G — 2026 Southeast Alaska Sport Fishing Regulations Summary Book (General Regulations: Salt Water)', null, '2026-09-02', 1,
   null, null, null, null, null, null, null, null, null, true, 30),
  (null, null, 'ak-se-state', 'salt', 'note', 'Other fish species not listed on pages 10-13: No bag, possession, annual, or size limits.', 'https://www.adfg.alaska.gov/static/regulations/fishregulations/PDFs/southeast/2026se_sfregs_general_freshwater_saltwater.pdf', 'ADF&G — 2026 Southeast Alaska Sport Fishing Regulations Summary Book (General Regulations: Salt Water)', null, '2026-09-02', 1,
   null, null, null, null, null, null, null, null, null, false, 120),
  ('chinook_salmon', null, 'ak-se-state', 'salt', 'note', 'King salmon — Southeast Alaska salt water: 28 inches or longer: Bag, possession, annual, and size limits are established annually by an emergency order, as specified in the Southeast Alaska King Salmon Management Plan. Nonresidents: A harvest record is required. Charter operators and their crew are prohibited from keeping king salmon while clients are on board.', 'https://www.adfg.alaska.gov/static/regulations/fishregulations/PDFs/southeast/2026se_sfregs_general_freshwater_saltwater.pdf', 'ADF&G — 2026 Southeast Alaska Sport Fishing Regulations Summary Book (General Regulations: Salt Water)', null, '2026-09-02', 1,
   null, null, null, null, null, null, null, null, null, true, 7),
  ('chinook_salmon', null, 'ak-se-state', 'salt', 'prohibited', 'King salmon — Southeast Alaska salt water: Less than 28 inches: Retention prohibited.', 'https://www.adfg.alaska.gov/static/regulations/fishregulations/PDFs/southeast/2026se_sfregs_general_freshwater_saltwater.pdf', 'ADF&G — 2026 Southeast Alaska Sport Fishing Regulations Summary Book (General Regulations: Salt Water)', null, '2026-09-02', 1,
   null, null, 0, 0, 28, null, 'total_length', null, null, true, 7),
  (null, 'akse-4salmon', 'ak-se-state', 'salt', 'bag_limit', 'Chum, coho, pink, & sockeye salmon — salt water: 16 inches or longer: 6 of each species per day, 12 of each species in possession. Less than 16 inches: 10 per day, 10 in possession, in combination.', 'https://www.adfg.alaska.gov/static/regulations/fishregulations/PDFs/southeast/2026se_sfregs_general_freshwater_saltwater.pdf', 'ADF&G — 2026 Southeast Alaska Sport Fishing Regulations Summary Book (General Regulations: Salt Water)', null, '2026-09-02', 1,
   null, null, 6, 12, null, null, null, null, null, true, 30),
  ('pacific_halibut', null, 'ak-se-state', 'salt', 'season', 'Halibut — Southeast Alaska salt water: January 1-January 31: Closed to halibut fishing. February 1-December 31: Open to halibut fishing.', 'https://www.adfg.alaska.gov/static/regulations/fishregulations/PDFs/southeast/2026se_sfregs_general_freshwater_saltwater.pdf', 'ADF&G — 2026 Southeast Alaska Sport Fishing Regulations Summary Book (General Regulations: Salt Water)', null, '2026-09-02', 1,
   '2026-01-01', '2026-01-31', 0, null, null, null, null, null, null, true, 30),
  ('pacific_halibut', null, 'ak-se-state', 'salt', 'bag_limit', 'Unguided anglers: 2 per day, 4 in possession, no size limit. Pacific halibut fisheries are managed by the federal government under international treaty. Possession includes unpreserved AND preserved fish for halibut. Proxy fishing for halibut is not allowed.', 'https://www.adfg.alaska.gov/static/regulations/fishregulations/PDFs/southeast/2026se_sfregs_general_freshwater_saltwater.pdf', 'ADF&G — 2026 Southeast Alaska Sport Fishing Regulations Summary Book (General Regulations: Salt Water)', null, '2026-09-02', 1,
   '2026-02-01', '2026-12-31', 2, 4, null, null, null, null, null, true, 14),
  ('pacific_halibut', null, 'ak-se-state', 'salt', 'note', 'Consult federal regulations for the following: bag, size, and possession limits for guided (charter) anglers; possession and landing requirements, and inseason changes to the regulations. Federal halibut regulations are available through NOAA Fisheries Alaska Region at (907) 586-7228. www.alaskafisheries.noaa.gov/fisheries/sport-halibut. No person shall possess on board a vessel Pacific halibut that have been filleted, mutilated, or otherwise disfigured in any manner, except that each Pacific halibut may be cut into no more than 2 ventral pieces, 2 dorsal pieces, and 2 cheek pieces, with a patch of skin on each piece, naturally attached.', 'https://www.adfg.alaska.gov/static/regulations/fishregulations/PDFs/southeast/2026se_sfregs_general_freshwater_saltwater.pdf', 'ADF&G — 2026 Southeast Alaska Sport Fishing Regulations Summary Book (General Regulations: Salt Water)', null, '2026-09-02', 1,
   null, null, null, null, null, null, null, null, null, true, 14),
  ('lingcod', null, 'ak-se-state', 'salt', 'season', 'Lingcod — Alaska Residents (All areas): May 16-November 30: Open to lingcod fishing. 1 per day, 2 in possession, no size limit.', 'https://www.adfg.alaska.gov/static/regulations/fishregulations/PDFs/southeast/2026se_sfregs_general_freshwater_saltwater.pdf', 'ADF&G — 2026 Southeast Alaska Sport Fishing Regulations Summary Book (General Regulations: Salt Water)', null, '2026-09-02', 1,
   '2026-05-16', '2026-11-30', 1, 2, null, null, null, null, null, true, 30),
  ('lingcod', null, 'ak-se-state', 'salt', 'note', 'Lingcod — Nonresidents (All areas except Yakutat area): 1 per day, 1 in possession. There is an annual limit of 2 fish, 1 that is 30-35 inches long, and 1 that is 55 inches or longer. Harvest record required. Charter operators and their crew are prohibited from keeping lingcod while clients are on board. Northern Southeast Area: May 16-June 14 and September 1-November 30. Central Southeast Outside Area: May 16-June 30 and September 1-November 30. Southern Southeast Outer Coast Area: May 16-July 31 and September 1-November 30. Southern Southeast Inside Waters Area: May 16-November 30. Yakutat Area: May 16-November 30.', 'https://www.adfg.alaska.gov/static/regulations/fishregulations/PDFs/southeast/2026se_sfregs_general_freshwater_saltwater.pdf', 'ADF&G — 2026 Southeast Alaska Sport Fishing Regulations Summary Book (General Regulations: Salt Water)', null, '2026-09-02', 1,
   null, null, null, null, null, null, null, null, null, true, 14),
  (null, 'akse-pelagic-rockfish', 'ak-se-state', 'salt', 'bag_limit', 'Pelagic rockfish includes black, dark, deacon, dusky, widow, and yellowtail. These six species are uniformly gray, green, brown, or black: 3 per day, 6 in possession, no size limit, except Sitka Area (CSEO). See page 25.', 'https://www.adfg.alaska.gov/static/regulations/fishregulations/PDFs/southeast/2026se_sfregs_general_freshwater_saltwater.pdf', 'ADF&G — 2026 Southeast Alaska Sport Fishing Regulations Summary Book (General Regulations: Salt Water)', null, '2026-09-02', 1,
   null, null, 3, 6, null, null, null, null, null, true, 30),
  (null, 'akse-slope-rockfish', 'ak-se-state', 'salt', 'bag_limit', 'Slope rockfish includes blackgill, blackspotted, blue, bocaccio, brown, chilipepper, darkblotched, greenstriped, harlequin, northern, Pacific Ocean perch, Puget Sound, pygmy, redstripe, redbanded, rougheye, sharpchin, shortbelly, shortraker, silvergray, splitnose, stripetail, vermilion, and yellowmouth: 1 per day, 2 in possession, no size limit.', 'https://www.adfg.alaska.gov/static/regulations/fishregulations/PDFs/southeast/2026se_sfregs_general_freshwater_saltwater.pdf', 'ADF&G — 2026 Southeast Alaska Sport Fishing Regulations Summary Book (General Regulations: Salt Water)', null, '2026-09-02', 1,
   null, null, 1, 2, null, null, null, null, null, true, 30),
  (null, 'akse-dsr', 'ak-se-state', 'salt', 'bag_limit', 'Demersal shelf rockfish includes canary, China, copper, quillback, rosethorn, tiger, and yelloweye. Alaska Residents: 1 per day, 2 in possession, no size limit.', 'https://www.adfg.alaska.gov/static/regulations/fishregulations/PDFs/southeast/2026se_sfregs_general_freshwater_saltwater.pdf', 'ADF&G — 2026 Southeast Alaska Sport Fishing Regulations Summary Book (General Regulations: Salt Water)', null, '2026-09-02', 1,
   null, null, 1, 2, null, null, null, null, null, true, 30),
  (null, 'akse-dsr', 'ak-se-state', 'salt', 'note', 'Demersal shelf rockfish — Nonresidents: July 1-August 25: Open to demersal shelf rockfish fishing. 1 per day, 1 in possession, no size limit. There is an annual limit of 1 fish. Harvest record required.', 'https://www.adfg.alaska.gov/static/regulations/fishregulations/PDFs/southeast/2026se_sfregs_general_freshwater_saltwater.pdf', 'ADF&G — 2026 Southeast Alaska Sport Fishing Regulations Summary Book (General Regulations: Salt Water)', null, '2026-09-02', 1,
   null, null, null, null, null, null, null, null, null, true, 14),
  ('yelloweye_rockfish', 'akse-dsr', 'ak-se-state', 'salt', 'season', 'Demersal shelf rockfish — Nonresidents: July 1-August 25: Open to demersal shelf rockfish fishing. (Outside July 1-August 25, nonresidents may not retain demersal shelf rockfish.)', 'https://www.adfg.alaska.gov/static/regulations/fishregulations/PDFs/southeast/2026se_sfregs_general_freshwater_saltwater.pdf', 'ADF&G — 2026 Southeast Alaska Sport Fishing Regulations Summary Book (General Regulations: Salt Water)', null, '2026-09-02', 1,
   '2026-07-01', '2026-08-25', null, null, null, null, null, null, null, true, 14),
  ('rockfish', null, 'ak-se-state', 'salt', 'note', 'All vessels must have at least one functional deepwater release device on board and readily available for use when sport fishing activities are taking place regardless of species targeted. All rockfish not retained must be released at the depth they were caught or 100 feet, whichever is shallower. Upon request, a deepwater release device must be presented to a local representative of ADF&G or a peace officer of the state.', 'https://www.adfg.alaska.gov/static/regulations/fishregulations/PDFs/southeast/2026se_sfregs_general_freshwater_saltwater.pdf', 'ADF&G — 2026 Southeast Alaska Sport Fishing Regulations Summary Book (General Regulations: Salt Water)', null, '2026-09-02', 1,
   null, null, null, null, null, null, null, 'boat', null, false, 120),
  ('sablefish', null, 'ak-se-state', 'salt', 'bag_limit', 'Sablefish (black cod): Alaska residents: 6 per day, 6 in possession, no size limit. Nonresidents: 4 per day, 4 in possession, no size limit. There is a 8 fish annual limit, harvest record required.', 'https://www.adfg.alaska.gov/static/regulations/fishregulations/PDFs/southeast/2026se_sfregs_general_freshwater_saltwater.pdf', 'ADF&G — 2026 Southeast Alaska Sport Fishing Regulations Summary Book (General Regulations: Salt Water)', null, '2026-09-02', 1,
   null, null, 6, 6, null, null, null, null, 'Nonresidents: 4 per day, 4 in possession, annual limit 8.', true, 30),
  (null, null, 'ak-se-state', 'salt', 'note', 'Sharks (except spiny dogfish): 1 per day, 1 in possession, no size limit. There is a 2 shark annual limit, harvest record required. Spiny dogfish: 5 per day, 5 in possession, no size limit, harvest record is NOT required.', 'https://www.adfg.alaska.gov/static/regulations/fishregulations/PDFs/southeast/2026se_sfregs_general_freshwater_saltwater.pdf', 'ADF&G — 2026 Southeast Alaska Sport Fishing Regulations Summary Book (General Regulations: Salt Water)', null, '2026-09-02', 1,
   null, null, null, null, null, null, null, null, null, true, 60),
  (null, null, 'ak-se-eez', 'salt', 'note', 'Exclusive Economic Zone waters (all saltwaters 3 to 200 nautical miles from the shoreline): Nonresident bag, possession, and annual limits apply to ALL anglers; nonresident lingcod size limits apply; nonresident seasonal closures apply; harvest record required for king salmon, lingcod, demersal shelf rockfish, sablefish, steelhead trout, and sharks. Anglers may only possess the limit of fish allowed for the specific waters they are fishing.', 'https://www.adfg.alaska.gov/static/regulations/fishregulations/PDFs/southeast/2026se_sfregs_general_freshwater_saltwater.pdf', 'ADF&G — 2026 Southeast Alaska Sport Fishing Regulations Summary Book (General Regulations: Salt Water)', null, '2026-09-02', 1,
   null, null, null, null, null, null, null, null, null, true, 30);

insert into public.reg_pack (id, version, published_at, notes) values
  ('alaska-2026-09-02', 1, '2026-09-02T18:00:00Z', 'Alaska — Southeast (ADF&G 2026 Region 1 summary book): saltwater year-round except halibut/lingcod/DSR/crab/shrimp. Lingcod May 16–Nov 30 w/ nonresident 30–35 in-or-55 in+ slot and 2/yr; DSR nonresidents Jul 1–Aug 25 only, annual 1; halibut closed January, unguided 2/day; pelagic 3 / slope 1 / DSR 1 rockfish regimes; deepwater release device mandatory; EEZ switches everyone to nonresident limits. Emergency orders control king salmon annually.')
on conflict (id) do update set version = excluded.version, notes = excluded.notes;

insert into public.reg_area (id, authority, kind, name, parent_id, boundary_geojson, source_url, verified_at, notes) values
  ('hi-statewide', 'hawaii_dar', 'ocean_region', 'Hawaii state marine waters — statewide (HAR 13-95)', null, '[[-160.3,18.7],[-159.8,20.9],[-158.1,21.7],[-156.5,20.4],[-154.8,19.5],[-155.1,18.9],[-160.3,18.7]]', 'https://dlnr.hawaii.gov/dar/fishing/fishing-regulations/marine-fishes-and-vertebrates/', '2026-09-02', 'Envelope. The statewide table rules here; one-off Regulated Fishing Areas (West Hawai''i RFMA, Miloli''i CBSFA, Hilo Bay…) may be stricter — check DLNR.'),
  ('hi-maui', 'hawaii_dar', 'conservation_area', 'Maui — HAR 13-95.1 rules', null, '[[-156.7,20.5],[-156.2,20.9],[-155.9,21],[-155.9,20.5],[-156.2,20.4],[-156.6,20.4],[-156.7,20.5]]', 'https://dlnr.hawaii.gov/dar/fishing/fishing-regulations/marine-fishes-and-vertebrates/', '2026-09-02', 'Envelope around Maui Nui waters; Maui carries its own size/bag rules.')
on conflict (id) do nothing;

insert into public.reg_group (id, name, member_species_ids, source_url, verified_at) values
  ('hi-deep7', 'Deep 7 bottomfish (onaga, ''ehu, gindai, kalekale, lehi, ''opakapaka, hapu''u)', '["onaga","opakapaka","ehu","hapuu"]', 'https://dlnr.hawaii.gov/dar/fishing/fishing-regulations/marine-fishes-and-vertebrates/', '2026-09-02'),
  ('hi-uhu-large', 'Regulated large uhu (14-inch minimum) species', '["uhu"]', 'https://dlnr.hawaii.gov/dar/fishing/fishing-regulations/marine-fishes-and-vertebrates/', '2026-09-02')
on conflict (id) do nothing;

insert into public.reg_rule
  (species_id, reg_group_id, reg_area_id, water_class, kind, verbatim, source_url, source_title, source_updated_at, verified_at, pack_version,
   season_start, season_end, bag_daily, possession_limit, min_size_in, max_size_in, size_measure, platform_scope, depth_note, check_inseason, stale_after_days)
values
  ('moi', null, 'hi-statewide', 'salt', 'bag_limit', 'Moi — Closed season June - August. Minimum size 11 inches. Bag limit 15. (HAR 13-95)', 'https://dlnr.hawaii.gov/dar/fishing/fishing-regulations/marine-fishes-and-vertebrates/', 'DLNR Division of Aquatic Resources — Marine Fishes and Other Vertebrates (HAR 13-95, 13-95.1, 13-94, 13-74)', null, '2026-09-02', 1,
   '2026-09-01', '2026-05-31', 15, null, 11, null, 'total_length', null, null, false, 180),
  ('moi', null, 'hi-statewide', 'salt', 'season', 'Moi — Closed season June - August. (HAR 13-95)', 'https://dlnr.hawaii.gov/dar/fishing/fishing-regulations/marine-fishes-and-vertebrates/', 'DLNR Division of Aquatic Resources — Marine Fishes and Other Vertebrates (HAR 13-95, 13-95.1, 13-94, 13-74)', null, '2026-09-02', 1,
   '2026-06-01', '2026-08-31', 0, null, null, null, null, null, null, false, 180),
  ('striped_mullet', null, 'hi-statewide', 'salt', 'bag_limit', '''Ama''ama (striped mullet) — Closed season December - March. Minimum size 11 inches (see measurement guide). (HAR 13-95, HRS 188-44)', 'https://dlnr.hawaii.gov/dar/fishing/fishing-regulations/marine-fishes-and-vertebrates/', 'DLNR Division of Aquatic Resources — Marine Fishes and Other Vertebrates (HAR 13-95, 13-95.1, 13-94, 13-74)', null, '2026-09-02', 1,
   '2026-04-01', '2026-11-30', null, null, 11, null, 'total_length', null, null, false, 180),
  ('striped_mullet', null, 'hi-statewide', 'salt', 'season', '''Ama''ama (striped mullet) — Closed season December - March. (HAR 13-95, HRS 188-44)', 'https://dlnr.hawaii.gov/dar/fishing/fishing-regulations/marine-fishes-and-vertebrates/', 'DLNR Division of Aquatic Resources — Marine Fishes and Other Vertebrates (HAR 13-95, 13-95.1, 13-94, 13-74)', null, '2026-09-02', 1,
   '2026-12-01', '2026-03-31', 0, null, null, null, null, null, null, false, 180),
  ('oio_bonefish', null, 'hi-statewide', 'salt', 'min_size', '''O''io — Minimum size 14 inches. (HAR 13-95)', 'https://dlnr.hawaii.gov/dar/fishing/fishing-regulations/marine-fishes-and-vertebrates/', 'DLNR Division of Aquatic Resources — Marine Fishes and Other Vertebrates (HAR 13-95, 13-95.1, 13-94, 13-74)', null, '2026-09-02', 1,
   null, null, null, null, 14, null, 'total_length', null, null, false, 180),
  ('aholehole', null, 'hi-statewide', 'salt', 'min_size', 'Aholehole — Minimum size 5 inches. (HAR 13-95)', 'https://dlnr.hawaii.gov/dar/fishing/fishing-regulations/marine-fishes-and-vertebrates/', 'DLNR Division of Aquatic Resources — Marine Fishes and Other Vertebrates (HAR 13-95, 13-95.1, 13-94, 13-74)', null, '2026-09-02', 1,
   null, null, null, null, 5, null, 'total_length', null, null, false, 180),
  ('awa', null, 'hi-statewide', 'salt', 'min_size', 'Awa — Minimum size 9 inches. (HAR 13-95)', 'https://dlnr.hawaii.gov/dar/fishing/fishing-regulations/marine-fishes-and-vertebrates/', 'DLNR Division of Aquatic Resources — Marine Fishes and Other Vertebrates (HAR 13-95, 13-95.1, 13-94, 13-74)', null, '2026-09-02', 1,
   null, null, null, null, 9, null, 'total_length', null, null, false, 180),
  ('giant_trevally', null, 'hi-statewide', 'salt', 'bag_limit', 'Ulua and papio — Minimum size 10 inches. Minimum size 16 inches for sale. Bag limit 20 (total all species, non-commercial only). (HAR 13-95)', 'https://dlnr.hawaii.gov/dar/fishing/fishing-regulations/marine-fishes-and-vertebrates/', 'DLNR Division of Aquatic Resources — Marine Fishes and Other Vertebrates (HAR 13-95, 13-95.1, 13-94, 13-74)', null, '2026-09-02', 1,
   null, null, 20, null, 10, null, 'total_length', null, null, false, 180),
  ('uhu', null, 'hi-statewide', 'salt', 'bag_limit', 'Uhu (all species, except as noted below) — Minimum size 10 inches. Bag limit 2 total all species. (HAR 13-95)', 'https://dlnr.hawaii.gov/dar/fishing/fishing-regulations/marine-fishes-and-vertebrates/', 'DLNR Division of Aquatic Resources — Marine Fishes and Other Vertebrates (HAR 13-95, 13-95.1, 13-94, 13-74)', null, '2026-09-02', 1,
   null, null, 2, null, 10, null, 'total_length', null, null, false, 180),
  ('uhu', null, 'hi-statewide', 'salt', 'note', 'Uhu ''ele''ele, uhu uliuli, uhu palukaluka, uhu ''ahu''ula — Minimum size 14 inches. Bag limit 2 (total all species). Uhu ''ele''ele and uhu uliuli: No take on Maui. (HAR 13-95, HAR 13-95.1)', 'https://dlnr.hawaii.gov/dar/fishing/fishing-regulations/marine-fishes-and-vertebrates/', 'DLNR Division of Aquatic Resources — Marine Fishes and Other Vertebrates (HAR 13-95, 13-95.1, 13-94, 13-74)', null, '2026-09-02', 1,
   null, null, null, null, 14, null, 'total_length', null, null, false, 180),
  ('uhu', null, 'hi-maui', 'salt', 'prohibited', 'Uhu ''ele''ele and uhu uliuli — No take on Maui. Large regulated uhu are 14-inch minimum, bag limit 2 total all species. (HAR 13-95.1)', 'https://dlnr.hawaii.gov/dar/fishing/fishing-regulations/marine-fishes-and-vertebrates/', 'DLNR Division of Aquatic Resources — Marine Fishes and Other Vertebrates (HAR 13-95, 13-95.1, 13-94, 13-74)', null, '2026-09-02', 1,
   null, null, 0, 0, 14, null, 'total_length', null, 'Maui: uhu ''ele''ele and uhu uliuli are no-take.', false, 180),
  ('weke', null, 'hi-statewide', 'salt', 'min_size', 'Weke and ''oama (statewide except Maui) — Minimum size 7 inches (sale). Bag limit 50 ''oama (''oama are weke under 7 inches). (HAR 13-95)', 'https://dlnr.hawaii.gov/dar/fishing/fishing-regulations/marine-fishes-and-vertebrates/', 'DLNR Division of Aquatic Resources — Marine Fishes and Other Vertebrates (HAR 13-95, 13-95.1, 13-94, 13-74)', null, '2026-09-02', 1,
   null, null, null, null, 7, null, 'total_length', null, '''Oama (under 7 in): bag limit 50.', false, 180),
  ('weke', null, 'hi-maui', 'salt', 'min_size', 'Weke ''a, weke ''ula, and ''oama (Maui rules) — Minimum size 8 inches. Bag limit 50 ''oama (''oama are weke under 8 inches). ''Oama may be taken by hook-and-line only. (HAR 13-95.1)', 'https://dlnr.hawaii.gov/dar/fishing/fishing-regulations/marine-fishes-and-vertebrates/', 'DLNR Division of Aquatic Resources — Marine Fishes and Other Vertebrates (HAR 13-95, 13-95.1, 13-94, 13-74)', null, '2026-09-02', 1,
   null, null, null, null, 8, null, 'total_length', null, '''Oama hook-and-line only on Maui.', false, 180),
  (null, null, 'hi-maui', 'salt', 'note', 'Kumu — Minimum size 12 inches (Maui rules). Bag limit 1 (Maui rules). Statewide (except Maui): minimum size 10 inches. (HAR 13-95, HAR 13-95.1) Moano kea: 12-inch minimum, bag limit 2 (Maui rules). Munu: 8-inch minimum, bag limit 2 (Maui rules). Weke nono: 12-inch minimum (Maui rules). All other goatfishes: 8-inch minimum (Maui rules).', 'https://dlnr.hawaii.gov/dar/fishing/fishing-regulations/marine-fishes-and-vertebrates/', 'DLNR Division of Aquatic Resources — Marine Fishes and Other Vertebrates (HAR 13-95, 13-95.1, 13-94, 13-74)', null, '2026-09-02', 1,
   null, null, null, null, null, null, null, null, null, false, 180),
  ('kala', null, 'hi-statewide', 'salt', 'bag_limit', 'Kala — Minimum size 14 inches. Bag limit 4. Commercial fishers may take and sell more than 4 kala per day with a permit. (HAR 13-95) Kala ''opelu: minimum size 16 inches.', 'https://dlnr.hawaii.gov/dar/fishing/fishing-regulations/marine-fishes-and-vertebrates/', 'DLNR Division of Aquatic Resources — Marine Fishes and Other Vertebrates (HAR 13-95, 13-95.1, 13-94, 13-74)', null, '2026-09-02', 1,
   null, null, 4, null, 14, null, 'total_length', null, null, false, 180),
  ('kole', null, 'hi-statewide', 'salt', 'min_size', 'Kole — Minimum size 5 inches. (HAR 13-95)', 'https://dlnr.hawaii.gov/dar/fishing/fishing-regulations/marine-fishes-and-vertebrates/', 'DLNR Division of Aquatic Resources — Marine Fishes and Other Vertebrates (HAR 13-95, 13-95.1, 13-94, 13-74)', null, '2026-09-02', 1,
   null, null, null, null, 5, null, 'total_length', null, null, false, 180),
  ('manini', null, 'hi-statewide', 'salt', 'min_size', 'Manini — Minimum size 6 inches. (HAR 13-95)', 'https://dlnr.hawaii.gov/dar/fishing/fishing-regulations/marine-fishes-and-vertebrates/', 'DLNR Division of Aquatic Resources — Marine Fishes and Other Vertebrates (HAR 13-95, 13-95.1, 13-94, 13-74)', null, '2026-09-02', 1,
   null, null, null, null, 6, null, 'total_length', null, null, false, 180),
  ('onaga', 'hi-deep7', 'hi-statewide', 'salt', 'bag_limit', '''Ula''ula koa''e (onaga) — Minimum size 1 pound (sale). Bag limit 5 (total all Deep 7 species, applies to non-commercial fishing only). (HAR 13-95, HAR 13-94, HAR 13-74) ''Opakapaka: minimum size 1 pound (sale). ''Ula''ula (ehu), kalekale, lehi, ''ukikiki (gindai), and hapu''u: bag limit 5 (total all Deep 7 species), non-commercial only.', 'https://dlnr.hawaii.gov/dar/fishing/fishing-regulations/marine-fishes-and-vertebrates/', 'DLNR Division of Aquatic Resources — Marine Fishes and Other Vertebrates (HAR 13-95, 13-95.1, 13-94, 13-74)', null, '2026-09-02', 1,
   null, null, 5, null, null, null, null, null, 'Deep 7 combined bag, non-commercial only.', false, 180),
  (null, null, 'hi-statewide', 'salt', 'prohibited', 'Paku''iku''i — Take prohibited in West Hawaii Regional Fishery Management Area through 12/17/26. (HAR 13-60.4)', 'https://dlnr.hawaii.gov/dar/fishing/fishing-regulations/marine-fishes-and-vertebrates/', 'DLNR Division of Aquatic Resources — Marine Fishes and Other Vertebrates (HAR 13-95, 13-95.1, 13-94, 13-74)', null, '2026-09-02', 1,
   null, null, 0, 0, null, null, null, null, 'West Hawaii RFMA through 2026-12-17.', true, 60),
  (null, null, 'hi-statewide', 'salt', 'prohibited', 'Mano (shark) and hihimau (ray) — Unlawful to intentionally or knowingly capture or entangle any shark or ray, whether alive or dead, or kill any shark or ray in state marine waters. (HRS 188-39.5, HRS 188-40.8)', 'https://dlnr.hawaii.gov/dar/fishing/fishing-regulations/marine-fishes-and-vertebrates/', 'DLNR Division of Aquatic Resources — Marine Fishes and Other Vertebrates (HAR 13-95, 13-95.1, 13-94, 13-74)', null, '2026-09-02', 1,
   null, null, 0, 0, null, null, null, null, null, false, 180),
  ('yellowfin_tuna', null, 'hi-statewide', 'salt', 'note', '''Ahi — Minimum size 3 pounds (sale). (HAR 13-95) No recreational bag or size limit on the DAR table.', 'https://dlnr.hawaii.gov/dar/fishing/fishing-regulations/marine-fishes-and-vertebrates/', 'DLNR Division of Aquatic Resources — Marine Fishes and Other Vertebrates (HAR 13-95, 13-95.1, 13-94, 13-74)', null, '2026-09-02', 1,
   null, null, null, null, null, null, null, null, null, false, 180),
  (null, null, 'hi-statewide', 'salt', 'note', 'Regulated Fishing Areas (West Hawaii Regional Fishery Management Area, Miloli''i Community-Based Subsistence Fishing Area, Hilo Bay, Kailua Bay, and others) carry their own permitted/prohibited lists and can be stricter than the statewide table — see DLNR DAR regulated-areas pages. Sea turtles (honu) and Hawaiian monk seals: no open season; unlawful to molest, kill, capture, or possess. (HRS 195D-4)', 'https://dlnr.hawaii.gov/dar/fishing/fishing-regulations/marine-fishes-and-vertebrates/', 'DLNR Division of Aquatic Resources — Marine Fishes and Other Vertebrates (HAR 13-95, 13-95.1, 13-94, 13-74)', null, '2026-09-02', 1,
   null, null, null, null, null, null, null, null, null, false, 180);

insert into public.reg_pack (id, version, published_at, notes) values
  ('hawaii-2026-09-02', 1, '2026-09-02T18:00:00Z', 'Hawaii (DLNR DAR statewide table): moi 11 in @ 15 closed Jun–Aug; ''ama''ama 11 in closed Dec–Mar; ''o''io 14 in; ulua/papio 10 in @ 20 non-commercial; uhu 10 in @ 2 (large uhu 14 in, no take on Maui for two); weke ''oama 7 in / 50 ''oama; kala 14 in @ 4; kole 5 in; manini 6 in; Deep 7 combined bag 5 non-commercial; Maui rules under HAR 13-95.1; sharks and rays protected in state waters (HRS 188). No recreational saltwater license required.')
on conflict (id) do update set version = excluded.version, notes = excluded.notes;
