-- PNW deepen v2 (2026-09-02): Washington v2 (inside-waters doctrine, North Coast
-- 20-fm rule, yelloweye C-area) + Oregon v2 (groundfish combos, crab/clam shellfish).
-- GENERATED from the bundles via gen-pnw-deepen-v2.mts. Insert-only; upsert packs to v2.

insert into public.species (id, common_name, scientific_name, is_group, rolls_up_to, water_class, take_status, sort_order, needs_review) values
  ('dungeness_crab', 'Dungeness crab', 'Metacarcinus magister', false, null, 'salt', 'regulated', 488, false),
  ('european_green_crab', 'European green crab (invasive)', 'Carcinus maenas', false, null, 'salt', 'regulated', 489, false),
  ('razor_clam', 'Razor clam', 'Siliqua patula', false, null, 'salt', 'regulated', 490, false)
on conflict (id) do nothing;

insert into public.reg_area (id, authority, kind, name, parent_id, boundary_geojson, source_url, verified_at, notes) values
  ('wa-ma-5-13-inside', 'wdfw', 'ocean_region', 'Marine Areas 5–13 — Puget Sound, Strait of Juan de Fuca, San Juan Islands, Hood Canal', null, '[[-123.96,49],[-123.1,48.9],[-122.8,48.45],[-122.4,48.9],[-122.3,49.15],[-123.7,49.15],[-123.96,49]]', 'https://wdfw.wa.gov/newsroom/news-release/coastal-recreational-bottomfish-fishery-season-opens-march-14-1', '2026-09-02', 'Envelope over the inside waters. v1 doctrine: rockfish are off-limits in Areas 6-13, barbless hooks required Areas 5-13. Area-by-area pamphlet tables pending.'),
  ('wa-ma-5-10-halibut', 'wdfw', 'ocean_region', 'Puget Sound & Strait of Juan de Fuca halibut (Marine Areas 5–10)', null, null, 'https://wdfw.wa.gov/newsroom/news-release/coastal-recreational-bottomfish-fishery-season-opens-march-14-1', '2026-09-02', 'Halibut subarea per WDFW''s Puget Sound page (2026 quota 80,512 lb). Shares the inside-water envelope; separate id so halibut rules don''t muddy the bottomfish area.'),
  ('wa-yrca', 'wdfw', 'conservation_area', 'Yelloweye Rockfish Conservation Area (C-shaped, off Cape Flattery)', null, '[[-125.3,48.3],[-124.9833,48.3],[-124.9833,48.1833],[-125.1833,48.1833],[-125.1833,48.0667],[-124.9833,48.0667],[-124.9833,48],[-125.3,48],[-125.3,48.3]]', 'https://wdfw.wa.gov/newsroom/news-release/coastal-recreational-bottomfish-fishery-season-opens-march-14-1', '2026-09-02', 'Closed to recreational bottomfish AND halibut fishing. Coordinates verbatim from WDFW''s North Coast page (48-18''N 125-18''W → 48-18''N 124-59''W → 48-11''N 124-59''W → 48-11''N 125-11''W → 48-04''N 125-11''W → 48-04''N 124-59''W → 48-00''N 124-59''W → 48-00''N 125-18''W → back).')
on conflict (id) do nothing;

insert into public.reg_rule
  (species_id, reg_group_id, reg_area_id, water_class, kind, verbatim, source_url, source_title, source_updated_at, verified_at, pack_version,
   season_start, season_end, bag_daily, possession_limit, min_size_in, max_size_in, size_measure, platform_scope, depth_note, check_inseason, stale_after_days)
values
  ('flatfish', null, 'wa-ma-1-4-coastal', 'salt', 'note', 'West of the Bonnilla-Tatoosh line: Recreational bottomfish is open from the second Saturday in March through the third Saturday in October, which is March 14 - October 17, 2026. Daily limit is a total of 9 bottomfish regardless of species, subject to individual limits shown below. In addition to the nine bottomfish daily limit, anglers can retain five additional flatfish. East of the Bonilla-Tatoosh line: Open year-round. In addition to the nine bottomfish daily limit, anglers can retain five additional flatfish.', 'https://wdfw.wa.gov/fishing/regulations/halibut/north-coast', 'WDFW — North coast halibut and bottomfish seasons and regulations', '2026-03-05', '2026-09-02', 2,
   null, null, 5, null, null, null, null, null, 'Five additional flatfish on top of the 9-bottomfish aggregate.', true, 30),
  (null, 'wa-bottomfish', 'wa-ma-1-4-coastal', 'salt', 'note', 'In Marine Area 3 and Marine Area 4 (west of the Bonilla-Tatoosh line) effective June 1 through July 31, recreational fishing for bottomfish is prohibited seaward of a boundary line approximating the 20-fm (120 ft.) depth contour. Beginning June 1, on days open to the Pacific halibut fishery, the following bottomfish can be retained seaward of 20 fathoms: lingcod, sablefish, Pacific cod, bocaccio, silvergray rockfish, canary rockfish, widow rockfish, and yellowtail rockfish. Yellowtail and widow rockfish retention is allowed seaward of 20 fathoms at all times during the month of July.', 'https://wdfw.wa.gov/fishing/regulations/halibut/north-coast', 'WDFW — North coast halibut and bottomfish seasons and regulations', '2026-03-05', '2026-09-02', 2,
   '2026-06-01', '2026-07-31', null, null, null, null, null, 'boat', 'Offshore of ~20 fathoms, June 1 - July 31: only the named bottomfish list may be retained.', true, 14),
  (null, 'wa-bottomfish', 'wa-yrca', 'salt', 'prohibited', 'A "C-shaped" yelloweye rockfish conservation area that is closed to recreational bottomfish and halibut fishing is defined by the following coordinates in the order listed: 48°18'' N lat, 125°18'' W long; 48°18'' N, 124°59'' W; 48°11'' N, 124°59'' W; 48°11'' N, 125°11'' W; 48°04'' N, 125°11'' W; 48°04'' N, 124°59'' W; 48°00'' N, 124°59'' W; 48°00'' N, 125°18'' W; and connecting back to 48°18'' N, 125°18'' W.', 'https://wdfw.wa.gov/fishing/regulations/halibut/north-coast', 'WDFW — North coast halibut and bottomfish seasons and regulations', '2026-03-05', '2026-09-02', 2,
   null, null, 0, 0, null, null, null, null, null, false, 120),
  (null, null, 'wa-ma-1-4-coastal', 'salt', 'prohibited', 'Wolf-eel — Closed to retention.', 'https://wdfw.wa.gov/fishing/regulations/halibut/north-coast', 'WDFW — North coast halibut and bottomfish seasons and regulations', '2026-03-05', '2026-09-02', 2,
   null, null, 0, 0, null, null, null, null, null, true, 60),
  ('rockfish', null, 'wa-ma-5-13-inside', 'salt', 'prohibited', 'Recreational anglers are reminded that it is unlawful to fish for, retain, or possess rockfish in Washington marine areas 6 through 13.', 'https://wdfw.wa.gov/fishing/regulations/halibut', 'WDFW — Recreational bottomfish and halibut fisheries page', '2026-03-05', '2026-09-02', 2,
   null, null, 0, 0, null, null, null, null, null, true, 60),
  (null, null, 'wa-ma-5-13-inside', 'salt', 'gear', 'Reminder that Barbless Hooks are required for all species in Marine Areas 5 through 13—including for halibut and bottomfish—except when using forage fish jig gear to target forage fish (herring, sandlance, anchovy, sardine and smelt).', 'https://wdfw.wa.gov/fishing/regulations/halibut', 'WDFW — Recreational bottomfish and halibut fisheries page', '2026-03-05', '2026-09-02', 2,
   null, null, null, null, null, null, null, null, null, false, 120),
  ('pacific_halibut', null, 'wa-ma-5-10-halibut', 'salt', 'season', 'Marine Area 5-10. The 2026 season dates are as follows: April 2 through June 30, seven days per week. August 16 through September 30, seven days per week. Fishing may close before September 30 if the quota is taken.', 'https://wdfw.wa.gov/fishing/regulations/halibut/puget-sound', 'WDFW — Puget Sound/Strait of Juan de Fuca halibut seasons and regulations', '2026-03-05', '2026-09-02', 2,
   null, null, null, null, null, null, null, null, null, true, 7),
  ('pacific_halibut', null, 'wa-ma-5-10-halibut', 'salt', 'bag_limit', 'In all marine areas open to halibut fishing, there is a one-fish daily catch limit and no minimum size restriction. There is a six fish annual bag limit. Anglers must record their catch on a WDFW catch record card.', 'https://wdfw.wa.gov/fishing/regulations/halibut/puget-sound', 'WDFW — Puget Sound/Strait of Juan de Fuca halibut seasons and regulations', '2026-03-05', '2026-09-02', 2,
   null, null, 1, null, null, null, null, null, 'Six fish annual bag limit; catch record card required.', true, 7);

insert into public.reg_rule
  (species_id, reg_group_id, reg_area_id, water_class, kind, verbatim, source_url, source_title, source_updated_at, verified_at, pack_version,
   season_start, season_end, bag_daily, possession_limit, min_size_in, max_size_in, size_measure, platform_scope, depth_note, check_inseason, stale_after_days)
values
  ('rockfish', null, 'or-marine', 'salt', 'note', 'Yelloweye and quillback rockfish are prohibited at all times and in all waters. Descending devices are mandatory; and must be used to release any rockfish outside of the 30-fathom regulatory line.', 'https://myodfw.com/sport-bottomfish-seasons', 'ODFW — Sport Bottomfish Seasons (2026 recreational bottomfish seasons/regulations)', '2025-12-31', '2026-09-02', 2,
   null, null, null, null, null, null, null, 'boat', 'Rockfish released outside 30 fathoms must go down on a descending device.', true, 30),
  (null, null, 'or-marine', 'salt', 'note', 'The multi-species rule prohibits fishing for, or taking and retaining any species of salmon, Pacific halibut or marine fish while possessing on board any species not allowed to be taken in the area at that time. Anglers are reminded that once salmon are on board, anglers are restricted to no more than 2 single point barbless hooks at all times when angling for salmon in the ocean or when angling for other species if a salmon has already been retained.', 'https://myodfw.com/sport-bottomfish-seasons', 'ODFW — Sport Bottomfish Seasons (2026 recreational bottomfish seasons/regulations)', '2025-12-31', '2026-09-02', 2,
   null, null, null, null, null, null, null, 'boat', null, true, 30),
  ('dungeness_crab', null, 'or-marine', 'salt', 'gear', 'Only male crab 5-3/4 inches or larger may be kept. You can have up to three different pots, traps or rings in the water at one time. While crabbing in Oregon''s bays and estuaries is open year-round, the ocean off the Oregon coast is closed to crabbing from Oct. 16 to Nov. 30. Everyone 12 years or older will need a shellfish license to clam or crab in Oregon.', 'https://myodfw.com/articles/start-crabbing', 'ODFW — Start crabbing (measuring, season, gear)', null, '2026-09-02', 2,
   null, null, null, null, 5.75, null, 'total_length', null, 'Males only; ocean closed Oct 16 - Nov 30; measure across the back, in front of the spine (not tip to tip).', true, 60),
  ('dungeness_crab', null, 'or-marine', 'salt', 'note', 'Always check for closures at the ODA Shellfish Safety page before harvesting shellfish, which includes clams, crabs and mussels. Call the ODA shellfish safety hotline at 1-800-448-2474. Recreational crabbers are prohibited from using certain line markings that are required in other fisheries (marine life entanglement prevention). Buoys must be marked in the ocean and bays.', 'https://myodfw.com/recreation-report/crabbing-clamming-report/marine-zone', 'ODFW — Marine Zone Crabbing & Clamming Report', '2026-08-27', '2026-09-02', 2,
   null, null, null, null, null, null, null, null, null, true, 14),
  ('european_green_crab', null, 'or-marine', 'salt', 'bag_limit', 'European green crab — the daily catch limit for European green crab is 35 per person per day; European green crab can be any size or sex. The Oregon Fish and Wildlife Commission increased the daily bag limit to 35 crab to help native shellfish.', 'https://myodfw.com/recreation-report/fishing-report/marine-zone', 'ODFW — European green crab (species page / Marine Zone recreation report)', '2026-08-27', '2026-09-02', 2,
   null, null, 35, null, null, null, null, null, 'Any size, any sex — invasive removal encouraged.', false, 180),
  ('razor_clam', null, 'or-marine', 'salt', 'season', 'Annual conservation closure for razor clams north of Tillamook Head (Clatsop Beaches) begins July 15 and goes through September 30. The season will reopen October 1 unless there is a closure for toxin levels.', 'https://myodfw.com/recreation-report/crabbing-clamming-report/marine-zone', 'ODFW — Marine Zone Crabbing & Clamming Report', '2026-08-27', '2026-09-02', 2,
   '2026-07-15', '2026-09-30', 0, null, null, null, null, null, 'North of Tillamook Head (Clatsop Beaches) only; other beaches remain open except toxin closures.', true, 30),
  ('razor_clam', null, 'or-marine', 'salt', 'note', 'Clammers need to remember to keep the first 15 they dig, regardless of size or condition. (Razor clams.)', 'https://myodfw.com/recreation-report/crabbing-clamming-report/marine-zone', 'ODFW — Marine Zone Crabbing & Clamming Report', '2026-08-27', '2026-09-02', 2,
   null, null, 15, null, null, null, null, null, 'Keep the first 15 dug — wastage is prohibited.', true, 60);

insert into public.reg_pack (id, version, published_at, notes) values
  ('washington-2026-09-02', 2, '2026-09-02T12:00:00Z', 'Washington ocean Marine Areas 1-4 (WDFW news release March 5, 2026) — v2 deepens with the inside-waters doctrine (no rockfish 6-13, barbless hooks 5-13), Puget Sound halibut windows (1/day, 6/yr, catch record card), the North Coast 20-fathom retention list, the C-shaped yelloweye conservation area, wolf-eel closure, and the five-additional-flatfish rule. Salmon and shellfish remain unshipped.'),
  ('oregon-2026-09-02', 2, '2026-09-02T12:00:00Z', 'Oregon ocean (ODFW): 2026 marine bottomfish table verbatim — general marine 4/day all depths year-round, canary 2 sub-bag, cabezon 1 (Jul–Dec, 16-inch), lingcod 3 (22-inch), sablefish 10, flatfish 25, offshore long-leader 10, halibut per the federal Area 2A catch-sharing plan. Yelloweye and quillback rockfish retention prohibited; descending device mandatory on boats. v2 deepens: multi-species/salmon- hook doctrine, 30-fathom descender use, and shellfish — Dungeness (males >=5.75in, ocean closed Oct 16-Nov 30, 3 pots, license 12+), green crab 35/day, razor clam Clatsop seasonal closure Jul 15-Sep 30 + first-15 keep.')
on conflict (id) do update set version = excluded.version, notes = excluded.notes;
