-- Atlantic wave 3 (2026-09-03): Connecticut DEEP, New Hampshire F&G, Maine DMR
-- recreational saltwater tables. GENERATED via gen-atlantic-wave3.mts — edit bundles,
-- regenerate. Insert-only.

insert into public.reg_pack (id, version, published_at, notes) values
  ('connecticut-2026-09-03', 1, '2026-09-03T21:00:00Z', 'Connecticut DEEP marine recreational table (2026): stripers 28–<31" @1 year-round + circle-hook bait; fluke 19" May 4–Aug 1 then 19.5" Aug 2–Oct 15 @3 (enhanced shore 17"); tautog 16" 2/2/3 windows; scup shore 9.5" / boat 11" @30 May 1–Dec 31; bluefish 5 (7 for-hire); BSB 15.5" @4 May 16–Nov 25 (filament excluded).')
on conflict (id) do nothing;

insert into public.reg_area (id, authority, kind, name, parent_id, boundary_geojson, source_url, verified_at, notes) values
  ('ct-lis', 'ct-deep', 'ocean_region', 'Connecticut — Long Island Sound / tidal waters', null, '[[-73.66,41.3],[-71.85,41.4],[-71.85,41.15],[-73.66,40.95],[-73.66,41.3]]', 'https://portal.ct.gov/deep/fishing/saltwater-fishing-guide/species-regulations', '2026-09-03', 'Possession in CT waters/shore must meet CT size/season/creel regardless of where taken.')
on conflict (id) do nothing;

insert into public.reg_rule
  (species_id, reg_group_id, reg_area_id, water_class, kind, verbatim, source_url, source_title, source_updated_at, verified_at, pack_version,
   season_start, season_end, bag_daily, possession_limit, min_size_in, max_size_in, size_measure, platform_scope, depth_note, check_inseason, stale_after_days)
values
  ('striped_bass', null, 'ct-lis', 'salt', 'bag_limit', 'Striped Bass: No person shall possess any striped bass less than 28 inches or greater than or equal to 31 inches measured from the tip of the snout to the end of the tail. Daily creel limit: 1 fish per angler. Open Season: Open Year Round.', 'https://portal.ct.gov/deep/fishing/saltwater-fishing-guide/species-regulations', 'Connecticut DEEP — Saltwater Fishing Guide: Species Regulations', '2026-01-01', '2026-09-03', 1,
   null, null, 1, 1, 28, 31, 'total_length', null, null, true, 30),
  ('striped_bass', null, 'ct-lis', 'salt', 'gear', 'Inline circle hook required when fishing with bait (does not apply to artificial lures).', 'https://portal.ct.gov/deep/fishing/saltwater-fishing-guide/species-regulations', 'Connecticut DEEP — Saltwater Fishing Guide: Species Regulations', '2026-01-01', '2026-09-03', 1,
   null, null, null, null, null, null, null, null, null, true, 30),
  ('summer_flounder', null, 'ct-lis', 'salt', 'bag_limit', 'Summer Flounder (Fluke): Open Season: May 4 - August 1; 19 inch minimum length. Daily creel limit: 3 fish per angler.', 'https://portal.ct.gov/deep/fishing/saltwater-fishing-guide/species-regulations', 'Connecticut DEEP — Saltwater Fishing Guide: Species Regulations', '2026-01-01', '2026-09-03', 1,
   '2026-05-04', '2026-08-01', 3, 3, 19, null, 'total_length', null, 'Enhanced shore sites 17".', true, 30),
  ('summer_flounder', null, 'ct-lis', 'salt', 'bag_limit', 'Summer Flounder (Fluke): Open Season: August 2 - October 15; 19.5 inch minimum length. Daily creel limit: 3 fish per angler.', 'https://portal.ct.gov/deep/fishing/saltwater-fishing-guide/species-regulations', 'Connecticut DEEP — Saltwater Fishing Guide: Species Regulations', '2026-01-01', '2026-09-03', 1,
   '2026-08-02', '2026-10-15', 3, 3, 19.5, null, 'total_length', null, 'Enhanced shore sites 17".', true, 30),
  ('tautog', null, 'ct-lis', 'salt', 'bag_limit', 'Tautog (Blackfish): Minimum length 16 inches. Open Season: April 1 - April 30, 2 fish per angler.', 'https://portal.ct.gov/deep/fishing/saltwater-fishing-guide/species-regulations', 'Connecticut DEEP — Saltwater Fishing Guide: Species Regulations', '2026-01-01', '2026-09-03', 1,
   '2026-04-01', '2026-04-30', 2, 2, 16, null, 'total_length', null, null, true, 30),
  ('tautog', null, 'ct-lis', 'salt', 'bag_limit', 'Tautog (Blackfish): Minimum length 16 inches. Open Season: July 1 - August 31, 2 fish per angler.', 'https://portal.ct.gov/deep/fishing/saltwater-fishing-guide/species-regulations', 'Connecticut DEEP — Saltwater Fishing Guide: Species Regulations', '2026-01-01', '2026-09-03', 1,
   '2026-07-01', '2026-08-31', 2, 2, 16, null, 'total_length', null, null, true, 30),
  ('tautog', null, 'ct-lis', 'salt', 'bag_limit', 'Tautog (Blackfish): Minimum length 16 inches. Open Season: October 10 - November 28, 3 fish per angler.', 'https://portal.ct.gov/deep/fishing/saltwater-fishing-guide/species-regulations', 'Connecticut DEEP — Saltwater Fishing Guide: Species Regulations', '2026-01-01', '2026-09-03', 1,
   '2026-10-10', '2026-11-28', 3, 3, 16, null, 'total_length', null, null, true, 30),
  ('tautog', null, 'ct-lis', 'salt', 'season', 'Tautog (Blackfish) open April 1-April 30, July 1-August 31, and October 10-November 28.', 'https://portal.ct.gov/deep/fishing/saltwater-fishing-guide/species-regulations', 'Connecticut DEEP — Saltwater Fishing Guide: Species Regulations', '2026-01-01', '2026-09-03', 1,
   '2026-04-01', '2026-04-30', null, null, null, null, null, null, null, true, 30),
  ('tautog', null, 'ct-lis', 'salt', 'season', 'Tautog (Blackfish) open July 1 - August 31.', 'https://portal.ct.gov/deep/fishing/saltwater-fishing-guide/species-regulations', 'Connecticut DEEP — Saltwater Fishing Guide: Species Regulations', '2026-01-01', '2026-09-03', 1,
   '2026-07-01', '2026-08-31', null, null, null, null, null, null, null, true, 30),
  ('tautog', null, 'ct-lis', 'salt', 'season', 'Tautog (Blackfish) open October 10 - November 28.', 'https://portal.ct.gov/deep/fishing/saltwater-fishing-guide/species-regulations', 'Connecticut DEEP — Saltwater Fishing Guide: Species Regulations', '2026-01-01', '2026-09-03', 1,
   '2026-10-10', '2026-11-28', null, null, null, null, null, null, null, true, 30),
  ('scup', null, 'ct-lis', 'salt', 'bag_limit', 'Scup (Porgy): Minimum length 9.5 inches for shore anglers (including Enhanced Opportunity Fishing Sites). Daily creel limit 30 fish per angler. Open Season: May 1 - December 31.', 'https://portal.ct.gov/deep/fishing/saltwater-fishing-guide/species-regulations', 'Connecticut DEEP — Saltwater Fishing Guide: Species Regulations', '2026-01-01', '2026-09-03', 1,
   '2026-05-01', '2026-12-31', 30, 30, 9.5, null, 'total_length', 'shore', null, true, 30),
  ('scup', null, 'ct-lis', 'salt', 'bag_limit', 'Scup (Porgy): Minimum length 11 inches for boat anglers. Daily creel limit 30 fish per angler. Open Season: May 1 - December 31.', 'https://portal.ct.gov/deep/fishing/saltwater-fishing-guide/species-regulations', 'Connecticut DEEP — Saltwater Fishing Guide: Species Regulations', '2026-01-01', '2026-09-03', 1,
   '2026-05-01', '2026-12-31', 30, 30, 11, null, 'total_length', 'boat', 'Party/charter bonus 40 Sep 1–Oct 31 for paying passengers.', true, 30),
  ('bluefish', null, 'ct-lis', 'salt', 'bag_limit', 'Bluefish: Minimum length None. Daily creel limit: 5 fish per angler (including "snappers") (New for 2026). Open Season: Open Year Round. Party/Charter Vessel: for paying passengers only - daily creel limit, 7 fish per angler. (New for 2026)', 'https://portal.ct.gov/deep/fishing/saltwater-fishing-guide/species-regulations', 'Connecticut DEEP — Saltwater Fishing Guide: Species Regulations', '2026-01-01', '2026-09-03', 1,
   null, null, 5, 5, null, null, null, null, 'For-hire 7.', true, 60),
  ('black_sea_bass', null, 'ct-lis', 'salt', 'bag_limit', 'Black Sea Bass: Minimum length 15.5 inches (New for 2026). Daily creel limit: 4 fish per angler (New for 2026). Open Season: May 16 - November 25 (no mid-season closure) (New for 2026). Excluding tail fin filament (tendril).', 'https://portal.ct.gov/deep/fishing/saltwater-fishing-guide/species-regulations', 'Connecticut DEEP — Saltwater Fishing Guide: Species Regulations', '2026-01-01', '2026-09-03', 1,
   '2026-05-16', '2026-11-25', 4, 4, 15.5, null, 'total_length', null, 'Filament excluded. Party/charter 4 then 6 Sep 1–Dec 31.', true, 30),
  ('weakfish', null, 'ct-lis', 'salt', 'bag_limit', 'Weakfish (Sea Trout): Minimum length 16 inches. Daily creel limit 1 fish per angler. Open Season: Open Year Round.', 'https://portal.ct.gov/deep/fishing/saltwater-fishing-guide/species-regulations', 'Connecticut DEEP — Saltwater Fishing Guide: Species Regulations', '2026-01-01', '2026-09-03', 1,
   null, null, 1, 1, 16, null, 'total_length', null, null, true, 60),
  ('winter_flounder', null, 'ct-lis', 'salt', 'bag_limit', 'Winter Flounder: Minimum length 12 inches. Daily creel limit 2 fish per angler. Open Season: Open April 1 - December 31.', 'https://portal.ct.gov/deep/fishing/saltwater-fishing-guide/species-regulations', 'Connecticut DEEP — Saltwater Fishing Guide: Species Regulations', '2026-01-01', '2026-09-03', 1,
   '2026-04-01', '2026-12-31', 2, 2, 12, null, 'total_length', null, null, true, 60),
  ('american_eel', null, 'ct-lis', 'salt', 'bag_limit', 'American Eel: Minimum length 9 inches. Daily creel limit 25 fish per angler. Open Season: Open Year Round.', 'https://portal.ct.gov/deep/fishing/saltwater-fishing-guide/species-regulations', 'Connecticut DEEP — Saltwater Fishing Guide: Species Regulations', '2026-01-01', '2026-09-03', 1,
   null, null, 25, 25, 9, null, 'total_length', null, null, false, 90),
  ('river_herring', null, 'ct-lis', 'salt', 'prohibited', 'River Herring: Alewife / Blueback Herring. The taking of anadromous alewife and blueback herring is prohibited from all Connecticut waters, including Long Island Sound.', 'https://portal.ct.gov/deep/fishing/saltwater-fishing-guide/species-regulations', 'Connecticut DEEP — Saltwater Fishing Guide: Species Regulations', '2026-01-01', '2026-09-03', 1,
   null, null, 0, 0, null, null, null, null, null, false, 90);

insert into public.reg_pack (id, version, published_at, notes) values
  ('new-hampshire-2026-09-03', 1, '2026-09-03T21:00:00Z', 'New Hampshire F&G saltwater recreational table (updated 2026-08-17): stripers 28–<31" @1 year-round + circle hooks/gaff/cull bans; BSB 16.5" @4 year-round; bluefish 5/7; cod 23" @1 Sep 1–Oct 31 (closed Nov 1–Aug 31); haddock 17" @15 except March; winter flounder 12" @8; fluke 15" no bag; shad/salmon/wolffish/ocean pout/windowpane prohibited.')
on conflict (id) do nothing;

insert into public.reg_area (id, authority, kind, name, parent_id, boundary_geojson, source_url, verified_at, notes) values
  ('nh-coast', 'nh-fg', 'ocean_region', 'New Hampshire — coastal / state marine waters', null, '[[-70.9,43.05],[-70.55,42.85],[-70.55,43.1],[-70.85,43.15],[-70.9,43.05]]', 'https://www.eregulations.com/newhampshire/fishing/saltwater/recreational-commercial-regulations', '2026-09-03', 'Envelope of the 18-mile seacoast + Great Bay approaches. Federal waters follow NOAA.')
on conflict (id) do nothing;

insert into public.reg_rule
  (species_id, reg_group_id, reg_area_id, water_class, kind, verbatim, source_url, source_title, source_updated_at, verified_at, pack_version,
   season_start, season_end, bag_daily, possession_limit, min_size_in, max_size_in, size_measure, platform_scope, depth_note, check_inseason, stale_after_days)
values
  ('striped_bass', null, 'nh-coast', 'salt', 'bag_limit', 'Striped Bass Recreational: Closed Season: No closed season. Minimum Length: 28 inches to less than 31 inches. Daily Bag Limit: 1 fish per day.', 'https://www.eregulations.com/newhampshire/fishing/saltwater/recreational-commercial-regulations', 'New Hampshire Fish & Game — Saltwater Recreational & Commercial Regulations', '2026-08-17', '2026-09-03', 1,
   null, null, 1, 1, 28, 31, 'total_length', null, null, true, 30),
  ('striped_bass', null, 'nh-coast', 'salt', 'gear', 'Striped Bass Special Rules: Gaffing and culling are prohibited; No sale allowed, regardless of origin. Non-offset, corrodible circle hooks required if angling with bait. Head and tail must be intact while on or leaving the waters or shores of the state except may possess up to 2 fillets with skin intact and possess fish rack ≥ 28" and less than 31" TL with head/tail intact that fillets came from. Total length is the straight-line distance from the tip of the snout to the tip of the tail (caudal fin) when the tail is squeezed to its maximum length while the fish is laying on its side.', 'https://www.eregulations.com/newhampshire/fishing/saltwater/recreational-commercial-regulations', 'New Hampshire Fish & Game — Saltwater Recreational & Commercial Regulations', '2026-08-17', '2026-09-03', 1,
   null, null, null, null, null, null, null, null, null, true, 30),
  ('black_sea_bass', null, 'nh-coast', 'salt', 'bag_limit', 'Black Sea Bass Recreational: Closed Season: No closed season. Minimum Length: 16.5 inches. Daily Bag Limit: 4 fish per day. Special Rules: Length does not include filament/tail extension.', 'https://www.eregulations.com/newhampshire/fishing/saltwater/recreational-commercial-regulations', 'New Hampshire Fish & Game — Saltwater Recreational & Commercial Regulations', '2026-08-17', '2026-09-03', 1,
   null, null, 4, 4, 16.5, null, 'total_length', null, 'Filament excluded.', true, 30),
  ('bluefish', null, 'nh-coast', 'salt', 'bag_limit', 'Bluefish Recreational: Closed Season: No closed season. Minimum Length: No minimum length. Daily Bag Limit: 5 fish harvest or possession per day for private anglers. 7 fish harvest or possession per day for anglers on licensed for-hire fishing vessels. Special Rules: Non-offset, corrodible circle hooks required if angling with bait.', 'https://www.eregulations.com/newhampshire/fishing/saltwater/recreational-commercial-regulations', 'New Hampshire Fish & Game — Saltwater Recreational & Commercial Regulations', '2026-08-17', '2026-09-03', 1,
   null, null, 5, 5, null, null, null, null, 'For-hire 7.', true, 60),
  ('atlantic_cod', null, 'nh-coast', 'salt', 'bag_limit', 'Atlantic Cod Recreational: Closed Season: Nov. 1 – Aug. 31. Minimum Length: 23 inches. Daily Bag Limit: 1 fish per day.', 'https://www.eregulations.com/newhampshire/fishing/saltwater/recreational-commercial-regulations', 'New Hampshire Fish & Game — Saltwater Recreational & Commercial Regulations', '2026-08-17', '2026-09-03', 1,
   '2026-09-01', '2026-10-31', 1, 1, 23, null, 'total_length', null, 'Open Sep 1–Oct 31 only.', true, 14),
  ('atlantic_cod', null, 'nh-coast', 'salt', 'season', 'Atlantic Cod Recreational: Closed Season: Nov. 1 – Aug. 31.', 'https://www.eregulations.com/newhampshire/fishing/saltwater/recreational-commercial-regulations', 'New Hampshire Fish & Game — Saltwater Recreational & Commercial Regulations', '2026-08-17', '2026-09-03', 1,
   '2026-09-01', '2026-10-31', null, null, null, null, null, null, null, true, 14),
  ('haddock', null, 'nh-coast', 'salt', 'bag_limit', 'Haddock Recreational: Closed Season: March 1 – March 31. Minimum Length: 17 inches. Daily Bag Limit: 15 fish per day.', 'https://www.eregulations.com/newhampshire/fishing/saltwater/recreational-commercial-regulations', 'New Hampshire Fish & Game — Saltwater Recreational & Commercial Regulations', '2026-08-17', '2026-09-03', 1,
   '2026-04-01', '2026-02-28', 15, 15, 17, null, 'total_length', null, 'Closed March; window wraps New Year''s.', true, 30),
  ('winter_flounder', null, 'nh-coast', 'salt', 'bag_limit', 'Winter Flounder Recreational: Closed Season: No closed season. Minimum Length: 12 inches. Daily Bag Limit: 8 fish per day.', 'https://www.eregulations.com/newhampshire/fishing/saltwater/recreational-commercial-regulations', 'New Hampshire Fish & Game — Saltwater Recreational & Commercial Regulations', '2026-08-17', '2026-09-03', 1,
   null, null, 8, 8, 12, null, 'total_length', null, null, true, 60),
  ('summer_flounder', null, 'nh-coast', 'salt', 'bag_limit', 'Summer Flounder Recreational: Closed Season: No closed season. Minimum Length: 15 inches. Daily Bag Limit: No bag limit. Special Rules: Sale is prohibited.', 'https://www.eregulations.com/newhampshire/fishing/saltwater/recreational-commercial-regulations', 'New Hampshire Fish & Game — Saltwater Recreational & Commercial Regulations', '2026-08-17', '2026-09-03', 1,
   null, null, null, null, 15, null, 'total_length', null, 'No bag limit.', true, 60),
  ('atlantic_halibut', null, 'nh-coast', 'salt', 'bag_limit', 'Atlantic Halibut Recreational: Closed Season: No closed season. Minimum Length: 41 inches. Daily Bag Limit: 1 fish per trip/vessel.', 'https://www.eregulations.com/newhampshire/fishing/saltwater/recreational-commercial-regulations', 'New Hampshire Fish & Game — Saltwater Recreational & Commercial Regulations', '2026-08-17', '2026-09-03', 1,
   null, null, 1, 1, 41, null, 'total_length', null, 'Per trip/vessel.', true, 60),
  ('atlantic_mackerel', null, 'nh-coast', 'salt', 'bag_limit', 'Atlantic Mackerel Recreational: Closed Season: No closed season. Minimum Length: No minimum length. Daily Bag Limit: 25 fish harvest or possession per day for private anglers. 50 fish harvest or possession per day for anglers on licensed for-hire fishing vessels.', 'https://www.eregulations.com/newhampshire/fishing/saltwater/recreational-commercial-regulations', 'New Hampshire Fish & Game — Saltwater Recreational & Commercial Regulations', '2026-08-17', '2026-09-03', 1,
   null, null, 25, 25, null, null, null, null, 'For-hire 50.', true, 60),
  ('american_eel', null, 'nh-coast', 'salt', 'bag_limit', 'American Eel Recreational: Closed Season: No closed season (except surrounding fishways). Minimum Length: 9 inches. Daily Bag Limit: 25 fish per day.', 'https://www.eregulations.com/newhampshire/fishing/saltwater/recreational-commercial-regulations', 'New Hampshire Fish & Game — Saltwater Recreational & Commercial Regulations', '2026-08-17', '2026-09-03', 1,
   null, null, 25, 25, 9, null, 'total_length', null, 'Fishway closures Oct 2–Jun 14.', false, 90),
  ('american_shad', null, 'nh-coast', 'salt', 'prohibited', 'American Shad Recreational: Closed Season: Closed year round. Possession prohibited. Special Rules: All shad must be immediately released.', 'https://www.eregulations.com/newhampshire/fishing/saltwater/recreational-commercial-regulations', 'New Hampshire Fish & Game — Saltwater Recreational & Commercial Regulations', '2026-08-17', '2026-09-03', 1,
   null, null, 0, 0, null, null, null, null, null, false, 90),
  ('atlantic_wolffish', null, 'nh-coast', 'salt', 'prohibited', 'Atlantic Wolffish Recreational: Closed Season: Closed year round. Possession is prohibited.', 'https://www.eregulations.com/newhampshire/fishing/saltwater/recreational-commercial-regulations', 'New Hampshire Fish & Game — Saltwater Recreational & Commercial Regulations', '2026-08-17', '2026-09-03', 1,
   null, null, 0, 0, null, null, null, null, null, false, 120),
  ('ocean_pout', null, 'nh-coast', 'salt', 'prohibited', 'Ocean Pout Recreational: Closed Season: Closed year round. Possession is prohibited.', 'https://www.eregulations.com/newhampshire/fishing/saltwater/recreational-commercial-regulations', 'New Hampshire Fish & Game — Saltwater Recreational & Commercial Regulations', '2026-08-17', '2026-09-03', 1,
   null, null, 0, 0, null, null, null, null, null, false, 120),
  ('windowpane_flounder', null, 'nh-coast', 'salt', 'prohibited', 'Windowpane Flounder Recreational: Closed Season: Closed year round. Possession is prohibited.', 'https://www.eregulations.com/newhampshire/fishing/saltwater/recreational-commercial-regulations', 'New Hampshire Fish & Game — Saltwater Recreational & Commercial Regulations', '2026-08-17', '2026-09-03', 1,
   null, null, 0, 0, null, null, null, null, null, false, 120);

insert into public.reg_pack (id, version, published_at, notes) values
  ('maine-2026-09-03', 1, '2026-09-03T21:00:00Z', 'Maine DMR 2026: stripers 28–31" inclusive @1 year-round (Kennebec C&R May 1–Jun 30, closed Dec 1–Jun 30 except that C&R window; EEZ prohibited) + circle-hook bait / no gaff; cod 23" @1 Sep 1–Oct 31; haddock 17" @15 except March; winter flounder 12" @8; fluke 20" @2; BSB 13" @10 May 19–Sep 21 and Oct 18–Dec 31; bluefish 5 + circle-hook bait; wolffish prohibited.')
on conflict (id) do nothing;

insert into public.reg_area (id, authority, kind, name, parent_id, boundary_geojson, source_url, verified_at, notes) values
  ('me-coast', 'me-dmr', 'ocean_region', 'Maine — coastal waters to head of tide', null, '[[-70.85,43.05],[-66.95,44.8],[-66.95,44.4],[-70.55,43.05],[-70.85,43.05]]', 'https://www.maine.gov/dmr/sites/maine.gov.dmr/files/inline-files/2026_sportfish_regs_Gabrielle%20Page_0.pdf', '2026-09-03', 'Envelope. Kennebec watershed has a separate striped-bass area.'),
  ('me-kennebec', 'me-dmr', 'ocean_region', 'Kennebec watershed (incl. Sheepscot, Androscoggin, related bays/tributaries to head of tide)', null, null, 'https://www.maine.gov/dmr/sites/maine.gov.dmr/files/inline-files/2026_striped_bass_regs%20-%20ADA%20compliant.pdf', '2026-09-03', 'Inside Cape Small–Salter Island–Cape Newagen line.')
on conflict (id) do nothing;

insert into public.reg_rule
  (species_id, reg_group_id, reg_area_id, water_class, kind, verbatim, source_url, source_title, source_updated_at, verified_at, pack_version,
   season_start, season_end, bag_daily, possession_limit, min_size_in, max_size_in, size_measure, platform_scope, depth_note, check_inseason, stale_after_days)
values
  ('striped_bass', null, 'me-coast', 'salt', 'bag_limit', 'STATEWIDE REGULATIONS OPEN SEASON January 1 through December 31, inclusive (except the Kennebec watershed). BAG LIMITS A person may take and possess 1 striped bass per day. SIZE LIMITS Fish can be harvested between 28 inches and 31 inches inclusive total length.', 'https://www.maine.gov/dmr/sites/maine.gov.dmr/files/inline-files/2026_striped_bass_regs%20-%20ADA%20compliant.pdf', 'Maine DMR — 2026 Striped Bass Regulations', '2026-03-25', '2026-09-03', 1,
   null, null, 1, 1, 28, 31, 'total_length', null, 'EEZ possession prohibited.', true, 30),
  ('striped_bass', null, 'me-coast', 'salt', 'gear', 'GENERAL GEAR RESTRICTIONS: Hook and line only, no gaffing of striped bass. No bait allowed when using treble hooks. It is unlawful to use more than two barbed or barbless treble hooks on any artificial lure or fly while fishing for striped bass in territorial waters. It is unlawful to use any hook other than a non-offset circle hook when using bait. Exception: Rubber or latex tube lures may be used without a circle hook if they are a minimum of 8 inches long and have a single hook protruding from the end portion of the tubing where bait may be attached. Fish must remain whole and intact.', 'https://www.maine.gov/dmr/sites/maine.gov.dmr/files/inline-files/2026_striped_bass_regs%20-%20ADA%20compliant.pdf', 'Maine DMR — 2026 Striped Bass Regulations', '2026-03-25', '2026-09-03', 1,
   null, null, null, null, null, null, null, null, null, true, 30),
  ('striped_bass', null, 'me-kennebec', 'salt', 'season', 'SPECIAL KENNEBEC REGULATIONS: CATCH & RELEASE SEASON WITH SPECIAL GEAR RESTRICTIONS From May 1 through June 30, inclusive. Fishing in this area is restricted to single-hooked artificial lures only (may be a single treble hook). Use of or possession of marine bait, dead or alive, is prohibited.', 'https://www.maine.gov/dmr/sites/maine.gov.dmr/files/inline-files/2026_striped_bass_regs%20-%20ADA%20compliant.pdf', 'Maine DMR — 2026 Striped Bass Regulations', '2026-03-25', '2026-09-03', 1,
   '2026-05-01', '2026-06-30', 0, 0, null, null, null, null, 'Closed.', true, 30),
  ('striped_bass', null, 'me-kennebec', 'salt', 'bag_limit', 'SPECIAL KENNEBEC REGULATIONS OPEN SEASON July 1 through November 30, inclusive. (Statewide 1 fish, 28–31 inches inclusive, applies.)', 'https://www.maine.gov/dmr/sites/maine.gov.dmr/files/inline-files/2026_striped_bass_regs%20-%20ADA%20compliant.pdf', 'Maine DMR — 2026 Striped Bass Regulations', '2026-03-25', '2026-09-03', 1,
   '2026-07-01', '2026-11-30', 1, 1, 28, 31, 'total_length', null, null, true, 30),
  ('atlantic_cod', null, 'me-coast', 'salt', 'bag_limit', 'ATLANTIC COD: Size: Minimum size 23 inches. Bag limit: 1 fish per angler per day. Season: Sept 1 – Oct 31, inclusive.', 'https://www.maine.gov/dmr/sites/maine.gov.dmr/files/inline-files/2026_sportfish_regs_Gabrielle%20Page_0.pdf', 'Maine DMR — 2026 Saltwater Recreational Fishing Regulations (Groundfish and Other Finfish, posted July 14, 2026)', '2026-07-01', '2026-09-03', 1,
   '2026-09-01', '2026-10-31', 1, 1, 23, null, 'total_length', null, null, true, 14),
  ('atlantic_cod', null, 'me-coast', 'salt', 'season', 'ATLANTIC COD Season: Sept 1 – Oct 31, inclusive.', 'https://www.maine.gov/dmr/sites/maine.gov.dmr/files/inline-files/2026_sportfish_regs_Gabrielle%20Page_0.pdf', 'Maine DMR — 2026 Saltwater Recreational Fishing Regulations (Groundfish and Other Finfish, posted July 14, 2026)', '2026-07-01', '2026-09-03', 1,
   '2026-09-01', '2026-10-31', null, null, null, null, null, null, null, true, 14),
  ('haddock', null, 'me-coast', 'salt', 'bag_limit', 'HADDOCK: Size: Minimum size 17 inches. Bag limit: 15 fish per angler per day. Season: Cannot possess from March 1 through March 31 inclusive.', 'https://www.maine.gov/dmr/sites/maine.gov.dmr/files/inline-files/2026_sportfish_regs_Gabrielle%20Page_0.pdf', 'Maine DMR — 2026 Saltwater Recreational Fishing Regulations (Groundfish and Other Finfish, posted July 14, 2026)', '2026-07-01', '2026-09-03', 1,
   '2026-04-01', '2026-02-28', 15, 15, 17, null, 'total_length', null, 'Closed March; wraps New Year''s.', true, 30),
  ('winter_flounder', null, 'me-coast', 'salt', 'bag_limit', 'WINTER FLOUNDER: Size: Minimum size 12 inches. Bag limit: 8 fish per angler per day.', 'https://www.maine.gov/dmr/sites/maine.gov.dmr/files/inline-files/2026_sportfish_regs_Gabrielle%20Page_0.pdf', 'Maine DMR — 2026 Saltwater Recreational Fishing Regulations (Groundfish and Other Finfish, posted July 14, 2026)', '2026-07-01', '2026-09-03', 1,
   null, null, 8, 8, 12, null, 'total_length', null, null, true, 60),
  ('summer_flounder', null, 'me-coast', 'salt', 'bag_limit', 'SUMMER FLOUNDER: Size: Minimum size 20 inches. Bag limit: 2 fish per angler per day.', 'https://www.maine.gov/dmr/sites/maine.gov.dmr/files/inline-files/2026_sportfish_regs_Gabrielle%20Page_0.pdf', 'Maine DMR — 2026 Saltwater Recreational Fishing Regulations (Groundfish and Other Finfish, posted July 14, 2026)', '2026-07-01', '2026-09-03', 1,
   null, null, 2, 2, 20, null, 'total_length', null, null, true, 60),
  ('black_sea_bass', null, 'me-coast', 'salt', 'bag_limit', 'BLACK SEA BASS: Size: Minimum size 13 inches. Bag limit: 10 fish per angler per day. Season: May 19 – September 21 and October 18 – December 31, inclusive. Method of take: Hook and line only.', 'https://www.maine.gov/dmr/sites/maine.gov.dmr/files/inline-files/2026_sportfish_regs_Gabrielle%20Page_0.pdf', 'Maine DMR — 2026 Saltwater Recreational Fishing Regulations (Groundfish and Other Finfish, posted July 14, 2026)', '2026-07-01', '2026-09-03', 1,
   '2026-05-19', '2026-09-21', 10, 10, 13, null, 'total_length', null, 'Hook and line only.', true, 30),
  ('black_sea_bass', null, 'me-coast', 'salt', 'bag_limit', 'BLACK SEA BASS: Size: Minimum size 13 inches. Bag limit: 10 fish per angler per day. Season: May 19 – September 21 and October 18 – December 31, inclusive.', 'https://www.maine.gov/dmr/sites/maine.gov.dmr/files/inline-files/2026_sportfish_regs_Gabrielle%20Page_0.pdf', 'Maine DMR — 2026 Saltwater Recreational Fishing Regulations (Groundfish and Other Finfish, posted July 14, 2026)', '2026-07-01', '2026-09-03', 1,
   '2026-10-18', '2026-12-31', 10, 10, 13, null, 'total_length', null, 'Hook and line only.', true, 30),
  ('bluefish', null, 'me-coast', 'salt', 'bag_limit', 'BLUEFISH: Size: No minimum size. Bag limit: 5 fish per angler per day. Method of take: No bait with treble hook. No more than two treble hooks per lure. It is unlawful to use any hook other than a circle hook when using bait.', 'https://www.maine.gov/dmr/sites/maine.gov.dmr/files/inline-files/2026_sportfish_regs_Gabrielle%20Page_0.pdf', 'Maine DMR — 2026 Saltwater Recreational Fishing Regulations (Groundfish and Other Finfish, posted July 14, 2026)', '2026-07-01', '2026-09-03', 1,
   null, null, 5, 5, null, null, null, null, null, true, 60),
  ('atlantic_mackerel', null, 'me-coast', 'salt', 'bag_limit', 'ATLANTIC MACKEREL: Size: No minimum size. Bag limit: 25 fish per angler per day.', 'https://www.maine.gov/dmr/sites/maine.gov.dmr/files/inline-files/2026_sportfish_regs_Gabrielle%20Page_0.pdf', 'Maine DMR — 2026 Saltwater Recreational Fishing Regulations (Groundfish and Other Finfish, posted July 14, 2026)', '2026-07-01', '2026-09-03', 1,
   null, null, 25, 25, null, null, null, null, null, true, 60),
  ('pollock', null, 'me-coast', 'salt', 'bag_limit', 'POLLOCK: Maine Territorial waters: No size or bag limits. Federal waters: Minimum size 19 inches & no bag limit.', 'https://www.maine.gov/dmr/sites/maine.gov.dmr/files/inline-files/2026_sportfish_regs_Gabrielle%20Page_0.pdf', 'Maine DMR — 2026 Saltwater Recreational Fishing Regulations (Groundfish and Other Finfish, posted July 14, 2026)', '2026-07-01', '2026-09-03', 1,
   null, null, null, null, null, null, null, null, 'Federal waters 19" min.', true, 60),
  ('atlantic_wolffish', null, 'me-coast', 'salt', 'prohibited', 'ATLANTIC WOLFFISH: Anglers are prohibited from possessing Atlantic wolffish.', 'https://www.maine.gov/dmr/sites/maine.gov.dmr/files/inline-files/2026_sportfish_regs_Gabrielle%20Page_0.pdf', 'Maine DMR — 2026 Saltwater Recreational Fishing Regulations (Groundfish and Other Finfish, posted July 14, 2026)', '2026-07-01', '2026-09-03', 1,
   null, null, 0, 0, null, null, null, null, null, false, 120);
