-- Washington v4 (2026-09-02): Crab Rules page verbatim (WDFW 2026-27 book,
-- page updated 2026-06-18). GENERATED via gen-wa-crab-v4.mts.
-- Insert-only + pack upsert to 4. Species appendix mirrors ontology additions.
-- Also PATCHES the v3 Puget Sound pamphlet rows: source_url shipped as
-- .../fishing/ma-N; the live page path is .../fishing/marine-area-N.

insert into public.species (id, common_name, scientific_name, is_group, rolls_up_to, water_class, take_status, sort_order, needs_review) values
  ('red_rock_crab', 'Red rock crab', 'Cancer productus', false, null, 'salt', 'regulated', 490, false),
  ('tanner_crab', 'Tanner crab', 'Chionoecetes bairdi', false, null, 'salt', 'regulated', 491, false)
on conflict (id) do nothing;

update public.reg_rule
set source_url = 'https://www.eregulations.com/washington/fishing/marine-area-' || substring(reg_area_id from 'wa-ma-(\d+)')
where reg_area_id in ('wa-ma-9', 'wa-ma-10', 'wa-ma-13')
  and source_url like 'https://www.eregulations.com/washington/fishing/ma-%';

insert into public.reg_area (id, authority, kind, name, parent_id, boundary_geojson, source_url, verified_at, notes) values
  ('wa-ps-crab', 'wdfw', 'ocean_region', 'Puget Sound crab — Marine Areas 4 (east of Bonilla-Tatoosh), 5, 6, 7 South/North, 8-1, 8-2, 9, 10, 11, 12 (north of Ayock Point)', null, '[[-123.96,49],[-123.1,48.9],[-122.8,48.45],[-122.4,48.9],[-122.3,49.15],[-123.7,49.15],[-123.96,49]]', 'https://www.eregulations.com/washington/fishing/crab-rules', '2026-09-02', 'Seasons are announced each spring (test fishery + co-management); limits/shape per the Crab Rules page. Envelope matches the inside-waters area; MA 12 south of Ayock Point and MA 13 are closed to crab harvest in 2026.'),
  ('wa-willapa-bay', 'wdfw', 'ocean_region', 'Willapa Bay (crab/shellfish estuary)', null, '[[-124.1,46.55],[-123.9,46.6],[-123.85,46.75],[-124,46.95],[-124.15,46.8],[-124.1,46.55]]', 'https://www.eregulations.com/washington/fishing/crab-rules', '2026-09-02', 'Envelope. Full bay fish tables pending; v4 ships the pamphlet crab lines only.'),
  ('wa-columbia-river', 'wdfw', 'ocean_region', 'Columbia River — east of the jetty tips upstream to the Tongue Point–Rocky Point line (crab estuary)', null, '[[-124.06,46.24],[-123.7,46.24],[-123.7,46.32],[-124.06,46.32],[-124.06,46.24]]', 'https://www.eregulations.com/washington/fishing/crab-rules', '2026-09-02', 'Salmonid-estuarine reach; v4 ships the year-round crab table only. Freshwater upstream rules are out of the salt pack''s scope.')
on conflict (id) do nothing;

insert into public.reg_rule
  (species_id, reg_group_id, reg_area_id, water_class, kind, verbatim, source_url, source_title, source_updated_at, verified_at, pack_version,
   season_start, season_end, bag_daily, possession_limit, min_size_in, max_size_in, size_measure, platform_scope, depth_note, check_inseason, stale_after_days)
values
  (null, null, 'wa-ps-crab', 'salt', 'note', 'Crab (Puget Sound): A catch record card (CRC) and a crab endorsement are required for Dungeness crab in Puget Sound only. Any harvest after Labor Day must be recorded on a winter CRC. Must release all softshell crab (underside of shell flexes with finger pressure). Fishing instruments must not penetrate the shell. It is unlawful to possess crab in the field without retaining the back shell. May not retain any species of crab other than Dungeness, Red Rock, and Tanner.', 'https://www.eregulations.com/washington/fishing/crab-rules', 'WDFW — 2026-2027 Washington Sport Fishing Rules (Crab Rules)', '2026-06-18', '2026-09-02', 4,
   null, null, null, null, null, null, null, null, null, false, 90),
  (null, null, 'wa-ps-crab', 'salt', 'note', 'Marine Areas 4 (east of the Bonilla-Tatoosh line), 5, 6, 7 South, 7 North, 8-1, 8-2, 9, 10, 11 and 12 (North of Ayock Point): For seasons go to wdfw.wa.gov/fishing/shellfishing-regulations/crab#marine-area. The dates for the season will be available in late May or early June to accommodate co-management obligations and complete preseason test fishing and quota setting. All Dungeness crab kept must be immediately recorded on a catch record card in ink. (Padilla Bay: crab fishing within 25 yards of the Burlington-Northern railroad trestles at the north end of Swinomish Slough is only allowed from one hour before official sunrise to one hour after official sunset.)', 'https://www.eregulations.com/washington/fishing/crab-rules', 'WDFW — 2026-2027 Washington Sport Fishing Rules (Crab Rules)', '2026-06-18', '2026-09-02', 4,
   null, null, null, null, null, null, null, null, null, true, 7),
  ('dungeness_crab', null, 'wa-ps-crab', 'salt', 'bag_limit', 'Dungeness Crab (Puget Sound Daily Limits/Rules): 5 crabs, 6¼" minimum size, males only, and in hardshell condition.', 'https://www.eregulations.com/washington/fishing/crab-rules', 'WDFW — 2026-2027 Washington Sport Fishing Rules (Crab Rules)', '2026-06-18', '2026-09-02', 4,
   null, null, 5, null, 6.25, null, 'carapace_width', null, 'Males only, hardshell condition; CRC endorsement required; record in ink immediately.', true, 14),
  ('red_rock_crab', null, 'wa-ps-crab', 'salt', 'bag_limit', 'Red Rock Crab (Puget Sound Daily Limits/Rules): 6 crabs, 5" minimum size, of either sex, and in hardshell condition.', 'https://www.eregulations.com/washington/fishing/crab-rules', 'WDFW — 2026-2027 Washington Sport Fishing Rules (Crab Rules)', '2026-06-18', '2026-09-02', 4,
   null, null, 6, null, 5, null, 'carapace_width', null, 'Either sex, hardshell.', true, 14),
  ('tanner_crab', null, 'wa-ps-crab', 'salt', 'bag_limit', 'Tanner Crab (Puget Sound Daily Limits/Rules): 6 crabs, 4½" minimum size, of either sex, and in hardshell condition. Measure at the widest portion of the shell.', 'https://www.eregulations.com/washington/fishing/crab-rules', 'WDFW — 2026-2027 Washington Sport Fishing Rules (Crab Rules)', '2026-06-18', '2026-09-02', 4,
   null, null, 6, null, 4.5, null, 'carapace_width', null, 'Either sex, hardshell; measure at widest portion of shell.', true, 14),
  ('european_green_crab', null, 'wa-ps-crab', 'salt', 'prohibited', 'European Green Crab — Help Stop the Spread: If caught please REPORT and RELEASE (it is illegal to retain or transport them alive). European green crabs are classified as prohibited species and it is illegal to retain/harvest them. Report: wdfw.wa.gov/greencrab, WA Invasives app, 1-888-WDFW-AIS, ais@wdfw.wa.gov.', 'https://www.eregulations.com/washington/fishing/crab-rules', 'WDFW — 2026-2027 Washington Sport Fishing Rules (Crab Rules)', '2026-06-18', '2026-09-02', 4,
   null, null, 0, 0, null, null, null, null, 'Report-and-release; keeps-of-molt allowed.', false, 365),
  ('dungeness_crab', null, 'wa-ma-13', 'salt', 'prohibited', 'Marine Areas 12 (south of Ayock Point), and 13 — Dungeness, Red Rock, and Tanner Crab: Closed to crab harvest in 2026.', 'https://www.eregulations.com/washington/fishing/crab-rules', 'WDFW — 2026-2027 Washington Sport Fishing Rules (Crab Rules)', '2026-06-18', '2026-09-02', 4,
   null, null, 0, 0, null, null, null, null, 'All crab harvest closed 2026 (book year).', true, 30),
  ('red_rock_crab', null, 'wa-ma-13', 'salt', 'prohibited', 'Marine Areas 12 (south of Ayock Point), and 13 — Dungeness, Red Rock, and Tanner Crab: Closed to crab harvest in 2026.', 'https://www.eregulations.com/washington/fishing/crab-rules', 'WDFW — 2026-2027 Washington Sport Fishing Rules (Crab Rules)', '2026-06-18', '2026-09-02', 4,
   null, null, 0, 0, null, null, null, null, 'All crab harvest closed 2026 (book year).', true, 30),
  ('tanner_crab', null, 'wa-ma-13', 'salt', 'prohibited', 'Marine Areas 12 (south of Ayock Point), and 13 — Dungeness, Red Rock, and Tanner Crab: Closed to crab harvest in 2026.', 'https://www.eregulations.com/washington/fishing/crab-rules', 'WDFW — 2026-2027 Washington Sport Fishing Rules (Crab Rules)', '2026-06-18', '2026-09-02', 4,
   null, null, 0, 0, null, null, null, null, 'All crab harvest closed 2026 (book year).', true, 30),
  ('dungeness_crab', null, 'wa-ma-1-4-coastal', 'salt', 'bag_limit', 'Dungeness Crab (Pacific Ocean Daily Limits/Rules): 6 crabs, 6" minimum size, males only, and in hardshell condition.', 'https://www.eregulations.com/washington/fishing/crab-rules', 'WDFW — 2026-2027 Washington Sport Fishing Rules (Crab Rules)', '2026-06-18', '2026-09-02', 4,
   null, null, 6, null, 6, null, 'carapace_width', null, 'Males only, hardshell.', true, 14),
  ('red_rock_crab', null, 'wa-ma-1-4-coastal', 'salt', 'bag_limit', 'Red Rock Crab (Pacific Ocean Daily Limits/Rules): 6 crabs, 5" minimum size, of either sex, and in hardshell condition.', 'https://www.eregulations.com/washington/fishing/crab-rules', 'WDFW — 2026-2027 Washington Sport Fishing Rules (Crab Rules)', '2026-06-18', '2026-09-02', 4,
   null, null, 6, null, 5, null, 'carapace_width', null, 'Either sex, hardshell.', true, 14),
  (null, null, 'wa-ma-1-4-coastal', 'salt', 'season', 'Grays Harbor, and Marine Areas 1-3 and 4 (west of Bonilla-Tatoosh line) — Dungeness and Red Rock Crab: Open December 1 to September 15 for Pot Gear. Open year-round to other gear.', 'https://www.eregulations.com/washington/fishing/crab-rules', 'WDFW — 2026-2027 Washington Sport Fishing Rules (Crab Rules)', '2026-06-18', '2026-09-02', 4,
   null, null, null, null, null, null, null, null, 'Pot gear window Dec 1-Sep 15 (wraps the calendar year); non-pot gear year-round.', true, 30),
  (null, null, 'wa-willapa-bay', 'salt', 'season', 'Willapa Bay — Dungeness and Red Rock Crab: November 15 to September 15 for Pot Gear. Open year-round to other gear.', 'https://www.eregulations.com/washington/fishing/crab-rules', 'WDFW — 2026-2027 Washington Sport Fishing Rules (Crab Rules)', '2026-06-18', '2026-09-02', 4,
   null, null, null, null, null, null, null, null, 'Pot gear window Nov 15-Sep 15 (wraps the calendar year); non-pot gear year-round.', true, 30),
  ('dungeness_crab', null, 'wa-willapa-bay', 'salt', 'bag_limit', 'Dungeness Crab (Pacific Ocean Daily Limits/Rules): 6 crabs, 6" minimum size, males only, and in hardshell condition. (Willapa Bay runs the Pacific Ocean limits block per the Crab Rules area table.)', 'https://www.eregulations.com/washington/fishing/crab-rules', 'WDFW — 2026-2027 Washington Sport Fishing Rules (Crab Rules)', '2026-06-18', '2026-09-02', 4,
   null, null, 6, null, 6, null, 'carapace_width', null, 'Males only, hardshell.', true, 14),
  ('red_rock_crab', null, 'wa-willapa-bay', 'salt', 'bag_limit', 'Red Rock Crab (Pacific Ocean Daily Limits/Rules): 6 crabs, 5" minimum size, of either sex, and in hardshell condition. (Willapa Bay runs the Pacific Ocean limits block per the Crab Rules area table.)', 'https://www.eregulations.com/washington/fishing/crab-rules', 'WDFW — 2026-2027 Washington Sport Fishing Rules (Crab Rules)', '2026-06-18', '2026-09-02', 4,
   null, null, 6, null, 5, null, 'carapace_width', null, 'Either sex, hardshell.', true, 14),
  (null, null, 'wa-columbia-river', 'salt', 'season', 'East of a line from exposed end of north and south jetty upstream to a line between Tongue Point and Rocky Point — Dungeness and Red Rock Crab: Open year-round to all gear. Crab fishers may fish for crab in Oregon waters under Oregon rules and land into Washington ports of the Columbia River. A resident license from either state is required.', 'https://www.eregulations.com/washington/fishing/crab-rules', 'WDFW — 2026-2027 Washington Sport Fishing Rules (Crab Rules)', '2026-06-18', '2026-09-02', 4,
   null, null, null, null, null, null, null, null, 'OR reciprocity: WA/OR resident license valid; landings allowed into WA ports.', true, 60),
  ('dungeness_crab', null, 'wa-columbia-river', 'salt', 'bag_limit', 'Dungeness Crab (Columbia River Daily Limits/Rules): 12 crabs, 5¾" minimum size, males only, and in hardshell condition.', 'https://www.eregulations.com/washington/fishing/crab-rules', 'WDFW — 2026-2027 Washington Sport Fishing Rules (Crab Rules)', '2026-06-18', '2026-09-02', 4,
   null, null, 12, null, 5.75, null, 'carapace_width', null, 'Males only, hardshell.', true, 14),
  ('red_rock_crab', null, 'wa-columbia-river', 'salt', 'bag_limit', 'Red Rock Crab (Columbia River Daily Limits/Rules): 6 crabs, 5" minimum size, of either sex, and in hardshell condition.', 'https://www.eregulations.com/washington/fishing/crab-rules', 'WDFW — 2026-2027 Washington Sport Fishing Rules (Crab Rules)', '2026-06-18', '2026-09-02', 4,
   null, null, 6, null, 5, null, 'carapace_width', null, 'Either sex, hardshell.', true, 14);

insert into public.reg_pack (id, version, published_at, notes) values
  ('washington-2026-09-02', 4, '2026-09-02T12:00:00Z', 'Washington ocean Marine Areas 1-4 (WDFW news release March 5, 2026) — v2 deepens with the inside-waters doctrine (no rockfish 6-13, barbless hooks 5-13), Puget Sound halibut windows (1/day, 6/yr, catch record card), the North Coast 20-fathom retention list, the C-shaped yelloweye conservation area, wolf-eel closure, and the five-additional-flatfish rule. v3 lands the Puget Sound pamphlet tables for Marine Areas 9, 10 and 13 verbatim (2026-27 book, updated June 18 2026): 15 bottomfish daily, >120ft fishing prohibited, descending device required, lingcod May 1-Jun 15 slot 26-36 in (spear May 21-Jun 15, hook-and-line from May 1), cabezon May 1-Nov 30 @18 in @1, rockfish closed, cod/pollock/hake/wolf-eel closed, salmon headline windows as notes. v4 lands the Crab Rules page verbatim: Puget Sound (Dungeness 5 @ 6.25 in males hardshell / Red Rock 6 @ 5 in / Tanner 6 @ 4.5 in; CRC + endorsement; MA12 south of Ayock Point + MA13 closed to crab in 2026), Pacific Ocean (Dungeness 6 @ 6 in + Red Rock 6 @ 5 in; pot window Dec 1-Sep 15, year-round other gear; Willapa Bay pots Nov 15-Sep 15), Columbia River estuary (Dungeness 12 @ 5.75 in, year-round all gear), European green crab report-and-release. Shrimp still pending.')
on conflict (id) do update set version = excluded.version, notes = excluded.notes;
